//! The Angler's daily quest, generated from the game's own rules.
//!
//! One of forty-one fish is asked for each dawn, but not every fish is catchable in every world:
//! some only exist in hardmode, some only in one evil or the other, and three want a boss to have
//! fallen first. Asking for a fish that cannot be caught is not a small bug — it costs the player
//! a whole day of a reward track.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.

/// Which evil a fish needs the world to have.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Evil {
    /// Catchable either way.
    Either,
    Corruption,
    Crimson,
}

/// One fish the Angler may ask for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Quest {
    /// The item the fish is.
    pub item: i32,
    /// Whether the world must be in hardmode.
    pub hardmode: bool,
    /// Which evil the world must have, if it matters.
    pub evil: Evil,
    /// Whether some boss must already have fallen.
    pub any_boss: bool,
}

/// Every fish, in the order the daily roll indexes them.
pub const QUESTS: [Quest; 41] = [
    Quest {
        item: 2450,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2451,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2452,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2453,
        hardmode: false,
        evil: Evil::Either,
        any_boss: true,
    },
    Quest {
        item: 2454,
        hardmode: true,
        evil: Evil::Corruption,
        any_boss: false,
    },
    Quest {
        item: 2455,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2456,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2457,
        hardmode: false,
        evil: Evil::Corruption,
        any_boss: false,
    },
    Quest {
        item: 2458,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2459,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2460,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2461,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2462,
        hardmode: true,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2463,
        hardmode: true,
        evil: Evil::Crimson,
        any_boss: false,
    },
    Quest {
        item: 2464,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2465,
        hardmode: true,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2466,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2467,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2468,
        hardmode: true,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2469,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2470,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2471,
        hardmode: true,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2472,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2473,
        hardmode: true,
        evil: Evil::Either,
        any_boss: true,
    },
    Quest {
        item: 2474,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2475,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2476,
        hardmode: false,
        evil: Evil::Either,
        any_boss: true,
    },
    Quest {
        item: 2477,
        hardmode: false,
        evil: Evil::Crimson,
        any_boss: false,
    },
    Quest {
        item: 2478,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2479,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2480,
        hardmode: true,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2481,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2482,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2483,
        hardmode: true,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2484,
        hardmode: true,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2485,
        hardmode: false,
        evil: Evil::Corruption,
        any_boss: false,
    },
    Quest {
        item: 2486,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2487,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 2488,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 4393,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
    Quest {
        item: 4394,
        hardmode: false,
        evil: Evil::Either,
        any_boss: false,
    },
];

/// Whether a fish can be asked for in a world in this state.
pub fn available(quest: &Quest, hardmode: bool, crimson: bool, any_boss_downed: bool) -> bool {
    if quest.hardmode && !hardmode {
        return false;
    }
    match quest.evil {
        Evil::Either => {}
        Evil::Crimson if !crimson => return false,
        Evil::Corruption if crimson => return false,
        _ => {}
    }
    if quest.any_boss && !any_boss_downed {
        return false;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A fresh world can still be given a quest, or the Angler is useless until hardmode.
    #[test]
    fn a_fresh_world_has_fish_to_ask_for() {
        let open = QUESTS
            .iter()
            .filter(|q| available(q, false, false, false))
            .count();
        assert!(open > 10, "only {open} fish available in a fresh world");
    }

    /// Hardmode opens more than pre-hardmode, not fewer.
    #[test]
    fn hardmode_opens_more_fish() {
        let before = QUESTS
            .iter()
            .filter(|q| available(q, false, false, true))
            .count();
        let after = QUESTS
            .iter()
            .filter(|q| available(q, true, false, true))
            .count();
        assert!(
            after > before,
            "{after} in hardmode against {before} before"
        );
    }

    /// The two evils each lock some fish and open others, and neither locks everything.
    #[test]
    fn each_evil_has_its_own_fish() {
        let corruption: Vec<i32> = QUESTS
            .iter()
            .filter(|q| available(q, true, false, true))
            .map(|q| q.item)
            .collect();
        let crimson: Vec<i32> = QUESTS
            .iter()
            .filter(|q| available(q, true, true, true))
            .map(|q| q.item)
            .collect();
        assert_ne!(corruption, crimson, "the evils should differ");
        assert!(corruption.iter().any(|i| !crimson.contains(i)));
        assert!(crimson.iter().any(|i| !corruption.contains(i)));
    }

    /// Every fish is a real item id and none is listed twice.
    #[test]
    fn the_fish_are_distinct_items() {
        let mut seen = std::collections::HashSet::new();
        for quest in QUESTS {
            assert!(quest.item > 0, "a fish with no item");
            assert!(seen.insert(quest.item), "item {} listed twice", quest.item);
        }
    }
}
