//! Buff tables, generated from the game's own.
//!
//! Nothing here is an algorithm. The rules that read these live in `game::npc` and
//! `game::server`; what varies per buff id or per NPC type is data, and data belongs in a
//! table rather than in a hand-written match a later version would silently invalidate.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.

/// How many buff ids exist. `BuffID.Count`.
pub const BUFF_COUNT: usize = 401;

/// Whether a buff id is a debuff, from `Main.debuff`.
///
/// `AddBuff` reads this to decide what it may evict when an NPC's twenty slots are full: a
/// good buff can be pushed out to make room, a debuff never can.
pub const DEBUFF: [bool; 401] = [
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, true, true, true, true, true, true, false,
    false, true, false, true, true, true, true, true, true, true, true, true, true, false, false,
    false, true, true, false, true, true, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, true, true, true,
    true, false, true, false, false, false, false, false, false, false, true, false, false, false,
    false, false, true, true, true, true, false, false, false, false, true, false, false, false,
    false, false, false, false, false, true, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, true, true, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, true,
    false, false, false, false, false, false, true, true, true, true, true, true, false, false,
    false, true, false, false, true, true, true, false, true, false, false, true, true, false,
    false, false, false, true, false, false, false, false, false, false, false, false, false,
    false, false, false, false, true, false, false, true, false, false, true, false, false, false,
    false, true, true, true, true, false, true, false, false, false, true, true, false, false,
    false, false, false, false, false, false, false, false, true, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, true, true, false, true, true,
    false, false, false, false, false, false, false, true, true, true, false, false, false, false,
    false, false, false, false, false, true, false, false, false, false, false, true, false, false,
    true, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, true, false, true, true, true, true,
];

/// Whether a buff id is a whip's mark, from `BuffID.Sets.IsAnNPCWhipDebuff`.
///
/// Immunity treats the two kinds separately — several bosses shrug off every debuff but can
/// still be tagged by a whip — so the distinction has to be kept.
pub const WHIP_MARK: [bool; 401] = [
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, true, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, true, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false,
];

/// Whether a client may ask the server to take a buff off an NPC, from
/// `BuffID.Sets.CanBeRemovedByNetMessage`.
///
/// Empty in this version, and deliberately so: the packet exists and the game validates
/// against this set, so every request is refused. Keeping the table means a later version
/// that fills it in needs no code change.
pub const REMOVABLE_BY_REQUEST: [bool; 401] = [
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false,
];

/// Buffs whose timer does not run down, from `BuffID.Sets.TimeLeftDoesNotDecrease`.
pub const TIME_DOES_NOT_DECREASE: [bool; 401] = [
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, true, true, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, true, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, true, false, false, false, false, false, false,
    false, false, true, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, true, false, false, false, false,
    false, false, false, false, false, false, false, false, false, true, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, true, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false,
];

/// Buffs a PvP-flagged player may spread to another PvP-flagged player, from `Main.pvpBuff`.
///
/// Gates packet 55 (`AddPlayerBuffPvP`): a hostile-marked player who lands one of these on
/// another hostile-marked player asks the server to relay it, rather than the target's own
/// client trusting the attacker's client directly.
pub const PVP_BUFF: [bool; 401] = [
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, true, false, false, false, true, false, false,
    false, false, false, true, true, false, false, false, false, true, false, false, true, false,
    false, false, false, true, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, true, true, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, true, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, true, true,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, true, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, true, false, false, true, true, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, true, true, true, true,
];

/// The distinct immunity masks, as bitmaps over buff ids.
///
/// Six hundred and ninety-one NPC types share far fewer than that many distinct sets of
/// immunities, so the masks are interned and [`IMMUNITY_OF`] indexes into them.
const MASKS: [[u64; 7]; 34] = [
    [
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
    ],
    [
        0x0000000040100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000000,
        0x0000000000000000,
    ],
    [
        0x0000000080000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
    ],
    [
        0x0000000080000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000200000000,
        0x0000000000000000,
    ],
    [
        0x00000000c0000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000000,
        0x0000000000000000,
    ],
    [
        0x00000000c1100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000008,
        0x0000000000000000,
    ],
    [
        0x0000000081000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000008,
        0x0000000000000000,
    ],
    [
        0x00000000c0100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000000,
        0x0000000000000000,
    ],
    [
        0x00000000c0100000,
        0x0000000000000000,
        0x0000020000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000001020000,
        0x0000000000000000,
    ],
    [
        0x00000000c0100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000200000000,
        0x0000000000000000,
    ],
    [
        0x0000000041100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000008,
        0x0000000000000000,
    ],
    [
        0x0000000001000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000008,
        0x0000000000000000,
    ],
    [
        0x0000000081000000,
        0x0000000000000000,
        0x0000000002000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000008,
        0x0000000000000000,
    ],
    [
        0xfffffffffffffffe,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xfffffffdffffffff,
        0x000000000001ffff,
    ],
    [
        0x00000080c1100000,
        0x0000000000000040,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000200000008,
        0x0000000000000800,
    ],
    [
        0xfffffffffffffffe,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0x000000000001ffff,
    ],
    [
        0xfffffffffffffffe,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffbfffffffffffff,
        0xfffffbfdffffffff,
        0x000000000001ffff,
    ],
    [
        0x0000008080000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
    ],
    [
        0xfffffffffffffffe,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffffffffffffffff,
        0xffbfffffffffffff,
        0xfffffbffffffffff,
        0x000000000001ffff,
    ],
    [
        0x0000000040100000,
        0x0000000000000040,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000000,
        0x0000000000000800,
    ],
    [
        0x0000100040100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000010,
        0x0000000000000000,
    ],
    [
        0x0000100000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000010,
        0x0000000000000000,
    ],
    [
        0x00001000c0100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000010,
        0x0000000000000000,
    ],
    [
        0x0000000040100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000200000000,
        0x0000000000000000,
    ],
    [
        0x00000000c1100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000200000008,
        0x0000000000000000,
    ],
    [
        0x0000001040100000,
        0x0000000000000020,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000000,
        0x0000000000000000,
    ],
    [
        0x00000010c0100000,
        0x0000000000000020,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000000,
        0x0000000000000000,
    ],
    [
        0x00001090c1100000,
        0x0000000000000060,
        0x2000000002000000,
        0x0000000000001800,
        0x0000000000000000,
        0x0080000000000018,
        0x0000000000000800,
    ],
    [
        0x00001000c0100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000200000010,
        0x0000000000000000,
    ],
    [
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000200000000,
        0x0000000000000000,
    ],
    [
        0x0000000080000000,
        0x0000000000000000,
        0x0000000002000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
    ],
    [
        0x00001090c1100000,
        0x0000000000000060,
        0x2000000002000000,
        0x0000000000001800,
        0x0000000000000000,
        0x0080000200000018,
        0x0000000000000800,
    ],
    [
        0x0000000081000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000200000008,
        0x0000000000000000,
    ],
    [
        0x00001000c1100000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0000000000000000,
        0x0080000000000018,
        0x0000000000000000,
    ],
];

/// Which mask each NPC type uses, from `NPCID.Sets.DebuffImmunitySets` with the corrections
/// `NPC.SetDefaults` applies on top (poison implies bleeding and hemorrhage, ichor implies
/// broken armour, and shimmer immunity is set from its own list either way).
const IMMUNITY_OF: [u16; 697] = [
    0, 1, 0, 0, 2, 3, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 1, 2, 2, 2, 2, 1, 2, 5, 6, 3, 0, 0, 0, 2, 3, 1,
    7, 3, 7, 8, 7, 2, 2, 5, 5, 5, 7, 7, 1, 7, 2, 0, 2, 0, 9, 0, 0, 0, 2, 2, 2, 2, 2, 10, 11, 2, 12,
    2, 2, 2, 12, 2, 13, 2, 14, 1, 15, 0, 2, 0, 2, 1, 0, 0, 0, 1, 16, 5, 5, 7, 0, 2, 2, 2, 2, 2, 2,
    0, 2, 2, 2, 2, 2, 2, 2, 17, 2, 2, 0, 2, 2, 2, 2, 2, 1, 0, 3, 6, 6, 3, 3, 2, 2, 2, 1, 1, 7, 2,
    2, 7, 7, 8, 7, 7, 7, 7, 0, 0, 16, 16, 16, 1, 1, 18, 10, 19, 2, 20, 20, 20, 2, 20, 2, 2, 21, 11,
    0, 0, 21, 0, 12, 2, 0, 0, 2, 21, 0, 1, 1, 1, 1, 20, 0, 22, 0, 0, 7, 2, 2, 7, 7, 2, 2, 5, 0, 1,
    7, 1, 20, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 20, 1, 1, 0, 1, 1, 1, 1, 7, 21, 2, 2, 2, 7, 7,
    0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 7, 0, 0, 1, 0, 2, 2, 2, 2, 7, 7, 7, 7, 7, 1, 1, 1, 1, 1, 2, 2,
    22, 23, 24, 24, 24, 24, 24, 7, 0, 0, 16, 0, 0, 2, 0, 0, 7, 7, 2, 7, 7, 7, 2, 2, 2, 25, 1, 1, 1,
    1, 1, 1, 1, 1, 10, 10, 10, 10, 7, 7, 7, 7, 7, 7, 1, 16, 7, 26, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
    1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 27, 0, 0, 0, 0, 0, 1, 1, 1, 9, 0, 5, 5, 10, 16, 0, 0,
    1, 1, 1, 1, 2, 21, 21, 21, 5, 0, 21, 28, 22, 22, 2, 0, 0, 0, 21, 22, 2, 2, 2, 3, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 29, 29, 18, 29, 29, 9, 9, 29, 29,
    29, 15, 18, 18, 18, 3, 3, 3, 9, 3, 3, 3, 3, 3, 3, 3, 3, 3, 29, 29, 29, 3, 3, 3, 29, 29, 29, 24,
    29, 3, 3, 16, 29, 29, 29, 29, 29, 3, 29, 0, 21, 0, 0, 0, 0, 0, 2, 2, 16, 13, 2, 2, 2, 2, 2, 2,
    2, 2, 1, 1, 1, 1, 2, 16, 16, 16, 16, 16, 16, 0, 2, 0, 0, 0, 2, 0, 5, 0, 0, 0, 30, 30, 5, 5, 5,
    5, 2, 2, 2, 2, 1, 5, 5, 2, 2, 2, 2, 2, 0, 0, 13, 16, 16, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    16, 0, 0, 2, 2, 2, 2, 2, 2, 3, 18, 3, 3, 24, 31, 3, 3, 0, 0, 0, 0, 0, 0, 1, 1, 0, 27, 0, 23, 0,
    1, 2, 2, 2, 7, 2, 2, 2, 2, 2, 2, 3, 15, 2, 32, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 0, 0, 0, 13, 13, 13, 0, 0, 2, 2, 0, 0, 2, 2, 3, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 33,
    0, 5, 0, 2, 0, 1, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 9, 9, 9, 9, 2,
    18, 2, 0, 3, 3, 29, 3, 3, 3, 2, 2, 2, 2, 2, 29, 3, 3, 3, 3, 3, 3, 3, 3, 2, 13, 13, 2, 2, 16, 0,
    2, 7, 7, 2, 2,
];

/// Whether `npc_type` can be given `buff`.
///
/// An unknown type is immune to nothing, which matches the game: `SetDefaults` clears the
/// whole array for a type with no entry.
pub fn npc_is_immune(npc_type: u16, buff: u16) -> bool {
    let buff = buff as usize;
    if buff == 0 || buff >= BUFF_COUNT {
        return true;
    }
    let Some(&slot) = IMMUNITY_OF.get(npc_type as usize) else {
        return false;
    };
    MASKS[slot as usize][buff / 64] >> (buff % 64) & 1 == 1
}

/// Whether a buff id is one the game counts as a debuff.
pub fn is_debuff(buff: u16) -> bool {
    DEBUFF.get(buff as usize).copied().unwrap_or(false)
}

/// Whether a PvP-flagged player may spread `buff` to another over packet 55.
pub fn is_pvp_spreadable(buff: u16) -> bool {
    PVP_BUFF.get(buff as usize).copied().unwrap_or(false)
}
