//! How a golf ball behaves on each kind of tile, generated from the game's own material data.
//!
//! A golf ball is the one projectile in the roster whose whole behaviour is a physics simulation
//! rather than a routine, and *what it is rolling on* is half of that simulation: a ball skids
//! across ice, dies in sand, and barely bounces at all on a slime block. `aiStyle 149` reads
//! these three numbers on every contact.
//!
//! * **Direct** is what a head-on bounce keeps, along the surface normal.
//! * **Side** is what a glancing one keeps, along the surface. This is the number that decides how
//!   far a ball rolls, and it is where the materials differ most: 1.0 on ice against 0.2 on sand.
//! * **Through** is what passing *inside* a non-solid tile keeps each substep - cobwebs and
//!   plants, which slow a ball without stopping it.
//!
//! The two figures the game's own material data also carries are deliberately absent.
//! `ClubImpactDampening` scales the swing that launches a ball and
//! `ImpactDampeningResistanceEfficiency` scales an accessory that resists the dampening; both are
//! applied on the client that took the shot, and a server never takes one.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.

/// What one kind of tile does to a ball that hits it.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Golf {
    /// What a head-on bounce keeps, along the surface normal.
    pub direct: f32,
    /// What a glancing one keeps, along the surface. This is what decides how far a ball rolls.
    pub side: f32,
    /// What passing *inside* a non-solid tile keeps, each substep.
    pub through: f32,
}

/// The `"Default"` material, used for every tile the game's own data does not name.
pub const DEFAULT: Golf = Golf {
    direct: 0.95,
    side: 0.98,
    through: 1.0,
};

/// 692 tiles the game names a material for; 0 names in its table are not tiles this build knows.
const BY_TILE: [Golf; 693] = [
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.95,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.5,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.1,
        side: 0.1,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.1,
        side: 0.1,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.5,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 1.0,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 1.0,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 1.0,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 1.0,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.3,
        side: 0.2,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.7,
        side: 0.4,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.94,
        side: 0.99,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.98,
        side: 0.98,
        through: 0.99,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 1.0,
        side: 1.0,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.1,
        side: 0.1,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.9,
        side: 0.95,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
    Golf {
        direct: 0.95,
        side: 0.98,
        through: 1.0,
    },
];

/// How a ball behaves on this tile.
pub fn of(tile: u16) -> Golf {
    BY_TILE.get(tile as usize).copied().unwrap_or(DEFAULT)
}
