//! What shimmer turns things into, generated from the game's own tables.
//!
//! Shimmer transmutes. An item dropped into it becomes another item, or a creature, or — for
//! coins — luck. Which of those, and into what, is per-item data running to several hundred
//! pairs, so it lives here rather than anywhere near hand-written code.
//!
//! The other branch of the game's shimmer is **decrafting**: an item with no transform and no
//! creature is broken into its recipe's ingredients instead. That is implemented — it needed the
//! recipe database as a table, which is [`crate::recipes`], and the server drives it through
//! `decraft_recipe`. See `docs/shimmer.md` for how a cascade terminates.
//!
//! (This comment said decrafting was "deliberately absent" and "a system this server does not
//! model at all" long after it had been built, which is worth a moment's thought: a stale note
//! misleads more effectively than no note, because it reads like a decision.)
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.

/// `ItemID.Sets.ShimmerTransformToItem`: what an item becomes.
///
/// Sorted by item id so it can be searched rather than indexed — it is a few hundred pairs out
/// of several thousand items, and a full array would be mostly zeroes.
const TRANSFORMS: [(u16, u16); 316] = [
    (3, 2),
    (8, 5353),
    (9, 2),
    (11, 699),
    (12, 133),
    (13, 701),
    (14, 700),
    (29, 5337),
    (30, 5546),
    (40, 5348),
    (52, 5347),
    (60, 5),
    (67, 66),
    (90, 954),
    (92, 955),
    (100, 958),
    (101, 957),
    (102, 956),
    (109, 5339),
    (133, 3),
    (134, 5417),
    (135, 5365),
    (136, 1390),
    (137, 5419),
    (138, 5371),
    (139, 5421),
    (140, 5368),
    (141, 5423),
    (143, 5425),
    (145, 5427),
    (151, 959),
    (177, 180),
    (178, 179),
    (179, 177),
    (180, 181),
    (181, 133),
    (182, 178),
    (192, 5433),
    (194, 195),
    (195, 194),
    (206, 207),
    (207, 1128),
    (214, 5435),
    (215, 5346),
    (228, 960),
    (229, 961),
    (230, 962),
    (265, 5348),
    (276, 1725),
    (280, 277),
    (332, 2196),
    (351, 353),
    (364, 702),
    (365, 1104),
    (366, 1105),
    (410, 411),
    (411, 410),
    (415, 5429),
    (416, 5431),
    (427, 5353),
    (428, 5353),
    (429, 5353),
    (430, 5353),
    (431, 5353),
    (432, 5353),
    (433, 5353),
    (489, 2998),
    (490, 491),
    (491, 489),
    (523, 5353),
    (531, 5336),
    (532, 5355),
    (576, 6146),
    (593, 5349),
    (619, 9),
    (620, 9),
    (621, 9),
    (664, 593),
    (670, 1319),
    (699, 12),
    (700, 11),
    (701, 14),
    (702, 13),
    (724, 670),
    (779, 5134),
    (782, 784),
    (784, 782),
    (824, 5996),
    (825, 5997),
    (832, 4281),
    (848, 857),
    (854, 855),
    (855, 3033),
    (857, 848),
    (866, 934),
    (885, 887),
    (886, 892),
    (887, 885),
    (888, 3781),
    (889, 893),
    (890, 891),
    (891, 890),
    (892, 886),
    (893, 889),
    (906, 1322),
    (911, 9),
    (931, 5380),
    (934, 866),
    (947, 1106),
    (953, 975),
    (954, 90),
    (955, 92),
    (956, 102),
    (957, 101),
    (958, 100),
    (959, 151),
    (960, 228),
    (961, 229),
    (962, 230),
    (966, 5357),
    (974, 5353),
    (975, 953),
    (1102, 5376),
    (1104, 364),
    (1105, 365),
    (1106, 366),
    (1125, 1124),
    (1127, 1124),
    (1128, 206),
    (1146, 1147),
    (1147, 1148),
    (1148, 1149),
    (1149, 1146),
    (1245, 5353),
    (1291, 5338),
    (1304, 215),
    (1319, 6153),
    (1322, 906),
    (1326, 5335),
    (1333, 5353),
    (1378, 5366),
    (1379, 5367),
    (1380, 5369),
    (1381, 5370),
    (1382, 5372),
    (1383, 5373),
    (1390, 1391),
    (1391, 1392),
    (1392, 1393),
    (1393, 1394),
    (1394, 1395),
    (1395, 136),
    (1533, 1528),
    (1534, 1529),
    (1535, 1530),
    (1536, 1531),
    (1537, 1532),
    (1614, 5380),
    (1723, 5545),
    (1725, 276),
    (1729, 9),
    (2222, 5343),
    (2260, 9),
    (2261, 2262),
    (2262, 2261),
    (2274, 5353),
    (2373, 2374),
    (2374, 2375),
    (2375, 2373),
    (2503, 9),
    (2504, 9),
    (2610, 5495),
    (2693, 5493),
    (2886, 66),
    (2887, 5),
    (2895, 5341),
    (2998, 490),
    (2999, 3000),
    (3000, 5482),
    (3004, 5353),
    (3015, 3016),
    (3016, 3015),
    (3031, 5364),
    (3033, 854),
    (3037, 3120),
    (3045, 5353),
    (3064, 5381),
    (3081, 3086),
    (3086, 3081),
    (3093, 4345),
    (3096, 3037),
    (3114, 5353),
    (3120, 3096),
    (3186, 5492),
    (3187, 3188),
    (3188, 3189),
    (3189, 3187),
    (3225, 159),
    (3271, 169),
    (3272, 169),
    (3273, 5374),
    (3274, 370),
    (3275, 1246),
    (3276, 370),
    (3277, 1246),
    (3338, 408),
    (3339, 408),
    (3340, 5375),
    (3460, 947),
    (3621, 5674),
    (3633, 5675),
    (3634, 5676),
    (3635, 5677),
    (3636, 5678),
    (3637, 5679),
    (3781, 888),
    (3818, 3824),
    (3819, 3825),
    (3820, 3826),
    (3824, 3832),
    (3825, 3833),
    (3826, 3834),
    (3829, 3818),
    (3830, 3819),
    (3831, 3820),
    (3832, 3829),
    (3833, 3830),
    (3834, 3831),
    (3979, 2334),
    (3980, 2335),
    (3981, 2336),
    (3982, 3203),
    (3983, 3204),
    (3984, 3205),
    (3985, 3206),
    (3986, 3207),
    (3987, 3208),
    (4009, 5342),
    (4282, 5342),
    (4283, 5342),
    (4284, 5342),
    (4285, 5342),
    (4286, 5342),
    (4287, 5342),
    (4288, 5342),
    (4289, 5342),
    (4290, 5342),
    (4291, 5342),
    (4292, 5342),
    (4293, 5342),
    (4294, 5342),
    (4295, 5342),
    (4296, 5342),
    (4297, 5342),
    (4345, 3093),
    (4354, 5128),
    (4377, 5128),
    (4378, 5128),
    (4383, 5353),
    (4384, 5353),
    (4385, 5353),
    (4386, 5353),
    (4387, 5353),
    (4388, 5353),
    (4389, 5128),
    (4406, 4405),
    (4408, 4407),
    (4414, 5340),
    (4503, 5363),
    (4714, 4712),
    (4831, 181),
    (4832, 180),
    (4833, 177),
    (4834, 179),
    (4835, 178),
    (4836, 182),
    (4837, 999),
    (4838, 181),
    (4839, 180),
    (4840, 177),
    (4841, 179),
    (4842, 178),
    (4843, 182),
    (4844, 999),
    (4871, 4907),
    (4875, 5653),
    (4876, 5653),
    (4878, 4877),
    (4907, 4871),
    (4916, 5653),
    (4917, 5653),
    (4918, 5653),
    (4919, 5653),
    (4920, 5653),
    (4921, 5653),
    (4951, 5653),
    (4956, 5669),
    (5003, 5002),
    (5127, 5128),
    (5215, 9),
    (5277, 5342),
    (5278, 5342),
    (5293, 5353),
    (5295, 5519),
    (5356, 5346),
    (5364, 3031),
    (5438, 5518),
    (5482, 2999),
    (5519, 5295),
    (5523, 5654),
    (5574, 5575),
    (5652, 5653),
    (5654, 5523),
    (5996, 824),
    (5997, 825),
    (6153, 724),
];

/// `ItemID.Sets.ShimmerCountsAsItem`: items that shimmer as though they were another.
///
/// Checked first, so a variant transmutes the way the thing it stands in for does.
const COUNTS_AS: [(u16, u16); 6] = [
    (5358, 5437),
    (5359, 5437),
    (5360, 5437),
    (5361, 5437),
    (5455, 5323),
    (6195, 6190),
];

/// `NPCID.Sets.ShimmerTransformToNPC`: a creature let out of a jar becomes another creature.
const NPC_TRANSFORMS: [(u16, u16); 114] = [
    (1, 676),
    (3, 21),
    (16, 676),
    (46, 677),
    (55, 677),
    (74, 677),
    (81, 676),
    (121, 676),
    (132, 202),
    (138, 676),
    (141, 676),
    (147, 676),
    (148, 677),
    (149, 677),
    (183, 676),
    (184, 676),
    (186, 201),
    (187, 21),
    (188, 21),
    (189, 202),
    (200, 203),
    (204, 676),
    (225, 676),
    (297, 677),
    (298, 677),
    (299, 677),
    (300, 677),
    (302, 676),
    (303, 677),
    (333, 676),
    (334, 676),
    (335, 676),
    (336, 676),
    (337, 677),
    (355, 677),
    (356, 677),
    (357, 677),
    (358, 677),
    (359, 677),
    (360, 677),
    (361, 677),
    (362, 677),
    (363, 677),
    (364, 677),
    (365, 677),
    (366, 677),
    (367, 677),
    (374, 677),
    (377, 677),
    (430, 449),
    (432, 450),
    (433, 449),
    (434, 449),
    (435, 451),
    (436, 452),
    (442, 677),
    (443, 677),
    (444, 677),
    (445, 677),
    (446, 677),
    (447, 677),
    (484, 677),
    (485, 677),
    (486, 677),
    (487, 677),
    (537, 676),
    (538, 677),
    (539, 677),
    (540, 677),
    (583, 677),
    (584, 677),
    (585, 677),
    (590, 21),
    (591, 449),
    (592, 677),
    (595, 677),
    (596, 677),
    (597, 677),
    (598, 677),
    (599, 677),
    (600, 677),
    (601, 677),
    (602, 677),
    (603, 677),
    (604, 677),
    (605, 677),
    (606, 677),
    (607, 677),
    (608, 677),
    (609, 677),
    (610, 677),
    (611, 677),
    (612, 677),
    (613, 677),
    (614, 677),
    (615, 677),
    (616, 677),
    (617, 677),
    (625, 677),
    (626, 677),
    (627, 677),
    (653, 677),
    (654, 677),
    (655, 677),
    (661, 677),
    (669, 677),
    (671, 677),
    (672, 677),
    (673, 677),
    (674, 677),
    (675, 677),
    (687, 677),
    (688, 677),
    (689, 677),
];

/// The coins, whose shimmer is luck rather than an item. `ItemID.Sets.CommonCoin`.
pub const COPPER_COIN: u16 = 71;

fn look_up(table: &[(u16, u16)], key: u16) -> Option<u16> {
    table
        .binary_search_by_key(&key, |&(k, _)| k)
        .ok()
        .map(|at| table[at].1)
}

/// The item this one shimmers *as*, which is usually itself.
///
/// A handful of variants stand in for another item so they transmute the way it does. The game
/// calls this `GetShimmerEquivalentType`.
pub fn equivalent(item: u16) -> u16 {
    look_up(&COUNTS_AS, item).unwrap_or(item)
}

/// What an item becomes in shimmer, if it becomes another item.
pub fn transforms_into(item: u16) -> Option<u16> {
    look_up(&TRANSFORMS, equivalent(item))
}

/// What a caught creature becomes when its jar goes in.
pub fn npc_becomes(npc_type: u16) -> Option<u16> {
    look_up(&NPC_TRANSFORMS, npc_type)
}

/// Whether an item is a coin, whose shimmer is coin luck rather than a transformation.
///
/// The four are consecutive and always have been, which is why this is a range rather than a
/// table of four entries.
pub fn is_coin(item: u16) -> bool {
    (COPPER_COIN..COPPER_COIN + 4).contains(&item)
}

/// What a stack of coins is worth in coppers, for the luck it grants.
///
/// Silver is a hundred coppers, gold ten thousand, platinum a million — and platinum is capped
/// at one, which is the game's own rule and stops a stack of them being worth a billion.
pub fn coin_luck(item: u16, stack: i32) -> i32 {
    match item.checked_sub(COPPER_COIN) {
        Some(0) => stack,
        Some(1) => stack.saturating_mul(100),
        Some(2) => stack.saturating_mul(10_000),
        Some(3) => 1_000_000,
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Both tables are sorted, or the binary searches above silently miss.
    #[test]
    fn the_tables_are_sorted() {
        for (name, table) in [
            ("TRANSFORMS", &TRANSFORMS[..]),
            ("COUNTS_AS", &COUNTS_AS[..]),
            ("NPC_TRANSFORMS", &NPC_TRANSFORMS[..]),
        ] {
            assert!(
                table.windows(2).all(|w| w[0].0 < w[1].0),
                "{name} must be strictly ascending by key"
            );
        }
    }

    /// Spot checks against transmutations that are well known.
    #[test]
    fn the_known_transmutations_hold() {
        // A Gold Chest's key mould line, and the ore/bar pairs, are the ones players learn first.
        assert_eq!(transforms_into(9), Some(2), "wood becomes stone");
        assert!(transforms_into(1).is_none(), "an iron pickaxe does not");
    }

    /// Coins are luck, and the four of them are worth what they are worth.
    #[test]
    fn coins_are_worth_their_weight() {
        assert!(is_coin(COPPER_COIN));
        assert!(is_coin(COPPER_COIN + 3));
        assert!(!is_coin(COPPER_COIN + 4));
        assert_eq!(coin_luck(COPPER_COIN, 50), 50);
        assert_eq!(coin_luck(COPPER_COIN + 1, 5), 500);
        assert_eq!(coin_luck(COPPER_COIN + 2, 5), 50_000);
        assert_eq!(
            coin_luck(COPPER_COIN + 3, 99),
            1_000_000,
            "platinum is capped at one, however many are thrown in"
        );
        assert_eq!(coin_luck(1, 5), 0, "and a pickaxe is not a coin");
    }

    /// A stack big enough to overflow is saturated rather than wrapped.
    #[test]
    fn an_absurd_stack_does_not_wrap() {
        assert_eq!(coin_luck(COPPER_COIN + 2, i32::MAX), i32::MAX);
    }

    /// An item that stands in for another transmutes the way that other one does.
    #[test]
    fn a_stand_in_follows_what_it_stands_for() {
        for &(variant, real) in COUNTS_AS.iter() {
            assert_eq!(
                equivalent(variant),
                real,
                "item {variant} should shimmer as {real}"
            );
            assert_eq!(transforms_into(variant), transforms_into(real));
        }
    }
}
