//! Which tiles a liquid destroys on contact, generated from the game's own setup code.
//!
//! `Main.tileLavaDeath` and `Main.tileWaterDeath`: a lava or water tile that spreads into one of
//! these kills it, the way a torch goes out in a flood or a table burns in lava. There is no
//! shimmer equivalent in 1.4.5.8: shimmer transforms what touches it rather than destroying
//! furniture, and no `tileShimmerDeath`-shaped array exists in the decompiled source.
//!
//! The consumer is `kill_drowned_furniture` (`game/server/systems.rs`), which reads whichever of
//! the two tables matches the liquid that arrived and kills the tile outright, exactly as
//! `Liquid.AddWater`'s own inline check does (`Liquid.cs:1196-1215`). This header used to say
//! nothing consulted the table yet, which stopped being true without the header noticing.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.

/// Whether a lava tile spreading into this one destroys it. `Main.tileLavaDeath`.
pub const LAVA_DEATH: [bool; 754] = [
    false, false, false, true, false, true, false, false, false, false, true, true, true, true,
    true, true, true, true, true, true, false, false, false, false, true, false, false, true, true,
    true, false, false, true, true, true, true, true, false, false, false, false, false, true,
    false, false, false, false, false, false, true, true, true, true, false, false, true, false,
    false, false, false, false, true, true, false, false, false, false, false, false, true, false,
    true, true, true, true, false, false, false, false, true, true, true, false, false, false,
    false, true, true, true, true, true, true, true, true, true, true, true, true, true, false,
    true, true, true, true, true, false, true, false, false, false, true, false, false, true,
    false, true, false, false, false, false, false, false, false, false, false, true, true, false,
    true, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, true, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, true, true, true, false, false, false, false, false, false,
    false, false, false, true, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, true, false, false, false, true, false, false,
    false, true, true, false, true, true, false, true, true, true, true, true, true, false, false,
    false, false, false, false, true, true, false, false, false, false, true, false, false, true,
    false, true, false, true, true, true, true, true, true, true, true, false, false, false, false,
    false, false, true, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, true, true, true, false, false, false, true, true, true, true,
    true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, false, false, false, false, false, true, true, true, true, false, false, false, true,
    true, false, false, false, false, false, false, false, false, false, false, true, false, false,
    true, true, false, false, false, false, false, false, false, false, false, false, false, false,
    true, true, true, true, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, true, false, false, false, false, false, false,
    false, false, false, true, false, false, false, true, true, true, true, true, false, false,
    false, false, true, false, false, false, false, false, false, false, false, false, true, true,
    false, false, false, false, false, false, true, false, false, false, false, false, false,
    false, false, false, false, false, true, false, true, false, false, false, false, false, false,
    false, true, true, true, true, true, false, false, false, false, false, false, false, false,
    false, false, false, false, true, true, true, false, true, true, false, false, false, false,
    false, true, true, true, false, false, false, true, false, true, false, false, false, false,
    false, false, false, false, false, false, false, false, true, true, true, true, true, true,
    true, false, false, true, true, false, false, true, false, true, false, false, false, false,
    false, false, false, false, false, false, true, true, false, false, false, false, false, false,
    false, false, true, false, false, false, false, false, false, false, true, true, true, false,
    true, true, false, false, false, false, true, false, false, false, false, false, true, false,
    false, true, true, false, true, true, true, true, true, true, true, false, true, true, true,
    false, false, false, true, true, false, true, true, true, true, true, true, true, false, false,
    false, false, false, true, true, true, true, false, false, false, false, false, false, false,
    false, true, false, false, false, false, false, false, false, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, false, false, false, false, false, false,
    true, true, true, true, true, true, false, false, false, false, true, true, true, true, false,
    false, false, true, false, false, true, true, false, true, true, true, true, true, false,
    false, false, false, false, false, false, true, true, true, false, false, false, true, false,
    false, false, false, false, false, false, true, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, true, true, true, true, true,
    true, true, true, true, false, true, false, false, true, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false,
];

/// Whether a water tile spreading into this one destroys it. `Main.tileWaterDeath`.
pub const WATER_DEATH: [bool; 754] = [
    false, false, false, false, true, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, true,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, true, false, false, false, false, true, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, true, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, true, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, true, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, true, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, true, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, true, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false,
];

/// Whether lava destroys this tile on contact.
pub fn lava_death(tile: u16) -> bool {
    LAVA_DEATH.get(tile as usize).copied().unwrap_or(false)
}

/// Whether water destroys this tile on contact.
pub fn water_death(tile: u16) -> bool {
    WATER_DEATH.get(tile as usize).copied().unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Spot checks against tiles whose behaviour is unmistakable: a torch (4) goes dark in a
    /// flood but is untouched by lava; cobweb (51) burns and washes away either way; stone (1)
    /// shrugs off both.
    #[test]
    fn the_obvious_cases_match_the_game() {
        assert!(water_death(4), "a torch goes out in water");
        assert!(!lava_death(4), "but is untouched by lava");
        assert!(lava_death(51), "cobweb burns in lava");
        assert!(water_death(51), "and washes away in water");
        assert!(!lava_death(1), "stone is unaffected by lava");
        assert!(!water_death(1), "and by water");
    }

    /// Every tile lava destroys was reachable from at least one statement in the setup method;
    /// this is really a check that the table did not regenerate empty.
    #[test]
    fn the_tables_are_populated() {
        assert!(LAVA_DEATH.iter().filter(|&&b| b).count() > 100);
        assert!(WATER_DEATH.iter().filter(|&&b| b).count() > 5);
    }

    /// Most of `tileLavaDeath` is set tile by tile, but 435..=439 (the five team-block platforms)
    /// are set by a `for` loop instead: `for (int num2 = 435; num2 <= 439; num2++) { ...
    /// tileLavaDeath[num2] = true; ... }`. None of the five appears as a literal
    /// `tileLavaDeath[N] = true;` anywhere else in `Main.cs`, so this is entirely a check that the
    /// generator's loop expansion ran rather than skipped a range it could not read.
    #[test]
    fn the_loop_set_range_is_not_missed() {
        for tile in 435..=439u16 {
            assert!(lava_death(tile), "tile {tile} is set by the num2 loop");
        }
    }
}
