//! The names town NPCs are given, generated from the game's own lists.
//!
//! A town NPC carries a name of its own on top of its type, and the client asks the server for
//! it the moment the NPC comes into view. Left unanswered, every guide in the world is "Guide"
//! and no two of them can be told apart.
//!
//! The lists are the localisation file's, and which list a type draws from is
//! `NPC.getNewNPCNameInner`. Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do
//! not edit by hand.

/// `MerchantNames`, for NPC type 17.
const MERCHANTNAMES: [&str; 23] = [
    "Alfred",
    "Barney",
    "Calvin",
    "Edmund",
    "Edwin",
    "Eugene",
    "Frank",
    "Frederick",
    "Gilbert",
    "Gus",
    "Wilbur",
    "Seymour",
    "Louis",
    "Humphrey",
    "Harold",
    "Milton",
    "Mortimer",
    "Howard",
    "Walter",
    "Isaac",
    "Joseph",
    "Kristian",
    "Ralph",
];

/// `NurseNames`, for NPC type 18.
const NURSENAMES: [&str; 24] = [
    "Molly",
    "Amy",
    "Claire",
    "Emily",
    "Katie",
    "Madeline",
    "Katelyn",
    "Emma",
    "Abigail",
    "Carly",
    "Jenna",
    "Heather",
    "Katherine",
    "Caitlin",
    "Kaitlin",
    "Holly",
    "Kaitlyn",
    "Hannah",
    "Kathryn",
    "Lorraine",
    "Helen",
    "Kayla",
    "Lisa",
    "Allison",
];

/// `ArmsDealerNames`, for NPC type 19.
const ARMSDEALERNAMES: [&str; 24] = [
    "DeShawn",
    "DeAndre",
    "Marquis",
    "Darnell",
    "Terrell",
    "Malik",
    "Trevon",
    "Tyrone",
    "Willie",
    "Dominique",
    "Demetrius",
    "Reginald",
    "Jamal",
    "Maurice",
    "Jalen",
    "Darius",
    "Xavier",
    "Terrance",
    "Andre",
    "Dante",
    "Brimst",
    "Bronson",
    "Tony",
    "Darryl",
];

/// `DryadNames`, for NPC type 20.
const DRYADNAMES: [&str; 21] = [
    "Alalia",
    "Alura",
    "Ariella",
    "Caelia",
    "Calista",
    "Chryseis",
    "Emerenta",
    "Elysia",
    "Evvie",
    "Faye",
    "Felicitae",
    "Lunette",
    "Nata",
    "Nissa",
    "Tatiana",
    "Rosalva",
    "Shea",
    "Tania",
    "Isis",
    "Celestia",
    "Xylia",
];

/// `GuideNames`, for NPC type 22.
const GUIDENAMES: [&str; 36] = [
    "Joe", "Connor", "Tanner", "Wyatt", "Cody", "Levi", "Luke", "Jack", "Scott", "Logan", "Cole",
    "Asher", "Bradley", "Jacob", "Garrett", "Dylan", "Maxwell", "Steve", "Brett", "Andrew",
    "Harley", "Kyle", "Jake", "Ryan", "Jeffrey", "Seth", "Marty", "Brandon", "Zach", "Jeff",
    "Daniel", "Trent", "Kevin", "Brian", "Colin", "Jan",
];

/// `DemolitionistNames`, for NPC type 38.
const DEMOLITIONISTNAMES: [&str; 22] = [
    "Dolbere", "Bazdin", "Durim", "Tordak", "Garval", "Morthal", "Oten", "Dolgen", "Gimli",
    "Gimut", "Duerthen", "Beldin", "Jarut", "Ovbere", "Norkas", "Dolgrim", "Boften", "Norsun",
    "Dias", "Fikod", "Urist", "Darur",
];

/// `ClothierNames`, for NPC type 54.
const CLOTHIERNAMES: [&str; 25] = [
    "Sebastian",
    "Rupert",
    "Clive",
    "Nigel",
    "Mervyn",
    "Cedric",
    "Pip",
    "Cyril",
    "Fitz",
    "Lloyd",
    "Arthur",
    "Rodney",
    "Graham",
    "Edward",
    "Alfred",
    "Edmund",
    "Henry",
    "Herald",
    "Roland",
    "Lincoln",
    "Edgar",
    "Eustace",
    "Benjamin",
    "James",
    "Rodrick",
];

/// `GoblinTinkererNames`, for NPC type 107.
const GOBLINTINKERERNAMES: [&str; 25] = [
    "Grodax", "Sarx", "Xon", "Mrunok", "Nuxatk", "Tgerd", "Darz", "Smador", "Stazen", "Mobart",
    "Knogs", "Tkanus", "Negurk", "Nort", "Durnok", "Trogem", "Stezom", "Gnudar", "Ragz", "Fahd",
    "Xanos", "Arback", "Fjell", "Dalek", "Knub",
];

/// `WizardNames`, for NPC type 108.
const WIZARDNAMES: [&str; 22] = [
    "Dalamar",
    "Dulais",
    "Elric",
    "Arddun",
    "Maelor",
    "Leomund",
    "Hirael",
    "Gwentor",
    "Greum",
    "Gearroid",
    "Fizban",
    "Ningauble",
    "Seonag",
    "Sargon",
    "Merlyn",
    "Magius",
    "Berwyn",
    "Arwyn",
    "Alasdair",
    "Tagar",
    "Abram",
    "Xanadu",
];

/// `MechanicNames`, for NPC type 124.
const MECHANICNAMES: [&str; 24] = [
    "Shayna",
    "Korrie",
    "Ginger",
    "Brooke",
    "Jenny",
    "Autumn",
    "Nancy",
    "Ella",
    "Kayla",
    "Selah",
    "Sophia",
    "Marshanna",
    "Lauren",
    "Trisha",
    "Shirlena",
    "Sheena",
    "Ellen",
    "Amy",
    "Dawn",
    "Susana",
    "Meredith",
    "Selene",
    "Terra",
    "Sally",
];

/// `TruffleNames`, for NPC type 160.
const TRUFFLENAMES: [&str; 13] = [
    "Reishi",
    "Maitake",
    "Chanterelle",
    "Porcini",
    "Shimeji",
    "Amanita",
    "Muscaria",
    "Agaric",
    "Cremini",
    "Morel",
    "Enoki",
    "Shiitake",
    "Leinspores",
];

/// `SteampunkerNames`, for NPC type 178.
const STEAMPUNKERNAMES: [&str; 20] = [
    "Whitney", "Verity", "Ada", "Cornelia", "Lydia", "Leila", "Minerva", "Emeline", "Cynthia",
    "Fidelia", "Lilly", "Phoebe", "Zylphia", "Zelda", "Selina", "Hope", "Isabella", "Judith",
    "Savannah", "Vivian",
];

/// `DyeTraderNames`, for NPC type 207.
const DYETRADERNAMES: [&str; 16] = [
    "Abdosir",
    "Akbar",
    "Bodashtart",
    "Danel",
    "Hanno",
    "Hiram",
    "Kanmi",
    "Philosir",
    "Tabnit",
    "Yutpan",
    "Ahirom",
    "Batnoam",
    "Sikarbaal",
    "Hannibal",
    "Yehomilk",
    "Ahinadab",
];

/// `PartyGirlNames`, for NPC type 208.
const PARTYGIRLNAMES: [&str; 18] = [
    "Candy", "Isis", "Trixy", "Destiny", "Lexus", "Bambi", "Bailey", "Glitter", "Sparkle", "Paris",
    "Dazzle", "Fantasy", "Bunny", "Sugar", "Fantasia", "Star", "Cherry", "Amanda",
];

/// `CyborgNames`, for NPC type 209.
const CYBORGNAMES: [&str; 23] = [
    "Alpha", "Beta", "Delta", "Omega", "Gamma", "Theta", "Kappa", "Omicron", "Sigma", "Upsilon",
    "Phi", "Zeta", "Lambda", "Nu", "Ci", "Rho", "Fender", "T-3E0", "Niner-7", "A.N.D.Y.", "Syn-X",
    "Mu", "Raynbro",
];

/// `PainterNames`, for NPC type 227.
const PAINTERNAMES: [&str; 19] = [
    "Marco", "Guido", "Enzo", "Martino", "Mauro", "Lorenzo", "Ludo", "Luciano", "Carlo", "Bruno",
    "Mario", "Leonardo", "Raphael", "Luigi", "Luca", "Darren", "Esreadel", "Stefano", "Jim",
];

/// `WitchDoctorNames`, for NPC type 228.
const WITCHDOCTORNAMES: [&str; 10] = [
    "Abibe", "Jamundi", "U'wa", "Tairona", "Xirigua", "Zop'a", "Opuni", "Kogi-ghi", "Konah",
    "Gboto",
];

/// `PirateNames`, for NPC type 229.
const PIRATENAMES: [&str; 11] = [
    "David",
    "Red Beard",
    "Jack",
    "Black Beard",
    "Captain Morgan",
    "Wet Beard",
    "James T. Beard",
    "Gunpowder Garry",
    "Captain Stoney Dirt",
    "Jake",
    "Captain Bullywort",
];

/// `StylistNames`, for NPC type 353.
const STYLISTNAMES: [&str; 20] = [
    "Bri",
    "Brianne",
    "Flora",
    "Iris",
    "Scarlett",
    "Lola",
    "Hazel",
    "Stella",
    "Pearl",
    "Tallulah",
    "Ruby",
    "Esmeralda",
    "Kylie",
    "Kati",
    "Biah",
    "Meliyah",
    "Petra",
    "Rox",
    "Roxanne",
    "Annabel",
];

/// `TravelingMerchantNames`, for NPC type 368.
const TRAVELINGMERCHANTNAMES: [&str; 13] = [
    "Abraham",
    "Bohemas",
    "Eladon",
    "Aphraim",
    "Gallius",
    "Llewellyn",
    "Riley",
    "Rawleigh",
    "Shipton",
    "Romeo",
    "Aedan",
    "Mercer",
    "Willy",
];

/// `AnglerNames`, for NPC type 369.
const ANGLERNAMES: [&str; 21] = [
    "Bobby", "Sammy", "Jimmy", "Danny", "Timmy", "Simon", "Johnny", "Billy", "Matty", "Bart",
    "Phillip", "Spencer", "Nathan", "Grayson", "Miles", "Charles", "Adam", "Tyler", "Jey", "Ivan",
    "Izzy",
];

/// `TaxCollectorNames`, for NPC type 441.
const TAXCOLLECTORNAMES: [&str; 19] = [
    "McKinly",
    "Millard",
    "Fillmore",
    "Rutherford",
    "Chester",
    "Grover",
    "Cleveland",
    "Theodore",
    "Herbert",
    "Warren",
    "Lyndon",
    "Ronald",
    "Harrison",
    "Woodrow",
    "Tweed",
    "Blanton",
    "Dwyer",
    "Carroll",
    "Agnew",
];

/// `SkeletonMerchantNames`, for NPC type 453.
const SKELETONMERCHANTNAMES: [&str; 11] = [
    "Skellington",
    "Bones McGee",
    "Gloomy Mays",
    "Jack Sellington",
    "Billy Marrows",
    "Tom",
    "Rattles Magoo",
    "Mandible Calavera",
    "Mika",
    "No-Eyed Wiley",
    "Victor",
];

/// `BartenderNames`, for NPC type 550.
const BARTENDERNAMES: [&str; 16] = [
    "Ted",
    "Barkeep",
    "Jerry",
    "Bill",
    "Ernest",
    "William",
    "Dale",
    "Bruce",
    "Moe",
    "Javahawk",
    "Elandrian",
    "Driscan",
    "Iamisom",
    "Blacksmith",
    "Dani Moo",
    "Paddy",
];

/// `GolferNames`, for NPC type 588.
const GOLFERNAMES: [&str; 8] = [
    "Lion Pines",
    "Gunner McLovin",
    "Harry Madison",
    "Arnie Palmfrond",
    "Jake Nicklelisp",
    "William",
    "Billy Bones",
    "Jim Mulligan",
];

/// `BestiaryGirlNames`, for NPC type 633.
const BESTIARYGIRLNAMES: [&str; 21] = [
    "Maria",
    "MacKenzie",
    "Azaria",
    "Juanita",
    "Astra",
    "Hayley",
    "Becca",
    "Veronica",
    "Tia",
    "Robyn",
    "Arien",
    "Jane",
    "Bindi",
    "Dian",
    "Lori",
    "Mardy",
    "Mollie",
    "Lizzy",
    "Daphne",
    "Ellen",
    "Lilith",
];

/// `CatNames_Siamese`, for NPC type 637.
const CATNAMES_SIAMESE: [&str; 12] = [
    "Zen", "Callie", "Rainha", "Nust", "Bandit", "Goliath", "Valerie", "Socks", "Iris", "Sekhmet",
    "Cleo", "Sappho",
];

/// `DogNames_Labrador`, for NPC type 638.
const DOGNAMES_LABRADOR: [&str; 19] = [
    "Penny", "Pebbles", "Puppy", "Monroe", "Kittie", "Buddy", "Charlie", "Trulte", "Daisy",
    "Calvin", "Willow", "Arthur", "John", "Bitsy", "Mike", "Sparky", "Lucky", "Bubbles", "Tank",
];

/// `BunnyNames_White`, for NPC type 656.
const BUNNYNAMES_WHITE: [&str; 15] = [
    "Bunnicula",
    "Ben",
    "Roger",
    "Skippy",
    "Donnie",
    "Alice",
    "Presto",
    "Shion",
    "Lisette",
    "Lily",
    "Inaba",
    "Shirayuki",
    "Lilia",
    "Ears",
    "Jimothy",
];

/// `PrincessNames`, for NPC type 663.
const PRINCESSNAMES: [&str; 22] = [
    "Ai",
    "Hime",
    "Emilia",
    "Alice",
    "Belle",
    "Sophia",
    "Hikari",
    "Faye",
    "Christina",
    "Flora",
    "Liselotte",
    "Aria",
    "Yuuki",
    "Theresa",
    "Elitia",
    "Lucia",
    "Ariel",
    "Momo",
    "Charlotte",
    "Tiara",
    "Yorai",
    "Rosetta",
];

/// `SlimeNames_Blue`, for NPC type 670.
const SLIMENAMES_BLUE: [&str; 27] = [
    "Steve",
    "Seymour",
    "Simon",
    "Sheldon",
    "Sam",
    "Samson",
    "Sid",
    "Sigvard",
    "Stein",
    "Sean",
    "Samwise",
    "Snoot",
    "Swotty",
    "Stuart",
    "Stratford",
    "Saliva",
    "Sherman",
    "Stiltskin",
    "Shibboleet",
    "Sine",
    "Spock",
    "Smarty",
    "Sonic",
    "Sputnik",
    "Smoof",
    "Spetch",
    "Stevenson",
];

/// `SlimeNames_Green`, for NPC type 678.
const SLIMENAMES_GREEN: [&str; 25] = [
    "Sylvester",
    "Slimer",
    "Seth",
    "Shane",
    "Sully",
    "Scooter",
    "Scotty",
    "Spike",
    "Slachi",
    "Spinach",
    "Slick",
    "Slippy",
    "Speedy",
    "Slurm",
    "School",
    "Swag",
    "Swiggity Swooty",
    "Slackin",
    "Switch",
    "Sport",
    "Squash",
    "Skeeter",
    "Scutiger",
    "Softball",
    "Spazzy",
];

/// `SlimeNames_Old`, for NPC type 679.
const SLIMENAMES_OLD: [&str; 27] = [
    "Stooge",
    "Sir Slushington III",
    "Santiago",
    "Sebastian",
    "Samuel",
    "Seamus",
    "Sage",
    "Sinclair",
    "Stanford",
    "Septimus",
    "Stinky",
    "Spiffy",
    "Spruce",
    "Swanky",
    "Soggy",
    "Scooby",
    "Sigmund",
    "Smithers",
    "Sassafras",
    "Slumbledore",
    "Slimdalf",
    "Schartzmugel",
    "Scion",
    "Scrooge",
    "Stonks",
    "Swanson",
    "Spinkerton",
];

/// `SlimeNames_Purple`, for NPC type 680.
const SLIMENAMES_PURPLE: [&str; 25] = [
    "Stewy",
    "Sue",
    "Spencer",
    "Sidney",
    "Stefan",
    "Sonnie",
    "Sacco",
    "Sunset",
    "Snafu",
    "Stumble",
    "Spaghetti",
    "Shoggy",
    "Slimefors",
    "Shirley",
    "Sara",
    "Sharon",
    "Sludge",
    "Snuggle",
    "Sloppy",
    "Slimeora",
    "Sylph",
    "Spew",
    "Shemp",
    "Spanky",
    "Spork",
];

/// `SlimeNames_Rainbow`, for NPC type 681.
const SLIMENAMES_RAINBOW: [&str; 29] = [
    "Sylvia",
    "Skye",
    "Stephanie",
    "Sophia",
    "Shanna",
    "Serenity",
    "Shian",
    "Slimestar",
    "Shimmer",
    "Surai",
    "Stella",
    "Sasha",
    "Sweety",
    "Sparkle",
    "Sapphire",
    "Seraph",
    "Starry",
    "Sprinkes",
    "Sherbet",
    "Sugar",
    "Stardew",
    "Sheena",
    "Sveta",
    "Shampoo",
    "Sproink",
    "Secreta",
    "Sponsa",
    "Skyler",
    "Sorai",
];

/// `SlimeNames_Red`, for NPC type 682.
const SLIMENAMES_RED: [&str; 27] = [
    "Sparky",
    "Sourpuss",
    "Steamer",
    "Sizzle",
    "Shaka",
    "Slippery Sal",
    "Sirius",
    "Sven",
    "Sly",
    "Smeagol",
    "Scuff",
    "Shifty",
    "Sassy",
    "Scorpius",
    "Snotty",
    "Sleepy",
    "Stressball",
    "Slurpee",
    "Squeezo",
    "Sapo",
    "Snart",
    "Skiprat",
    "Sully",
    "Sharkey",
    "Scarface",
    "Slickfather",
    "Slimeballa",
];

/// `SlimeNames_Yellow`, for NPC type 683.
const SLIMENAMES_YELLOW: [&str; 27] = [
    "Sandy", "Saoirse", "Selena", "Sienna", "Samara", "Simone", "Siobhan", "Sabrina", "Sunny",
    "Savannah", "Spirit", "Sinead", "Saraid", "Siofra", "Sorcha", "Salem", "Soleil", "Salvo",
    "Sahara", "Shanoa", "Sybil", "Salome", "Summer", "Swirl", "Saga", "Silva", "Striga",
];

/// `SlimeNames_Copper`, for NPC type 684.
const SLIMENAMES_COPPER: [&str; 26] = [
    "Solomon",
    "Shortsword Saxon",
    "Steele",
    "Sigfried",
    "Sterling",
    "Seniore Slash",
    "Stabby",
    "Spunky",
    "Sharpie",
    "Scout",
    "Scrappy",
    "Slade",
    "Samsara",
    "Six-Swing Serge",
    "Scorch",
    "Sabin",
    "Stryker",
    "Slayer",
    "Slival",
    "Sting",
    "Sabaton",
    "Semper Serus",
    "Scrimshank",
    "Scavager",
    "Selmy",
    "Shortie",
];

/// Which list a type draws its name from, in type order.
const LISTS: [(u16, &[&str]); 38] = [
    (17, &MERCHANTNAMES),
    (18, &NURSENAMES),
    (19, &ARMSDEALERNAMES),
    (20, &DRYADNAMES),
    (22, &GUIDENAMES),
    (38, &DEMOLITIONISTNAMES),
    (54, &CLOTHIERNAMES),
    (107, &GOBLINTINKERERNAMES),
    (108, &WIZARDNAMES),
    (124, &MECHANICNAMES),
    (160, &TRUFFLENAMES),
    (178, &STEAMPUNKERNAMES),
    (207, &DYETRADERNAMES),
    (208, &PARTYGIRLNAMES),
    (209, &CYBORGNAMES),
    (227, &PAINTERNAMES),
    (228, &WITCHDOCTORNAMES),
    (229, &PIRATENAMES),
    (353, &STYLISTNAMES),
    (368, &TRAVELINGMERCHANTNAMES),
    (369, &ANGLERNAMES),
    (441, &TAXCOLLECTORNAMES),
    (453, &SKELETONMERCHANTNAMES),
    (550, &BARTENDERNAMES),
    (588, &GOLFERNAMES),
    (633, &BESTIARYGIRLNAMES),
    (637, &CATNAMES_SIAMESE),
    (638, &DOGNAMES_LABRADOR),
    (656, &BUNNYNAMES_WHITE),
    (663, &PRINCESSNAMES),
    (670, &SLIMENAMES_BLUE),
    (678, &SLIMENAMES_GREEN),
    (679, &SLIMENAMES_OLD),
    (680, &SLIMENAMES_PURPLE),
    (681, &SLIMENAMES_RAINBOW),
    (682, &SLIMENAMES_RED),
    (683, &SLIMENAMES_YELLOW),
    (684, &SLIMENAMES_COPPER),
];

/// `CatNames_Black`.
const CATNAMES_BLACK: [&str; 23] = [
    "Luna", "Figment", "Ember", "Damien", "Snowball", "Night", "Misu", "Magic", "Tonic", "Violet",
    "Jaspers", "Gargoyle", "Lilith", "Salem", "Rascal", "Bella", "Odin", "Jiji", "Morgan", "Arbus",
    "Max", "George", "Esper",
];

/// `CatNames_OrangeTabby`.
const CATNAMES_ORANGETABBY: [&str; 19] = [
    "Linkle",
    "Remy",
    "Lux",
    "Sunny",
    "Tigger",
    "Callie",
    "Sassy",
    "Bob",
    "Leo",
    "Tiger",
    "Caramel",
    "Tony",
    "Garfield",
    "Hobbes",
    "Charlie",
    "Rascal",
    "Critter",
    "Adol",
    "Lawnmower",
];

/// `CatNames_RussianBlue`.
const CATNAMES_RUSSIANBLUE: [&str; 17] = [
    "Alexi",
    "Ruby",
    "Bubbles",
    "Lexi",
    "Prissy",
    "Valery",
    "Lucy",
    "Pete",
    "Jocelyn",
    "Light",
    "Lily",
    "Starlight",
    "Cobalt",
    "Tilly",
    "Rion",
    "Momo",
    "Tarzan",
];

/// `CatNames_Silver`.
const CATNAMES_SILVER: [&str; 20] = [
    "Roo", "Blaze", "Rebus", "Polo", "Kelly", "Kiva", "Sooty", "By-Tor", "Merlin", "Trudy", "Nana",
    "Ange", "Kanako", "Freya", "Cloud", "Cutie", "Renne", "Miette", "Tula", "Kibby",
];

/// `CatNames_White`.
const CATNAMES_WHITE: [&str; 16] = [
    "Misty", "Storm", "Angel", "Vincent", "Mr. Cat", "Holly", "Sam", "Rory", "Ichibi", "Belle",
    "Yuki", "Ater", "Snowdrop", "Snowball", "Reah", "Gemma",
];

/// `DogNames_PitBull`.
const DOGNAMES_PITBULL: [&str; 14] = [
    "Max", "Dexter", "Chomps", "Bubba", "Sampson", "Spike", "Ginger", "Kona", "Keith", "Jazzy",
    "Rex", "Toshiro", "Buster", "Doug",
];

/// `DogNames_Beagle`.
const DOGNAMES_BEAGLE: [&str; 13] = [
    "Zelda",
    "Navi",
    "Ali",
    "Fred",
    "Roxie",
    "Milo",
    "Copper",
    "Darwin",
    "Lieselotte",
    "Wilma",
    "Odie",
    "Feena",
    "Pete",
];

/// `DogNames_Corgi`.
const DOGNAMES_CORGI: [&str; 16] = [
    "Bella",
    "Ellie",
    "Baxter",
    "Oliver",
    "Maya",
    "Titus",
    "Shino",
    "Elizabeth",
    "Victoria",
    "Yona",
    "Ammy",
    "Charles",
    "Estelle",
    "Astro",
    "Kilo",
    "AK",
];

/// `DogNames_Dalmation`.
const DOGNAMES_DALMATION: [&str; 13] = [
    "Spot", "Suzy", "Lucky", "Marshall", "Dotty", "Pongo", "Sapphire", "Splat", "Aurora", "Akane",
    "Firebug", "Polka", "Mizore",
];

/// `DogNames_Husky`.
const DOGNAMES_HUSKY: [&str; 16] = [
    "Rosalie", "Balto", "Miska", "Sky", "Sasha", "Zoey", "Toya", "Snowdog", "Kayla", "Hachiko",
    "Indiana", "Sven", "Bullet", "Comet", "Ingrid", "Dogi",
];

/// `BunnyNames_Angora`.
const BUNNYNAMES_ANGORA: [&str; 10] = [
    "Breadbuns",
    "Loaf",
    "Babs",
    "Big B",
    "Greg",
    "Fluffy",
    "Pom",
    "Muffin",
    "Maximus",
    "Donald",
];

/// `BunnyNames_Dutch`.
const BUNNYNAMES_DUTCH: [&str; 11] = [
    "Oreo", "Olaf", "Domino", "Oz", "Yin", "Yang", "Pow", "Kaguya", "Mono", "Panda", "Orin",
];

/// `BunnyNames_Flemish`.
const BUNNYNAMES_FLEMISH: [&str; 12] = [
    "Thumper",
    "Cinnabun",
    "Peter",
    "Hazel",
    "Loki",
    "Sunflower",
    "Toby",
    "Daisy",
    "Dusty",
    "Jazz",
    "Russell",
    "Honeycomb",
];

/// `BunnyNames_Lop`.
const BUNNYNAMES_LOP: [&str; 13] = [
    "Bunbun",
    "Lola",
    "Max",
    "Tyler",
    "Flops",
    "Flappie",
    "Caerbannog",
    "Mochi",
    "Dandy",
    "Puff",
    "Youp",
    "Boof",
    "Veidra",
];

/// `BunnyNames_Silver`.
const BUNNYNAMES_SILVER: [&str; 13] = [
    "Bugz",
    "Buster",
    "Silvine",
    "Bunstar",
    "Lord",
    "Bunnykins",
    "Crystal",
    "Chrome",
    "Vincent",
    "Zach",
    "Joshua",
    "Dustbunny",
    "Dusty",
];

/// The types that are not one creature but several, and the name list each breed uses.
///
/// A cat, a dog and a bunny each roll a breed on arrival; the breed decides how it looks and
/// which names it can have, which is why the two cannot be chosen independently.
const BREEDS: [(u16, &[&[&str]]); 3] = [
    (
        637,
        &[
            &CATNAMES_SIAMESE,
            &CATNAMES_BLACK,
            &CATNAMES_ORANGETABBY,
            &CATNAMES_RUSSIANBLUE,
            &CATNAMES_SILVER,
            &CATNAMES_WHITE,
        ],
    ),
    (
        638,
        &[
            &DOGNAMES_LABRADOR,
            &DOGNAMES_PITBULL,
            &DOGNAMES_BEAGLE,
            &DOGNAMES_CORGI,
            &DOGNAMES_DALMATION,
            &DOGNAMES_HUSKY,
        ],
    ),
    (
        656,
        &[
            &BUNNYNAMES_WHITE,
            &BUNNYNAMES_ANGORA,
            &BUNNYNAMES_DUTCH,
            &BUNNYNAMES_FLEMISH,
            &BUNNYNAMES_LOP,
            &BUNNYNAMES_SILVER,
        ],
    ),
];

/// The names a type may be given, or an empty slice if it is not the kind of NPC that has one.
///
/// Every NPC has a *type* name; this is the personal one on top of it, which only town NPCs,
/// town pets and town slimes carry.
pub fn names_for(npc_type: u16) -> &'static [&'static str] {
    match LISTS.binary_search_by_key(&npc_type, |&(ty, _)| ty) {
        Ok(at) => LISTS[at].1,
        Err(_) => &[],
    }
}

/// Whether a type is given a personal name at all.
pub fn has_given_name(npc_type: u16) -> bool {
    !names_for(npc_type).is_empty()
}

/// How many looks a type has to choose between when it arrives.
///
/// One for almost everything. Six for the cat, the dog and the bunny, whose breed is rolled on
/// arrival and then decides both the sprite and the name list.
pub fn variation_count(npc_type: u16) -> usize {
    match BREEDS.binary_search_by_key(&npc_type, |&(ty, _)| ty) {
        Ok(at) => BREEDS[at].1.len(),
        Err(_) => 1,
    }
}

/// The names a type may be given once its look has been chosen.
///
/// For everything but the three pets this is exactly [`names_for`]; for those it is the chosen
/// breed's own list, because a Siamese is never called Rex.
pub fn names_for_variation(npc_type: u16, variation: usize) -> &'static [&'static str] {
    if let Ok(at) = BREEDS.binary_search_by_key(&npc_type, |&(ty, _)| ty)
        && let Some(names) = BREEDS[at].1.get(variation)
    {
        return names;
    }
    names_for(npc_type)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The list is sorted, or the binary search above silently misses.
    #[test]
    fn the_lists_are_in_type_order() {
        assert!(
            LISTS.windows(2).all(|w| w[0].0 < w[1].0),
            "LISTS must be strictly ascending by type"
        );
    }

    /// The types the game names, and the ones it does not.
    #[test]
    fn the_named_types_are_the_town_ones() {
        assert!(has_given_name(22), "the guide has a name");
        assert!(has_given_name(17), "so does the merchant");
        assert!(has_given_name(637), "and the cat");
        assert!(!has_given_name(1), "a green slime does not");
        assert!(!has_given_name(0), "and neither does nothing");
    }

    /// Every list has something in it, and nothing in it is blank.
    #[test]
    fn every_list_holds_real_names() {
        for (ty, names) in LISTS {
            assert!(!names.is_empty(), "type {ty} has an empty name list");
            assert!(
                names.iter().all(|n| !n.trim().is_empty()),
                "type {ty} has a blank name"
            );
        }
    }

    /// The guide's list is the one the game ships, spot-checked against a name from it.
    #[test]
    fn the_guide_can_be_andrew() {
        assert!(names_for(22).contains(&"Andrew"));
    }

    /// The pets have six breeds each; everything else has one look.
    #[test]
    fn only_the_pets_have_breeds() {
        assert!(BREEDS.windows(2).all(|w| w[0].0 < w[1].0));
        for (ty, breeds) in BREEDS {
            assert_eq!(breeds.len(), 6, "type {ty} should have six breeds");
        }
        assert_eq!(variation_count(22), 1, "the guide has one look");
        assert_eq!(variation_count(637), 6, "the cat has six");
    }

    /// A breed's names are its own, not the type's first list.
    #[test]
    fn a_breed_draws_from_its_own_names() {
        let first = names_for_variation(637, 0);
        let last = names_for_variation(637, 5);
        assert!(!first.is_empty() && !last.is_empty());
        assert_ne!(first, last, "two breeds should not share a name list");
        assert_eq!(
            names_for_variation(637, 0),
            names_for(637),
            "the first breed is the type's default list"
        );
        assert_eq!(
            names_for_variation(637, 99),
            names_for(637),
            "an impossible breed falls back rather than panicking"
        );
    }
}
