//! The Travelling Merchant's stock, generated from the game's own chain.
//!
//! His inventory is not a list but a *chain of rolls*: one per candidate item, each overwriting
//! the last, so the final match wins. Rarer items sit at higher tiers and are rolled against
//! longer odds, and several only appear once the world has been through something.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.

/// What a world must already have been through for an item to be offered.
///
/// A bit set rather than an enum: a few items want two things at once.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Needs(pub u16);

impl Needs {
    pub const NONE: Self = Self(0);

    pub const ANY_MECH: u16 = 1 << 0;
    pub const DESTROYER: u16 = 1 << 1;
    pub const EYE: u16 = 1 << 2;
    pub const HARDMODE: u16 = 1 << 3;
    pub const ORB_SMASHED: u16 = 1 << 4;
    pub const PRIME: u16 = 1 << 5;
    pub const SKELETRON: u16 = 1 << 6;
    pub const TWINS: u16 = 1 << 7;

    pub fn met_by(self, world: Needs) -> bool {
        self.0 & !world.0 == 0
    }
}

/// One thing the merchant might be carrying.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Offer {
    pub item: u16,
    /// Which rarity tier's odds it is rolled against. Higher is rarer.
    pub tier: u8,
    /// What the world must have been through.
    pub needs: Needs,
    /// The `minimumRarity` floor below which the game stops considering this part of the chain.
    pub floor: u8,
}

/// The chain, in the order the game walks it. Later entries win.
pub const OFFERS: [Offer; 66] = [
    // `Chest.cs:980-987` — BlackCounterweight and YellowCounterweight each carry their own
    // leading `minimumRarity <= F &&` guard rather than sitting behind one of the
    // `if (minimumRarity > N) return;` checkpoints the rest of the chain uses, and both sit
    // ahead of item 1987 in source, so they are tried (and can be overwritten by it) first.
    Offer {
        item: 3309,
        tier: 4,
        needs: Needs(0),
        floor: 4,
    },
    Offer {
        item: 3314,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 1987,
        tier: 5,
        needs: Needs(0),
        floor: 0,
    },
    Offer {
        item: 2270,
        tier: 4,
        needs: Needs(Needs::HARDMODE),
        floor: 4,
    },
    Offer {
        item: 4760,
        tier: 4,
        needs: Needs(Needs::HARDMODE),
        floor: 4,
    },
    Offer {
        item: 2278,
        tier: 4,
        needs: Needs(0),
        floor: 4,
    },
    Offer {
        item: 2271,
        tier: 4,
        needs: Needs(0),
        floor: 4,
    },
    Offer {
        item: 2223,
        tier: 3,
        needs: Needs(Needs::HARDMODE | Needs::DESTROYER | Needs::TWINS | Needs::PRIME),
        floor: 3,
    },
    Offer {
        item: 2272,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 2276,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 2284,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 2285,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 2286,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 2287,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 4744,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 2296,
        tier: 3,
        needs: Needs(Needs::SKELETRON),
        floor: 3,
    },
    Offer {
        item: 3628,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 4091,
        tier: 3,
        needs: Needs(Needs::HARDMODE),
        floor: 3,
    },
    Offer {
        item: 4603,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 4604,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 5297,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 4605,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 4550,
        tier: 3,
        needs: Needs(0),
        floor: 3,
    },
    Offer {
        item: 5680,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 2268,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 2269,
        tier: 2,
        needs: Needs(Needs::ORB_SMASHED),
        floor: 2,
    },
    Offer {
        item: 1988,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 2275,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 2279,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 2277,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4555,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4321,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4323,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 5390,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4549,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4561,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4774,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 5136,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 5305,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4562,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4558,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4559,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4563,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4666,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4347,
        tier: 2,
        needs: Needs(0),
        floor: 2,
    },
    Offer {
        item: 4348,
        tier: 2,
        needs: Needs(Needs::HARDMODE),
        floor: 2,
    },
    Offer {
        item: 3262,
        tier: 2,
        needs: Needs(Needs::EYE),
        floor: 2,
    },
    Offer {
        item: 3284,
        tier: 2,
        needs: Needs(Needs::ANY_MECH),
        floor: 2,
    },
    Offer {
        item: 5600,
        tier: 1,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2267,
        tier: 1,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2214,
        tier: 1,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2215,
        tier: 1,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2216,
        tier: 1,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2217,
        tier: 1,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 3624,
        tier: 1,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2273,
        tier: 1,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2274,
        tier: 1,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2266,
        tier: 0,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2258,
        tier: 0,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2242,
        tier: 0,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 2260,
        tier: 0,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 3637,
        tier: 0,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 4420,
        tier: 0,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 3119,
        tier: 0,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 3118,
        tier: 0,
        needs: Needs(0),
        floor: 1,
    },
    Offer {
        item: 3099,
        tier: 0,
        needs: Needs(0),
        floor: 1,
    },
];

/// How many rarity tiers there are, and the odds each is rolled against.
///
/// `Chest.SetupTravelShop`'s starting array. The odds are one-in-N, so a tier-five item at 1200
/// turns up about once in every twelve hundred rolls of that step.
pub const TIER_ODDS: [i32; 6] = [1, 1, 1, 6, 300, 1200];

#[cfg(test)]
mod tests {
    use super::*;

    /// Every offer names a real item and a tier the odds table has.
    #[test]
    fn every_offer_is_well_formed() {
        for offer in OFFERS {
            assert!(offer.item > 0, "an offer with no item");
            assert!(
                (offer.tier as usize) < TIER_ODDS.len(),
                "item {} names tier {}, past the odds table",
                offer.item,
                offer.tier
            );
        }
    }

    /// A fresh world can be offered something, and a finished one can be offered more.
    #[test]
    fn progress_widens_the_stock() {
        let open = |world: Needs| OFFERS.iter().filter(|o| o.needs.met_by(world)).count();
        let fresh = open(Needs::NONE);
        let late = open(Needs(u16::MAX));
        assert!(fresh > 0, "a fresh world should have stock");
        assert!(late > fresh, "{late} late against {fresh} fresh");
    }

    /// BlackCounterweight (3309) and YellowCounterweight (3314) each carry their own leading
    /// `minimumRarity <= F &&` guard in `Chest.cs:980-987` instead of an enclosing
    /// `if (minimumRarity > N) return;` checkpoint, which the old anchored regex in
    /// `gen_travel_shop.py` could not see at all — both items were silently absent, with no
    /// other drop or craft source anywhere in this project, making them unobtainable.
    #[test]
    fn the_travelling_merchant_can_offer_both_counterweights() {
        assert!(OFFERS.iter().any(|o| o.item == 3309), "BlackCounterweight");
        assert!(OFFERS.iter().any(|o| o.item == 3314), "YellowCounterweight");
    }

    /// The condition test is a subset check, not equality: a world that has been through more
    /// than an item asks for still qualifies.
    #[test]
    fn extra_progress_does_not_disqualify() {
        let wants = Needs(Needs::HARDMODE);
        assert!(wants.met_by(Needs(Needs::HARDMODE)));
        assert!(wants.met_by(Needs(u16::MAX)));
        assert!(!wants.met_by(Needs::NONE));
    }
}
