//! `crates/terrustia-proto/src/angler.rs` — the Angler's daily fish quest.
//!
//! `Terraria/Main.cs`'s `anglerQuestItemNetIDs` is the list of fish, in roll order.
//! `AnglerQuestSwap` rerolls when a guard clause's condition holds, so each `if (num == N &&
//! <condition>) { flag2 = true; }` is read backwards into what the fish *requires*. The three
//! that want a boss down are gated by a separate combined clause. Everything from the
//! `isThereAWorldSurface` branch onward is world-seed-gated and this server does not offer those
//! seeds, so parsing stops there.
//!
//! Ported from `gen_angler.py`.

use std::collections::BTreeMap;
use std::path::Path;

use regex::Regex;

use crate::csharp::read_lossy;

#[derive(Clone, Copy, PartialEq, Eq)]
enum Evil {
    Crimson,
    Corruption,
}

#[derive(Default, Clone)]
struct Needs {
    hardmode: bool,
    evil: Option<Evil>,
    any_boss: bool,
}

pub fn generate(root: &Path) -> String {
    let main_cs = read_lossy(&root.join("Terraria/Main.cs"));

    // The list of fish, in the order the roll indexes it.
    let list_re = Regex::new(
        r"(?s)public static int\[\] anglerQuestItemNetIDs = new int\[(\d+)\]\s*\{(.*?)\};",
    )
    .unwrap();
    let m = list_re
        .captures(&main_cs)
        .expect("no anglerQuestItemNetIDs");
    let count: usize = m[1].parse().unwrap();
    let digit_re = Regex::new(r"\d+").unwrap();
    let fish: Vec<i64> = digit_re
        .find_iter(&m[2])
        .map(|x| x.as_str().parse().unwrap())
        .collect();
    assert_eq!(
        fish.len(),
        count,
        "expected {count} fish, parsed {}",
        fish.len()
    );

    // The guard clauses. Everything up to the `isThereAWorldSurface` branch, which only fires
    // under world seeds this server does not offer.
    let start = main_cs
        .find("public static void AnglerQuestSwap()")
        .expect("no AnglerQuestSwap");
    let stop = main_cs[start..]
        .find("if (!isThereAWorldSurface)")
        .expect("no isThereAWorldSurface")
        + start;
    let body = &main_cs[start..stop];

    // `if (num == N && <condition>) { flag2 = true; }` means "reroll when <condition>", i.e. the
    // fish is *unavailable* when the condition holds. Turn each into what the fish requires.
    let guard_re = Regex::new(r"if \(num == (\d+) && ([^)]*(?:\([^)]*\))?[^)]*)\)").unwrap();
    let not_crimson_re = Regex::new(r"!WorldGen\.crimson").unwrap();
    let crimson_re = Regex::new(r"WorldGen\.crimson").unwrap();

    let mut rules: BTreeMap<i64, Needs> = BTreeMap::new();
    for caps in guard_re.captures_iter(body) {
        let item: i64 = caps[1].parse().unwrap();
        let cond = &caps[2];
        let needs = rules.entry(item).or_default();
        if cond.contains("!hardMode") {
            needs.hardmode = true;
        }
        if not_crimson_re.is_match(cond) {
            needs.evil = Some(Evil::Crimson);
        } else if crimson_re.is_match(cond) {
            needs.evil = Some(Evil::Corruption);
        }
    }

    // The three that need a boss down are gated by a separate combined clause.
    let boss_re = Regex::new(r"if \(\(([^)]*)\) && !flag\)").unwrap();
    if let Some(boss_clause) = boss_re.captures(body) {
        let item_re = Regex::new(r"num == (\d+)").unwrap();
        for caps in item_re.captures_iter(&boss_clause[1]) {
            let item: i64 = caps[1].parse().unwrap();
            rules.entry(item).or_default().any_boss = true;
        }
    }
    assert!(
        rules.len() >= 10,
        "only {} gated fish parsed; AnglerQuestSwap's shape changed",
        rules.len()
    );

    let evil_of = |item: i64| -> &'static str {
        match rules.get(&item).and_then(|r| r.evil) {
            None => "Either",
            Some(Evil::Crimson) => "Crimson",
            Some(Evil::Corruption) => "Corruption",
        }
    };

    let mut chunks: Vec<String> = Vec::new();

    chunks.push(
        "//! The Angler's daily quest, generated from the game's own rules.\n\
         //!\n\
         //! One of forty-one fish is asked for each dawn, but not every fish is catchable in every world:\n\
         //! some only exist in hardmode, some only in one evil or the other, and three want a boss to have\n\
         //! fallen first. Asking for a fish that cannot be caught is not a small bug — it costs the player\n\
         //! a whole day of a reward track.\n\
         //!\n\
         //! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.\n\
         \n\
         /// Which evil a fish needs the world to have.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum Evil {\n    \
             /// Catchable either way.\n    \
             Either,\n    \
             Corruption,\n    \
             Crimson,\n\
         }\n\
         \n\
         /// One fish the Angler may ask for.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct Quest {\n    \
             /// The item the fish is.\n    \
             pub item: i32,\n    \
             /// Whether the world must be in hardmode.\n    \
             pub hardmode: bool,\n    \
             /// Which evil the world must have, if it matters.\n    \
             pub evil: Evil,\n    \
             /// Whether some boss must already have fallen.\n    \
             pub any_boss: bool,\n\
         }\n"
            .to_string(),
    );

    chunks.push(format!(
        "/// Every fish, in the order the daily roll indexes them.\npub const QUESTS: [Quest; {count}] = ["
    ));
    for &item in &fish {
        let r = rules.get(&item).cloned().unwrap_or_default();
        chunks.push(format!(
            "    Quest {{ item: {item}, hardmode: {}, evil: Evil::{}, any_boss: {} }},",
            r.hardmode,
            evil_of(item),
            r.any_boss
        ));
    }
    chunks.push("];".to_string());

    chunks.push(
        "\n/// Whether a fish can be asked for in a world in this state.\n\
         pub fn available(quest: &Quest, hardmode: bool, crimson: bool, any_boss_downed: bool) -> bool {\n    \
             if quest.hardmode && !hardmode {\n        \
                 return false;\n    \
             }\n    \
             match quest.evil {\n        \
                 Evil::Either => {}\n        \
                 Evil::Crimson if !crimson => return false,\n        \
                 Evil::Corruption if crimson => return false,\n        \
                 _ => {}\n    \
             }\n    \
             if quest.any_boss && !any_boss_downed {\n        \
                 return false;\n    \
             }\n    \
             true\n\
         }\n\
         \n\
         #[cfg(test)]\n\
         mod tests {\n    \
             use super::*;\n\
             \n    \
             /// A fresh world can still be given a quest, or the Angler is useless until hardmode.\n    \
             #[test]\n    \
             fn a_fresh_world_has_fish_to_ask_for() {\n        \
                 let open = QUESTS\n            \
                     .iter()\n            \
                     .filter(|q| available(q, false, false, false))\n            \
                     .count();\n        \
                 assert!(open > 10, \"only {open} fish available in a fresh world\");\n    \
             }\n\
             \n    \
             /// Hardmode opens more than pre-hardmode, not fewer.\n    \
             #[test]\n    \
             fn hardmode_opens_more_fish() {\n        \
                 let before = QUESTS\n            \
                     .iter()\n            \
                     .filter(|q| available(q, false, false, true))\n            \
                     .count();\n        \
                 let after = QUESTS\n            \
                     .iter()\n            \
                     .filter(|q| available(q, true, false, true))\n            \
                     .count();\n        \
                 assert!(after > before, \"{after} in hardmode against {before} before\");\n    \
             }\n\
             \n    \
             /// The two evils each lock some fish and open others, and neither locks everything.\n    \
             #[test]\n    \
             fn each_evil_has_its_own_fish() {\n        \
                 let corruption: Vec<i32> = QUESTS\n            \
                     .iter()\n            \
                     .filter(|q| available(q, true, false, true))\n            \
                     .map(|q| q.item)\n            \
                     .collect();\n        \
                 let crimson: Vec<i32> = QUESTS\n            \
                     .iter()\n            \
                     .filter(|q| available(q, true, true, true))\n            \
                     .map(|q| q.item)\n            \
                     .collect();\n        \
                 assert_ne!(corruption, crimson, \"the evils should differ\");\n        \
                 assert!(corruption.iter().any(|i| !crimson.contains(i)));\n        \
                 assert!(crimson.iter().any(|i| !corruption.contains(i)));\n    \
             }\n\
             \n    \
             /// Every fish is a real item id and none is listed twice.\n    \
             #[test]\n    \
             fn the_fish_are_distinct_items() {\n        \
                 let mut seen = std::collections::HashSet::new();\n        \
                 for quest in QUESTS {\n            \
                     assert!(quest.item > 0, \"a fish with no item\");\n            \
                     assert!(seen.insert(quest.item), \"item {} listed twice\", quest.item);\n        \
                 }\n    \
             }\n\
         }\n"
            .to_string(),
    );

    format!("{}\n", chunks.join("\n"))
}
