//! `crates/terrustia-proto/src/golf_physics.rs` - how a golf ball behaves on each kind of tile.
//!
//! Two embedded JSON resources rather than a C# set: `Materials.json` names fourteen materials and
//! their dampening figures, and `Tiles.json` maps each tile *name* to one of them. `TileMaterials`
//! resolves the names through `TileID.Search` at load, and this does the same by reading
//! `TileID.cs`'s own `public const ushort` list.
//!
//! Only the four figures the ball physics reads are emitted. `ClubImpactDampening` and
//! `ImpactDampeningResistanceEfficiency` are the player's swing and its accessory resistance, both
//! of which happen on the client that took the shot, so a server has no use for them.

use std::collections::BTreeMap;
use std::path::Path;

use crate::csharp::read_lossy;

const MODULE_DOC: &str = "\
//! How a golf ball behaves on each kind of tile, generated from the game's own material data.
//!
//! A golf ball is the one projectile in the roster whose whole behaviour is a physics simulation
//! rather than a routine, and *what it is rolling on* is half of that simulation: a ball skids
//! across ice, dies in sand, and barely bounces at all on a slime block. `aiStyle 149` reads
//! these three numbers on every contact.
//!
//! * **Direct** is what a head-on bounce keeps, along the surface normal.
//! * **Side** is what a glancing one keeps, along the surface. This is the number that decides how
//!   far a ball rolls, and it is where the materials differ most: 1.0 on ice against 0.2 on sand.
//! * **Through** is what passing *inside* a non-solid tile keeps each substep - cobwebs and
//!   plants, which slow a ball without stopping it.
//!
//! The two figures the game's own material data also carries are deliberately absent.
//! `ClubImpactDampening` scales the swing that launches a ball and
//! `ImpactDampeningResistanceEfficiency` scales an accessory that resists the dampening; both are
//! applied on the client that took the shot, and a server never takes one.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.";

/// One material's three numbers, in the order the emitted struct lists them.
#[derive(Clone, Copy, PartialEq)]
struct Golf {
    direct: f32,
    side: f32,
    through: f32,
}

fn read_json(root: &Path, name: &str) -> String {
    let text = read_lossy(&root.join(name));
    // These resources are written with a byte-order mark, which is not JSON.
    text.trim_start_matches('\u{feff}').to_string()
}

/// Pull `"Key": <number>` out of one object body. A hand-rolled reach into two well-formed files
/// the game ships, rather than a JSON dependency in a tool that has no other use for one.
fn number(body: &str, key: &str) -> Option<f32> {
    let at = body.find(&format!("\"{key}\""))?;
    let rest = &body[at + key.len() + 2..];
    let colon = rest.find(':')?;
    let value: String = rest[colon + 1..]
        .chars()
        .skip_while(|c| c.is_whitespace())
        .take_while(|c| c.is_ascii_digit() || *c == '.' || *c == '-' || *c == 'e' || *c == 'E')
        .collect();
    value.parse().ok()
}

/// Split a JSON object into its top-level `"name": { ... }` entries by brace matching.
fn objects(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let bytes: Vec<char> = text.chars().collect();
    let mut i = 0;
    let mut depth = 0;
    while i < bytes.len() {
        match bytes[i] {
            '{' => depth += 1,
            '}' => depth -= 1,
            '"' if depth == 1 => {
                let start = i + 1;
                let mut j = start;
                while j < bytes.len() && bytes[j] != '"' {
                    j += 1;
                }
                let name: String = bytes[start..j].iter().collect();
                // The value: skip to the colon, then take a balanced object if there is one.
                let mut k = j + 1;
                while k < bytes.len() && bytes[k] != ':' {
                    k += 1;
                }
                k += 1;
                while k < bytes.len() && bytes[k].is_whitespace() {
                    k += 1;
                }
                if k < bytes.len() && bytes[k] == '{' {
                    let body_start = k;
                    let mut inner = 0;
                    while k < bytes.len() {
                        match bytes[k] {
                            '{' => inner += 1,
                            '}' => {
                                inner -= 1;
                                if inner == 0 {
                                    break;
                                }
                            }
                            _ => {}
                        }
                        k += 1;
                    }
                    out.push((name, bytes[body_start..=k].iter().collect()));
                    i = k;
                } else {
                    // A plain `"name": "value"` pair, which is what `Tiles.json` is made of.
                    let start = k + 1;
                    let mut e = start;
                    while e < bytes.len() && bytes[e] != '"' {
                        e += 1;
                    }
                    out.push((name, bytes[start..e].iter().collect()));
                    i = e;
                }
            }
            _ => {}
        }
        i += 1;
    }
    out
}

/// `TileID.cs`'s own `public const ushort Name = N;` list, which is what `TileID.Search` is built
/// from.
fn tile_ids(root: &Path) -> BTreeMap<String, u16> {
    let cs = read_lossy(&root.join("Terraria.ID/TileID.cs"));
    let mut out = BTreeMap::new();
    for line in cs.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("public const ushort ") else {
            continue;
        };
        let Some((name, value)) = rest.split_once(" = ") else {
            continue;
        };
        if let Ok(id) = value.trim_end_matches(';').trim().parse::<u16>() {
            out.insert(name.trim().to_string(), id);
        }
    }
    out
}

pub fn generate(root: &Path) -> String {
    let materials_json = read_json(
        root,
        "Terraria.GameContent.Metadata.MaterialData.Materials.json",
    );
    let tiles_json = read_json(
        root,
        "Terraria.GameContent.Metadata.MaterialData.Tiles.json",
    );
    let ids = tile_ids(root);

    let mut materials: BTreeMap<String, Golf> = BTreeMap::new();
    for (name, body) in objects(&materials_json) {
        let Some(at) = body.find("\"GolfPhysics\"") else {
            continue;
        };
        let physics = &body[at..];
        let (Some(direct), Some(side), Some(through)) = (
            number(physics, "DirectImpactDampening"),
            number(physics, "SideImpactDampening"),
            number(physics, "PassThroughDampening"),
        ) else {
            continue;
        };
        materials.insert(
            name,
            Golf {
                direct,
                side,
                through,
            },
        );
    }
    let fallback = *materials
        .get("Default")
        .expect("the game's material data always carries a Default");

    // Tile id -> material, for every tile the game names one for.
    let mut per_tile: BTreeMap<u16, Golf> = BTreeMap::new();
    let mut unresolved = 0usize;
    for (tile_name, material_name) in objects(&tiles_json) {
        let (Some(id), Some(golf)) = (ids.get(&tile_name), materials.get(&material_name)) else {
            unresolved += 1;
            continue;
        };
        per_tile.insert(*id, *golf);
    }

    let highest = per_tile.keys().copied().max().unwrap_or(0);
    let mut rows = String::new();
    for id in 0..=highest {
        let g = per_tile.get(&id).copied().unwrap_or(fallback);
        rows.push_str(&format!(
            "    Golf {{ direct: {:?}, side: {:?}, through: {:?} }},\n",
            g.direct, g.side, g.through
        ));
    }

    format!(
        "{MODULE_DOC}\n\n\
/// What one kind of tile does to a ball that hits it.\n\
#[derive(Debug, Clone, Copy, PartialEq)]\n\
pub struct Golf {{\n\
    /// What a head-on bounce keeps, along the surface normal.\n\
    pub direct: f32,\n\
    /// What a glancing one keeps, along the surface. This is what decides how far a ball rolls.\n\
    pub side: f32,\n\
    /// What passing *inside* a non-solid tile keeps, each substep.\n\
    pub through: f32,\n\
}}\n\n\
/// The `\"Default\"` material, used for every tile the game's own data does not name.\n\
pub const DEFAULT: Golf = Golf {{ direct: {:?}, side: {:?}, through: {:?} }};\n\n\
/// {} tiles the game names a material for; {} names in its table are not tiles this build knows.\n\
const BY_TILE: [Golf; {}] = [\n{rows}];\n\n\
/// How a ball behaves on this tile.\n\
pub fn of(tile: u16) -> Golf {{\n\
    BY_TILE.get(tile as usize).copied().unwrap_or(DEFAULT)\n\
}}\n",
        fallback.direct,
        fallback.side,
        fallback.through,
        per_tile.len(),
        unresolved,
        highest as usize + 1,
    )
}
