//! `crates/terrustia-proto/src/hurt_tiles.rs` — which tiles hurt to stand in.
//!
//! The union of the game's `Suffocate`, `TouchDamageBleeding`, `TouchDamageHot` and non-zero
//! `TouchDamageImmediate` sets (exactly what `Collision.CanTileHurt` answers true for), minus the
//! two tiles that only hurt under seeds this server does not offer. Ported from `gen_hurt_tiles.py`.

use std::collections::BTreeSet;
use std::path::Path;

use crate::csharp::{bool_set, int_set, read_lossy, ushort_const};

const MODULE_DOC: &str = "\
//! Which tiles hurt to stand in, generated from the game's own sets.
//!
//! This decides where a teleport may put you. A magic conch that drops you into spikes, or a
//! demon conch that lands you in lava, is worse than one that does nothing at all — so the
//! landing-spot search consults this before it accepts a candidate.
//!
//! Two tiles the game can make dangerous are deliberately absent. `Collision.CanTileHurt` gates
//! tile 230 behind the Ravaged seed and tile 80 behind Don't Starve; this server offers neither,
//! so on it they are ordinary blocks.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.";

const HURTS_DOC: &str = "\
/// Whether standing in this tile costs you something.
///
/// The union of `TouchDamageBleeding`, `Suffocate`, `TouchDamageHot` and everything with a
/// non-zero `TouchDamageImmediate` — which is exactly what `Collision.CanTileHurt` answers true
/// for, minus the two seed-gated ones.";

const SUFFOCATES_DOC: &str = "\
/// The tiles that hurt by being *inside* them rather than by being touched.
///
/// The distinction matters to the collision box: the game shrinks the test by two pixels on each
/// side for these, so brushing past sand does not suffocate you.";

const TAIL: &str = r#"/// Whether standing in this tile costs you something.
pub fn hurts(tile: u16) -> bool {
    HURTS.get(tile as usize).copied().unwrap_or(false)
}

/// Whether this tile hurts by enclosing rather than by touch.
pub fn suffocates(tile: u16) -> bool {
    SUFFOCATES.get(tile as usize).copied().unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Spot checks against tiles whose behaviour is unmistakable.
    #[test]
    fn the_obvious_hazards_are_hazards() {
        assert!(hurts(48), "spikes");
        assert!(hurts(232), "wooden spikes");
        assert!(hurts(37), "meteorite burns");
        assert!(hurts(58), "hellstone burns");
        assert!(hurts(53) || suffocates(53), "sand suffocates");
        assert!(!hurts(1), "stone is just stone");
        assert!(!hurts(0), "and so is dirt");
    }

    /// The two seed-gated tiles are ordinary here, because those seeds are not offered.
    #[test]
    fn the_seed_only_hazards_are_harmless() {
        assert!(!hurts(230), "tile 230 needs Ravaged");
        assert!(!hurts(80), "cactus needs Don't Starve");
    }

    /// Suffocating tiles are a subset of hurting ones, or the box-shrink rule applies to nothing.
    #[test]
    fn suffocating_tiles_also_hurt() {
        for tile in 0..super::HURTS.len() as u16 {
            if suffocates(tile) {
                assert!(hurts(tile), "tile {tile} suffocates but does not hurt");
            }
        }
    }
}"#;

/// One `pub const NAME: [bool; COUNT]` table: `true` for each member id, `false` elsewhere.
/// `cargo fmt` reflows the row afterward, so this just emits the values in order.
fn bool_table(name: &str, members: &BTreeSet<u32>, count: usize, doc: &str) -> String {
    let vals: Vec<&str> = (0..count as u32)
        .map(|i| {
            if members.contains(&i) {
                "true,"
            } else {
                "false,"
            }
        })
        .collect();
    format!(
        "{doc}\npub const {name}: [bool; {count}] = [\n    {}\n];",
        vals.join(" ")
    )
}

pub fn generate(root: &Path) -> String {
    let tile_cs = read_lossy(&root.join("Terraria.ID/TileID.cs"));
    let count = ushort_const(&tile_cs, "Count");

    let suffocate: BTreeSet<u32> = bool_set(&tile_cs, "Suffocate").into_iter().collect();
    let bleeding = bool_set(&tile_cs, "TouchDamageBleeding");
    let hot = bool_set(&tile_cs, "TouchDamageHot");
    let (_default_immediate, immediate) = int_set(&tile_cs, "TouchDamageImmediate");

    let mut hurts: BTreeSet<u32> = BTreeSet::new();
    hurts.extend(suffocate.iter().copied());
    hurts.extend(bleeding);
    hurts.extend(hot);
    hurts.extend(immediate.keys().copied());
    // Ravaged gates tile 230, Don't Starve gates 80 — neither seed is offered here.
    for gated in [230, 80] {
        hurts.remove(&gated);
    }

    let hurts_table = bool_table("HURTS", &hurts, count, HURTS_DOC);
    let suffocates_table = bool_table("SUFFOCATES", &suffocate, count, SUFFOCATES_DOC);
    format!("{MODULE_DOC}\n\n{hurts_table}\n\n{suffocates_table}\n\n{TAIL}\n")
}
