//! `crates/terrustia-proto/src/recipes.rs` — what each crafted item is made of, for shimmer
//! decrafting. Ported from `gen_recipes.py`.
//!
//! Reads `Recipe.SetupRecipes`, one recipe per `createItem.SetDefaults(N) … AddRecipe()`, keeps the
//! last decraftable recipe for each result (`UpdateWhichItemsAreCrafted`), and packs the
//! ingredients end to end.
//!
//! D1: `SetupRecipes` also builds around 570 more recipes inside `for` loops and a handful of small
//! per-set helper functions (`AddCritterStatueRecipe`, `AddStandardFurnitureSetRecipes`), none of
//! which the literal `createItem.SetDefaults(N)` parse above can see: their argument is a loop
//! variable, an array slot, or a helper parameter, never a source-text digit. [`loop_built_recipes`]
//! unrolls each of these families by hand against the cited `Recipe.cs` lines and its doc comment
//! is the inventory of what they are and why each is faithful.

use std::collections::BTreeMap;
use std::ops::Range;
use std::path::Path;

use regex::Regex;

use crate::csharp::{int_set, read_lossy, resolve_locals};

const HEADER: &str = "\
//! What crafted things are made of, generated from the game's recipes.
//!
//! This is **not** a crafting system and does not try to be. It knows nothing about crafting
//! stations, conditions, or whether a player can reach a bench. It answers exactly one question:
//! *if this item were broken apart, what would come out?*
//!
//! That is what shimmer needs. An item with no transmutation of its own is decrafted — broken
//! back into its recipe's ingredients — and without this table it simply sat in the pool.
//!
//! Two rules from the game are baked in rather than applied at runtime:
//!
//! * Where several recipes make the same item, the **last** one wins, which is what
//!   `UpdateWhichItemsAreCrafted` does by overwriting as it goes.
//! * Recipes marked `notDecraftable` are excluded outright, so nothing here can be broken apart
//!   that the game would refuse to break.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.
//!
//! Around 570 of the recipes below never appear as a literal `SetDefaults(N)` in `Recipe.cs`:
//! `SetupRecipes` builds them inside `for` loops and small per-set helper functions instead. Their
//! provenance is in `terrustia-codegen/src/recipes.rs`'s `loop_built_recipes`, cited by `Recipe.cs`
//! line range there rather than repeated here 570 times.

/// One ingredient and how many of it the recipe wanted.
pub type Ingredient = (u16, u16);

/// A recipe, as decrafting sees it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Recipe {
    /// What it makes.
    pub result: u16,
    /// How many it makes at once. An item only decrafts if there are at least this many.
    pub makes: u16,
    /// Where this recipe's ingredients start in [`INGREDIENTS`], and how many there are.
    pub first: u16,
    pub count: u8,
    /// Alchemy recipes give back less: each ingredient has a one-in-three chance of being lost,
    /// which is the game's way of stopping potions being a free material duplicator.
    pub alchemy: bool,
}";

const TAIL: &str = r#"fn look_up(table: &[(u16, u16)], key: u16) -> Option<u16> {
    table
        .binary_search_by_key(&key, |&(k, _)| k)
        .ok()
        .map(|at| table[at].1)
}

/// The recipe an item would be broken apart by, if any.
///
/// `ShimmerTransforms.GetDecraftingRecipeIndex`: a world's evil decides between two variants
/// where both exist, so the same item decrafts differently in a crimson world.
pub fn decraft_recipe(item: u16, crimson: bool) -> Option<&'static Recipe> {
    let base = look_up(&CRAFTED_BY, item)?;
    let chosen = if crimson {
        look_up(&CRAFTED_BY_CRIMSON, item).unwrap_or(base)
    } else {
        look_up(&CRAFTED_BY_CORRUPTION, item).unwrap_or(base)
    };
    RECIPES.get(chosen as usize)
}

impl Recipe {
    /// What this recipe wanted.
    pub fn ingredients(&self) -> &'static [Ingredient] {
        let from = self.first as usize;
        &INGREDIENTS[from..from + self.count as usize]
    }
}

/// Whether a recipe is one the world has not earned yet.
///
/// Two gates: some recipes cannot be decrafted until Skeletron is down, others until the Golem
/// is. `ShimmerTransforms.IsRecipeIndexDecraftLocked` (`ShimmerTransforms.cs:47-61`) checks
/// `RecipeSets.PostSkeletron` and `RecipeSets.PostGolem`, and those two sets are not tables at
/// all: `UpdateRecipeSets` (`:81-85`) fills them at load time from the recipes themselves,
///
/// ```text
/// RecipeSets.PostSkeletron = Utils.MapArray(Main.recipe, (Recipe r) => r.ContainsIngredient(154));
/// RecipeSets.PostGolem    = Utils.MapArray(Main.recipe, (Recipe r) => r.ContainsIngredient(1101));
/// ```
///
/// so the rule is simply "made of Bone" and "made of Lihzahrd Brick". Reading them at their bare
/// `bool[]` declarations and concluding they were empty is what left this returning `false` for
/// every recipe, which let a world decraft the 97 Bone recipes before Skeletron and the 21
/// Lihzahrd ones before the Golem. `ContainsIngredient` is an exact item-id test, which is what
/// [`Recipe::ingredients`] holds.
pub fn decraft_locked(recipe: &Recipe, downed_skeletron: bool, downed_golem: bool) -> bool {
    let wants = |item: u16| recipe.ingredients().iter().any(|&(i, _)| i == item);
    (!downed_skeletron && wants(154)) || (!downed_golem && wants(1101))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The lookups are sorted, or the binary searches silently miss.
    #[test]
    fn the_lookups_are_sorted() {
        for (name, table) in [
            ("CRAFTED_BY", &CRAFTED_BY[..]),
            ("CRAFTED_BY_CRIMSON", &CRAFTED_BY_CRIMSON[..]),
            ("CRAFTED_BY_CORRUPTION", &CRAFTED_BY_CORRUPTION[..]),
        ] {
            assert!(
                table.windows(2).all(|w| w[0].0 < w[1].0),
                "{name} must be strictly ascending"
            );
        }
    }

    /// Every recipe's ingredient span lies inside the packed array and holds real items.
    #[test]
    fn every_recipe_points_at_real_ingredients() {
        for recipe in RECIPES {
            let end = recipe.first as usize + recipe.count as usize;
            assert!(
                end <= INGREDIENTS.len(),
                "item {} runs past the ingredient table",
                recipe.result
            );
            assert!(recipe.count > 0, "item {} has no ingredients", recipe.result);
            assert!(recipe.makes > 0, "item {} makes nothing", recipe.result);
            for &(item, stack) in recipe.ingredients() {
                assert!(item > 0, "recipe for {} wants item zero", recipe.result);
                assert!(stack > 0, "recipe for {} wants none of {item}", recipe.result);
            }
        }
    }

    /// Every index in the lookups names a recipe that exists.
    #[test]
    fn every_lookup_names_a_recipe() {
        for table in [&CRAFTED_BY[..], &CRAFTED_BY_CRIMSON[..], &CRAFTED_BY_CORRUPTION[..]] {
            for &(item, at) in table {
                assert!(
                    (at as usize) < RECIPES.len(),
                    "item {item} names recipe {at}, past the end"
                );
            }
        }
    }

    /// A well-known one, end to end.
    #[test]
    fn a_torch_decrafts_into_what_it_was_made_of() {
        let torch = decraft_recipe(8, false).expect("a torch is crafted");
        assert_eq!(torch.result, 8);
        assert_eq!(torch.makes, 3, "three torches at a time");
        let wants: Vec<u16> = torch.ingredients().iter().map(|&(i, _)| i).collect();
        assert!(wants.contains(&23), "a torch wants gel");
    }

    /// Something that is not crafted decrafts into nothing.
    ///
    /// Note that a great deal *is* crafted, including things that feel primitive — an Iron
    /// Pickaxe is ten bars and three wood. So this checks the shape of the answer rather than
    /// guessing at which items are raw.
    #[test]
    fn raw_materials_do_not_decraft() {
        assert!(decraft_recipe(0, false).is_none(), "nothing at all");
        let uncraftable = (1u16..2000)
            .filter(|&i| decraft_recipe(i, false).is_none())
            .count();
        assert!(
            uncraftable > 100,
            "only {uncraftable} of the first two thousand items are uncrafted, which is too few"
        );
    }

    /// The two evils can disagree about what an item is made of.
    #[test]
    fn the_evils_can_differ() {
        let differing = (0u16..u16::MAX).filter(|&i| {
            match (decraft_recipe(i, false), decraft_recipe(i, true)) {
                (Some(a), Some(b)) => a != b,
                _ => false,
            }
        });
        assert!(
            differing.take(1).count() > 0 || CRAFTED_BY_CRIMSON.is_empty(),
            "if any recipe is evil-specific, some item should decraft differently"
        );
    }

    /// D1: a fake chest still decrafts into what it was made of.
    ///
    /// `Recipe.cs` 6524-6532: the `for (int i = 3665; i <= 3704; i++)` texture-copy loop. Item
    /// 3665 (`Fake_Chest`) copies the Regular Chest's texture, so it wants Regular Chest (48) and
    /// ten Wire (530): `ItemID.Sets.TextureCopyLoad[3665] == 48` (`Terraria.ID/ItemID.cs` 1096).
    #[test]
    fn a_fake_chest_decrafts_into_its_wire_and_copied_chest() {
        let fake_chest = decraft_recipe(3665, false).expect("a fake chest is crafted");
        assert_eq!(fake_chest.makes, 1);
        let wants: Vec<(u16, u16)> = fake_chest.ingredients().to_vec();
        assert_eq!(wants, vec![(48, 1), (530, 10)]);
    }

    /// D1: a critter statue decrafts into its stone and its critter.
    ///
    /// `Recipe.cs` 9630 (`AddCritterStatueRecipe(444, 261)`, helper at 16702-16718): the Fish
    /// Statue (444) wants fifty Stone Block (3) and five Goldfish (261).
    #[test]
    fn a_critter_statue_decrafts_into_stone_and_its_critter() {
        let statue = decraft_recipe(444, false).expect("a fish statue is crafted");
        assert_eq!(statue.makes, 1);
        let wants: Vec<(u16, u16)> = statue.ingredients().to_vec();
        assert_eq!(wants, vec![(3, 50), (261, 5)]);
    }

    /// D1: `AddCritterStatueRecipe`'s `RecipeGroup` branch resolves to the group's first member.
    ///
    /// `Recipe.cs` 9632 (`AddCritterStatueRecipe(3651, 0, RecipeGroups.Squirrels)`): the Squirrel
    /// statue wants five of item 2018, the Squirrel: `RecipeGroups.Squirrels`'s first member
    /// (`Recipe.cs` 501, `SetupRecipeGroups`), not the literal `0` the call passes.
    #[test]
    fn a_group_based_critter_statue_resolves_the_groups_first_member() {
        let statue = decraft_recipe(3651, false).expect("a squirrel statue is crafted");
        let wants: Vec<(u16, u16)> = statue.ingredients().to_vec();
        assert_eq!(wants, vec![(3, 50), (2018, 5)]);
    }

    /// D1: a gemspark wall decrafts back into the ordinary one-block-to-four-walls ratio.
    ///
    /// `Recipe.cs` 3188-3195: the first of seven `num2/num3/num4` gemspark-wall blocks. Item 2679
    /// (`AmethystGemsparkWall`, `num3`) is four walls made from one Amethyst Gemspark Block (1970,
    /// `num2`).
    #[test]
    fn a_gemspark_wall_makes_four_from_one_block() {
        let wall = decraft_recipe(2679, false).expect("a gemspark wall is crafted");
        assert_eq!(wall.makes, 4, "the loop's createItem.stack = 4, the usual block-to-wall ratio");
        let wants: Vec<(u16, u16)> = wall.ingredients().to_vec();
        assert_eq!(wants, vec![(1970, 1)]);
    }

    /// D1: `StrungCounterweight`'s six-iteration loop was a real bug in the pre-D1 table, not just
    /// a gap: `Recipe.cs` 9456-9463 sets a literal `createItem` (5547) but a loop-variable second
    /// ingredient, so the generic parse used to keep a real but truncated recipe: White String
    /// (3306) alone, with the second ingredient silently dropped. The last iteration (l = 3314)
    /// wants White String and item 3314 both.
    #[test]
    fn a_strung_counterweight_wants_both_strings_not_just_one() {
        let counterweight = decraft_recipe(5547, false).expect("a counterweight is crafted");
        let wants: Vec<(u16, u16)> = counterweight.ingredients().to_vec();
        assert_eq!(
            wants,
            vec![(3306, 1), (3314, 1)],
            "the pre-D1 table only recovered the first ingredient here"
        );
    }

    /// D1: `AddStandardFurnitureSetRecipes` called twice from `AddPineFurniture` (`Recipe.cs`
    /// 16520-16524) with the same nineteen result items but two different primary materials (1872,
    /// then 5930): the second call's recipes must win, the same last-recipe-wins rule as anywhere
    /// else in `SetupRecipes`.
    #[test]
    fn pine_furnitures_second_call_wins_over_its_first() {
        let bathtub = decraft_recipe(5840, false).expect("a pine bathtub is crafted");
        let wants: Vec<(u16, u16)> = bathtub.ingredients().to_vec();
        assert_eq!(
            wants,
            vec![(5930, 14)],
            "the second AddStandardFurnitureSetRecipes(5930, ...) call must win over the first \
             AddStandardFurnitureSetRecipes(1872, ...) one"
        );
    }

    /// D1 in one number: a future extractor regression that silently stops seeing the loop-built
    /// families should be loud, not a quiet shrink nobody notices.
    #[test]
    fn the_decraft_table_includes_the_loop_built_families() {
        assert_eq!(
            CRAFTED_BY.len(),
            3090,
            "expected 2536 pre-D1 craftable items, 547 loop-built ones, and the 7 that only \
             appeared once `SetupRecipes`' integer locals were resolved"
        );
    }

    /// The two progression gates on decrafting are real, not empty sets.
    ///
    /// `ShimmerTransforms.UpdateRecipeSets` builds them from the ingredients themselves, so
    /// anything made of Bone waits for Skeletron and anything made of Lihzahrd Brick waits for the
    /// Golem. This used to return `false` for everything.
    #[test]
    fn bone_and_lihzahrd_recipes_wait_for_their_boss() {
        let count = |pred: fn(&Recipe) -> bool| RECIPES.iter().filter(|r| pred(r)).count();
        assert_eq!(count(|r| decraft_locked(r, false, true)), 96, "Bone recipes");
        assert_eq!(
            count(|r| decraft_locked(r, true, false)),
            21,
            "Lihzahrd Brick recipes"
        );
        // A finished world is gated on nothing.
        assert_eq!(count(|r| decraft_locked(r, true, true)), 0);
        let bone = RECIPES
            .iter()
            .find(|r| r.ingredients().iter().any(|&(i, _)| i == 154))
            .expect("something is made of Bone");
        assert!(decraft_locked(bone, false, true));
        assert!(!decraft_locked(bone, true, true));
    }

    /// The three integer locals `SetupRecipes` hoists its materials into, one recipe each.
    ///
    /// Every one of these read as garbage while `ingredients_of` could only see digits: the
    /// Lesion Bed was "one of item 7", the Crystal Bathtub had no Crystal Block at all, and every
    /// sofa gave back 1 + 1 rather than 5 + 2.
    #[test]
    fn hoisted_materials_survive_extraction() {
        let of = |item: u16| decraft_recipe(item, false).expect("crafted").ingredients();
        assert_eq!(of(3959), &[(3955, 15), (225, 5)], "Lesion Bed");
        assert_eq!(of(3918), &[(3234, 12), (225, 2)], "Crystal Bathtub");
        assert_eq!(of(2397), &[(9, 5), (225, 2)], "a sofa");
    }

    /// Potions are alchemy recipes, which is what makes decrafting them lossy.
    ///
    /// `Recipe.AddRecipe` sets the flag from `requiredTile == 13`, text that never appears in
    /// `SetupRecipes`, so every row used to say `false` and shimmer handed back 100% of a potion's
    /// ingredients.
    #[test]
    fn potions_are_alchemy() {
        let alchemy = RECIPES.iter().filter(|r| r.alchemy).count();
        assert_eq!(alchemy, 52, "the alchemy-table recipes that survive last-wins");
        assert!(
            decraft_recipe(288, false).expect("Shine Potion is crafted").alchemy,
            "a potion brewed at the alchemy table"
        );
    }
}"#;

/// Substitute `SetupRecipes`' integer locals and its ingredient arrays into the lines the recipe
/// parser reads, so an ingredient hoisted out of the literal text is not lost.
///
/// Three declarations in `Recipe.cs` between them account for 62 wrong or missing recipes, every
/// one of them because [`ingredients_of`] can only see digits:
///
/// * `int num = 5; int stack = 2;` (`:608-609`), used by the 26 sofa-style recipes as
///   `requiredItem[N].stack = num`. Read as no stack at all, they each gave back 1+1 rather than
///   5+2, so decrafting a sofa was a net loss of four wood.
/// * `int type = 3234;` (`:6280`), the Crystal Block that 18 crystal furniture recipes take as
///   `requiredItem[0].SetDefaults(type)`. Invisible, so six of those recipes came out with *no*
///   ingredients at all (dropped entirely) and twelve came out missing their main material.
/// * `int num = 3955;` (`:15721`), the Lesion Block behind 18 Lesion furniture recipes, half of
///   them passed through an `int[] objN = new int[K] { 0, ... }; objN[0] = num;` array. Reading
///   `obj7` for its trailing digit turned the Lesion Bed's (3955, 15) + (225, 5) into a single
///   ingredient 7.
///
/// The array form is expanded here too: `recipe7.SetIngredients(obj7)` becomes
/// `recipe7.SetIngredients(3955, 15, 225, 5)`, which the existing `SetIngredients` parse then
/// reads without further help.
///
/// Substitution is deliberately confined to the statement forms the recipe parser looks at
/// (`currentRecipe.…`, `<recipe>.SetIngredients(…)`, an array element assignment). Applying it to
/// the whole body would rewrite `SetupRecipes`' own loop and helper text, which
/// [`loop_built_recipes`] matches against verbatim.
fn resolve_recipe_locals(body: &str) -> String {
    let int_decl = Regex::new(r"^int (\w+) = (\d+);$").unwrap();
    let arr_decl = Regex::new(r"^int\[\] (\w+) = new int\[\d*\] \{([^}]*)\};$").unwrap();
    let arr_store = Regex::new(r"^(\w+)\[(\d+)\] = (-?\d+);$").unwrap();
    let arr_use = Regex::new(r"^(\w+\.SetIngredients\()(\w+)(\);)$").unwrap();
    let interesting =
        Regex::new(r"^(?:currentRecipe\.|\w+\.SetIngredients\(|\w+\[\d+\] = )").unwrap();
    let cast_re = Regex::new(r"\(int\)\(\(float\)(\d+) \* ([\d.]+)f\)").unwrap();
    let num_re = Regex::new(r"-?\d+").unwrap();

    let mut ints: BTreeMap<String, String> = BTreeMap::new();
    let mut arrays: BTreeMap<String, Vec<i64>> = BTreeMap::new();
    let mut out = String::with_capacity(body.len());
    for raw in body.lines() {
        let trimmed = raw.trim();
        if let Some(caps) = int_decl.captures(trimmed) {
            ints.insert(caps[1].to_string(), caps[2].to_string());
            out.push_str(raw);
            out.push('\n');
            continue;
        }
        if let Some(caps) = arr_decl.captures(trimmed) {
            arrays.insert(
                caps[1].to_string(),
                num_re
                    .find_iter(&caps[2])
                    .map(|m| m.as_str().parse().unwrap())
                    .collect(),
            );
            out.push_str(raw);
            out.push('\n');
            continue;
        }
        let line = if interesting.is_match(trimmed) {
            resolve_locals(trimmed, &ints)
        } else {
            trimmed.to_string()
        };
        // `obj7[0] = 3955;` patches the placeholder the declaration left.
        if let Some(caps) = arr_store.captures(&line)
            && let Some(values) = arrays.get_mut(&caps[1])
            && let Ok(at) = caps[2].parse::<usize>()
            && at < values.len()
        {
            values[at] = caps[3].parse().unwrap();
        }
        // `recipe7.SetIngredients(obj7);` becomes the numbers themselves.
        let line = match arr_use.captures(&line) {
            Some(caps) => match arrays.get(&caps[2]) {
                Some(values) => format!(
                    "{}{}{}",
                    &caps[1],
                    values
                        .iter()
                        .map(i64::to_string)
                        .collect::<Vec<_>>()
                        .join(", "),
                    &caps[3]
                ),
                None => line,
            },
            None => line,
        };
        // `stack = (int)((float)5 * 2.5f);` is the one arithmetic stack in `SetupRecipes`
        // (`Recipe.cs:6374`, the Crystal Bathtub's twelve Crystal Blocks). Folded to its C# value:
        // a `(int)` cast of a positive float truncates.
        let line = cast_re
            .replace_all(&line, |caps: &regex::Captures| {
                let n: f64 = caps[1].parse().unwrap();
                let by: f64 = caps[2].parse().unwrap();
                ((n * by) as i64).to_string()
            })
            .into_owned();
        // Keep the original indentation so byte offsets stay comparable line for line.
        let indent = &raw[..raw.len() - raw.trim_start().len()];
        out.push_str(indent);
        out.push_str(&line);
        out.push('\n');
    }
    out
}

/// One parsed recipe declaration, before the last-wins filtering.
struct RecipeData {
    result: u32,
    stack: u32,
    ingredients: Vec<(u32, u32)>,
    not_decraftable: bool,
    crimson: bool,
    corruption: bool,
    alchemy: bool,
}

/// Both ingredient-declaration styles, in slot order — mirrors `gen_recipes.py`'s `ingredients_of`.
fn ingredients_of(text: &str) -> Vec<(u32, u32)> {
    let mut found: BTreeMap<u32, [u32; 2]> = BTreeMap::new();

    // Style one: requiredItem[i].SetDefaults(X); optionally requiredItem[i].stack = N;
    let set_re = Regex::new(r"requiredItem\[(\d+)\]\.SetDefaults\((\d+)\)").unwrap();
    for cap in set_re.captures_iter(text) {
        let slot: u32 = cap[1].parse().unwrap();
        let item: u32 = cap[2].parse().unwrap();
        if item > 0 {
            found.insert(slot, [item, 1]);
        }
    }
    let stack_re = Regex::new(r"requiredItem\[(\d+)\]\.stack = (\d+)").unwrap();
    for cap in stack_re.captures_iter(text) {
        let slot: u32 = cap[1].parse().unwrap();
        let stack: u32 = cap[2].parse().unwrap();
        if let Some(entry) = found.get_mut(&slot) {
            entry[1] = stack;
        }
    }

    // Style two: SetIngredients(item, count, item, count, …) — the game's own convention is that
    // the call always alternates item, count; a trailing lone item defaults to a count of one.
    if let Some(m) = Regex::new(r"SetIngredients\(([^)]*)\)")
        .unwrap()
        .captures(text)
    {
        let nums: Vec<i64> = Regex::new(r"-?\d+")
            .unwrap()
            .find_iter(&m[1])
            .map(|x| x.as_str().parse().unwrap())
            .collect();
        let mut slot = found.len() as u32;
        let mut i = 0;
        while i + 1 < nums.len() {
            if nums[i] > 0 {
                found.insert(slot, [nums[i] as u32, (nums[i + 1].max(1)) as u32]);
                slot += 1;
            }
            i += 2;
        }
        if nums.len() % 2 == 1
            && let Some(&last) = nums.last()
            && last > 0
        {
            found.insert(slot, [last as u32, 1]);
        }
    }

    found.into_values().map(|v| (v[0], v[1])).collect()
}

/// A [`RecipeData`] with none of the flags a loop-built recipe ever sets. Checked against every
/// family below: none marks `notDecraftable`, none is evil-conditional, and none uses
/// `requiredTile = 13` (the one tile `Recipe.AddRecipe` promotes to `alchemy = true` on its own).
fn plain_recipe(result: u32, stack: u32, ingredients: Vec<(u32, u32)>) -> RecipeData {
    RecipeData {
        result,
        stack,
        ingredients,
        not_decraftable: false,
        crimson: false,
        corruption: false,
        alchemy: false,
    }
}

/// D1: the `StrungCounterweight` (5547) loop, `Recipe.cs` 9456-9463:
///
/// ```text
/// for (int l = 3309; l <= 3314; l++)
/// {
///     currentRecipe.createItem.SetDefaults(5547);
///     currentRecipe.requiredItem[0].SetDefaults(3306);
///     currentRecipe.requiredItem[1].SetDefaults(l);
///     currentRecipe.requiredTile = 114;
///     AddRecipe();
/// }
/// ```
///
/// Six recipes for the *same* result (one per colour string, 3309-3314), so only the last
/// (l = 3314) survives `UpdateWhichItemsAreCrafted`'s last-wins rule. Because `createItem` is a
/// literal `5547` here, `chunk_re` in [`generate`] also matches this loop's one copy of source
/// text, but `requiredItem[1]` is the loop variable `l`, not a digit, so the generic
/// `requiredItem\[(\d+)\]\.SetDefaults\((\d+)\)` parse silently drops the second ingredient. That
/// leaves a real but *wrong* single-ingredient recipe in the naive parse: (3306,1) alone, missing
/// White String's real partner. [`generate`] excludes any generic match inside the byte range this
/// function returns and uses these six instead, so the last-wins fold lands on the true final
/// recipe: White String (3306) plus Crimson/whichever String (3314), both present.
fn strung_counterweight_loop(body: &str) -> (Range<usize>, Vec<RecipeData>) {
    let re = Regex::new(concat!(
        r"for \(int l = (\d+); l <= (\d+); l\+\+\)\s*\{\s*",
        r"currentRecipe\.createItem\.SetDefaults\(5547\);\s*",
        r"currentRecipe\.requiredItem\[0\]\.SetDefaults\(3306\);\s*",
        r"currentRecipe\.requiredItem\[1\]\.SetDefaults\(l\);\s*",
        r"currentRecipe\.requiredTile = 114;\s*AddRecipe\(\);\s*\}",
    ))
    .unwrap();
    let caps = re
        .captures(body)
        .expect("StrungCounterweight loop not found; Recipe.cs's shape changed");
    let span = caps.get(0).unwrap().range();
    let start: u32 = caps[1].parse().unwrap();
    let end: u32 = caps[2].parse().unwrap();
    let recipes = (start..=end)
        .map(|l| plain_recipe(5547, 1, vec![(3306, 1), (l, 1)]))
        .collect();
    (span, recipes)
}

/// D1: the disguised-chest ("Fake_*") texture-copy loop, `Recipe.cs` 6524-6532:
///
/// ```text
/// for (int i = 3665; i <= 3704; i++)
/// {
///     currentRecipe.createItem.SetDefaults(i);
///     currentRecipe.requiredItem[0].SetDefaults(ItemID.Sets.TextureCopyLoad[i]);
///     currentRecipe.requiredItem[1].SetDefaults(530);
///     currentRecipe.requiredItem[1].stack = 10;
///     currentRecipe.requiredTile = 283;
///     AddRecipe();
/// }
/// ```
///
/// Forty fake chests (`Fake_Chest` = 3665 through `Fake_MarbleChest` = 3704), each from ten Wire
/// (530) and the item whose texture it copies: `ItemID.Sets.TextureCopyLoad[i]`
/// (`Terraria.ID/ItemID.cs` 1096, a `Factory.CreateIntSet(-1, key, value, …)` read the same way
/// [`crate::csharp::int_set`] reads every other one).
fn fake_chest_texture_copies(root: &Path, body: &str) -> Vec<RecipeData> {
    let bounds = Regex::new(concat!(
        r"for \(int i = (\d+); i <= (\d+); i\+\+\)\s*\{\s*",
        r"currentRecipe\.createItem\.SetDefaults\(i\);\s*",
        r"currentRecipe\.requiredItem\[0\]\.SetDefaults\(ItemID\.Sets\.TextureCopyLoad\[i\]\);",
    ))
    .unwrap()
    .captures(body)
    .expect("Fake_* texture-copy loop not found; Recipe.cs's shape changed");
    let start: u32 = bounds[1].parse().unwrap();
    let end: u32 = bounds[2].parse().unwrap();

    let item_cs = read_lossy(&root.join("Terraria.ID/ItemID.cs"));
    let (default, copy_from) = int_set(&item_cs, "TextureCopyLoad");

    (start..=end)
        .map(|i| {
            let source = *copy_from.get(&i).unwrap_or(&default);
            assert!(source > 0, "TextureCopyLoad[{i}] has no source item");
            plain_recipe(i, 1, vec![(source as u32, 1), (530, 10)])
        })
        .collect()
}

/// D1: 36 more disguised chests, given as an inline `int[,]` table rather than a range because
/// their ids are not contiguous. `Recipe.cs` 6533-6580:
///
/// ```text
/// int[,] array = new int[36, 2] { { 3886, 3884 }, … , { 6131, 6118 } };
/// for (int j = 0; j < array.GetLength(0); j++)
/// {
///     currentRecipe.createItem.SetDefaults(array[j, 0]);
///     currentRecipe.requiredItem[0].SetDefaults(array[j, 1]);
///     currentRecipe.requiredItem[1].SetDefaults(530);
///     currentRecipe.requiredItem[1].stack = 10;
///     currentRecipe.requiredTile = 283;
///     AddRecipe();
/// }
/// ```
///
/// Same ten-Wire (530) recipe shape as the loop above; `array[j, 0]` is the fake chest, `array[j, 1]`
/// the item it copies.
fn fake_chest_array(body: &str) -> Vec<RecipeData> {
    assert!(
        body.contains("for (int j = 0; j < array.GetLength(0); j++)"),
        "the 36-row Fake_* array's loop not found; Recipe.cs's shape changed"
    );
    let array_re = Regex::new(r"(?s)int\[,\] array = new int\[36, 2\]\s*\{(.*?)\};").unwrap();
    let array_body = &array_re
        .captures(body)
        .expect("36-row Fake_* array not found; Recipe.cs's shape changed")[1];
    let pair_re = Regex::new(r"\{\s*(\d+),\s*(\d+)\s*\}").unwrap();
    let pairs: Vec<(u32, u32)> = pair_re
        .captures_iter(array_body)
        .map(|c| (c[1].parse().unwrap(), c[2].parse().unwrap()))
        .collect();
    assert_eq!(pairs.len(), 36, "expected 36 Fake_* array rows");
    pairs
        .into_iter()
        .map(|(result, source)| plain_recipe(result, 1, vec![(source, 1), (530, 10)]))
        .collect()
}

/// D1: the weapon-rack loop, `Recipe.cs` 6700-6711:
///
/// ```text
/// for (int k = 2114; k <= 2118; k++)
/// {
///     currentRecipe.createItem.SetDefaults(k);
///     currentRecipe.requiredItem[0].SetDefaults(9);
///     currentRecipe.requiredItem[0].stack = 12;
///     currentRecipe.requiredItem[1].SetDefaults(22);
///     currentRecipe.requiredItem[1].stack = 3;
///     currentRecipe.requiredTile = 106;
///     currentRecipe.RequireGroup(RecipeGroups.Wood);
///     currentRecipe.RequireGroup(RecipeGroups.IronBar);
///     AddRecipe();
/// }
/// ```
///
/// Five racks (`BlacksmithRack` = 2114 onward), each from twelve Wood (9) and three Iron Bar (22).
/// The `RequireGroup` alternates (Lead Bar, the other woods) are not modelled, same as everywhere
/// else in this generator: only the literal `SetDefaults` ingredient is recorded.
fn blacksmith_racks(body: &str) -> Vec<RecipeData> {
    let bounds = Regex::new(concat!(
        r"for \(int k = (\d+); k <= (\d+); k\+\+\)\s*\{\s*",
        r"currentRecipe\.createItem\.SetDefaults\(k\);\s*",
        r"currentRecipe\.requiredItem\[0\]\.SetDefaults\(9\);\s*",
        r"currentRecipe\.requiredItem\[0\]\.stack = 12;\s*",
        r"currentRecipe\.requiredItem\[1\]\.SetDefaults\(22\);\s*",
        r"currentRecipe\.requiredItem\[1\]\.stack = 3;",
    ))
    .unwrap()
    .captures(body)
    .expect("weapon-rack loop not found; Recipe.cs's shape changed");
    let start: u32 = bounds[1].parse().unwrap();
    let end: u32 = bounds[2].parse().unwrap();
    (start..=end)
        .map(|k| plain_recipe(k, 1, vec![(9, 12), (22, 3)]))
        .collect()
}

/// D1: the alphabet-statue loop, `Recipe.cs` 9622-9629:
///
/// ```text
/// for (int m = 0; m < 36; m++)
/// {
///     currentRecipe.createItem.SetDefaults(2702 + m);
///     currentRecipe.requiredItem[0].SetDefaults(3);
///     currentRecipe.requiredItem[0].stack = 50;
///     currentRecipe.requiredTile = 283;
///     AddRecipe();
/// }
/// ```
///
/// 36 statues (`AlphabetStatue0` = 2702 onward), each from fifty Stone Block (3).
fn alphabet_statues(body: &str) -> Vec<RecipeData> {
    let bounds = Regex::new(concat!(
        r"for \(int m = 0; m < (\d+); m\+\+\)\s*\{\s*",
        r"currentRecipe\.createItem\.SetDefaults\((\d+) \+ m\);\s*",
        r"currentRecipe\.requiredItem\[0\]\.SetDefaults\(3\);\s*",
        r"currentRecipe\.requiredItem\[0\]\.stack = 50;",
    ))
    .unwrap()
    .captures(body)
    .expect("alphabet-statue loop not found; Recipe.cs's shape changed");
    let count: u32 = bounds[1].parse().unwrap();
    let base: u32 = bounds[2].parse().unwrap();
    (0..count)
        .map(|m| plain_recipe(base + m, 1, vec![(3, 50)]))
        .collect()
}

/// D1: `AddCritterStatueRecipe` (`Recipe.cs` 16702-16718), called 22 times from `SetupRecipes`
/// (9630-9651):
///
/// ```text
/// private static void AddCritterStatueRecipe(int statueItem, int critterItem = 0, RecipeGroup critterGroup = null)
/// {
///     currentRecipe.createItem.SetDefaults(statueItem);
///     currentRecipe.requiredItem[0].SetDefaults(3);
///     currentRecipe.requiredItem[0].stack = 50;
///     if (critterGroup != null)
///     {
///         critterItem = critterGroup.GetPlaceholderItemType();
///         currentRecipe.RequireGroup(critterGroup);
///     }
///     currentRecipe.requiredItem[1].SetDefaults(critterItem);
///     currentRecipe.requiredItem[1].stack = 5;
///     currentRecipe.requiredTile = 283;
///     AddRecipe();
/// }
/// ```
///
/// Every statue is fifty Stone Block (3) plus five of the critter. Fourteen calls pass a literal
/// critter item; eight pass a `RecipeGroup` instead (`RecipeGroups.Squirrels`, `.Butterflies`, …),
/// and the helper resolves that to the group's *first* member: `RecipeGroup.GetPlaceholderItemType`
/// returns `Items[0]` (`RecipeGroup.cs` 101-104), the same item the group was first constructed
/// with (`SetupRecipeGroups`, `Recipe.cs` 497-533). This reads that first member straight out of
/// `SetupRecipeGroups`'s source rather than hard-coding the twelve resolved ids, so it stays correct
/// if a group's member order ever changes.
fn critter_statues(src: &str, body: &str) -> Vec<RecipeData> {
    let group_re = Regex::new(r"RecipeGroups\.(\w+) = new RecipeGroup\([^,]+,\s*(\d+)").unwrap();
    let placeholders: BTreeMap<String, u32> = group_re
        .captures_iter(src)
        .map(|c| (c[1].to_string(), c[2].parse().unwrap()))
        .collect();
    assert!(
        placeholders.len() >= 20,
        "only {} recipe groups parsed; SetupRecipeGroups's shape changed",
        placeholders.len()
    );

    let call_re = Regex::new(r"AddCritterStatueRecipe\(([^)]*)\);").unwrap();
    let calls: Vec<Vec<String>> = call_re
        .captures_iter(body)
        .map(|c| c[1].split(',').map(|s| s.trim().to_string()).collect())
        .collect();
    assert_eq!(
        calls.len(),
        22,
        "expected 22 AddCritterStatueRecipe calls; Recipe.cs's shape changed"
    );

    calls
        .into_iter()
        .map(|args| {
            let statue: u32 = args[0].parse().unwrap();
            let critter = match args.get(2) {
                Some(group) => {
                    let name = group.trim_start_matches("RecipeGroups.");
                    *placeholders
                        .get(name)
                        .unwrap_or_else(|| panic!("unknown recipe group {name}"))
                }
                None => args[1].parse().unwrap(),
            };
            plain_recipe(statue, 1, vec![(3, 50), (critter, 5)])
        })
        .collect()
}

/// D1: the butterfly-jar loop, `Recipe.cs` 12840-12847:
///
/// ```text
/// for (int n = 0; n < 8; n++)
/// {
///     currentRecipe.createItem.SetDefaults(2178 + n);
///     currentRecipe.requiredItem[0].SetDefaults(1994 + n);
///     currentRecipe.requiredItem[0].stack = 1;
///     currentRecipe.requiredItem[1].SetDefaults(31);
///     AddRecipe();
/// }
/// ```
///
/// Eight jars (`MonarchButterflyJar` = 2178 onward), each from a caught butterfly (1994 onward,
/// `RecipeGroups.Butterflies`'s own members) and one Glass (31, default stack of one: the loop
/// never sets `requiredItem[1].stack`).
fn butterfly_jars(body: &str) -> Vec<RecipeData> {
    let bounds = Regex::new(concat!(
        r"for \(int n = 0; n < (\d+); n\+\+\)\s*\{\s*",
        r"currentRecipe\.createItem\.SetDefaults\((\d+) \+ n\);\s*",
        r"currentRecipe\.requiredItem\[0\]\.SetDefaults\((\d+) \+ n\);\s*",
        r"currentRecipe\.requiredItem\[0\]\.stack = 1;\s*",
        r"currentRecipe\.requiredItem\[1\]\.SetDefaults\(31\);",
    ))
    .unwrap()
    .captures(body)
    .expect("butterfly-jar loop not found; Recipe.cs's shape changed");
    let count: u32 = bounds[1].parse().unwrap();
    let jar_base: u32 = bounds[2].parse().unwrap();
    let critter_base: u32 = bounds[3].parse().unwrap();
    (0..count)
        .map(|n| plain_recipe(jar_base + n, 1, vec![(critter_base + n, 1), (31, 1)]))
        .collect()
}

/// D1: the dragonfly-jar loop, `Recipe.cs` 12848-12855:
///
/// ```text
/// for (int num5 = 4327; num5 <= 4332; num5++)
/// {
///     currentRecipe.createItem.SetDefaults(num5);
///     currentRecipe.requiredItem[0].SetDefaults(num5 - 4327 + 4334);
///     currentRecipe.requiredItem[0].stack = 1;
///     currentRecipe.requiredItem[1].SetDefaults(31);
///     AddRecipe();
/// }
/// ```
///
/// Six jars (`BlackDragonflyJar` = 4327 onward), each from a caught dragonfly
/// (`BlackDragonfly` = 4334 onward) and one Glass (31).
fn dragonfly_jars(body: &str) -> Vec<RecipeData> {
    let bounds = Regex::new(concat!(
        r"for \(int num5 = (\d+); num5 <= (\d+); num5\+\+\)\s*\{\s*",
        r"currentRecipe\.createItem\.SetDefaults\(num5\);\s*",
        r"currentRecipe\.requiredItem\[0\]\.SetDefaults\(num5 - (\d+) \+ (\d+)\);",
    ))
    .unwrap()
    .captures(body)
    .expect("dragonfly-jar loop not found; Recipe.cs's shape changed");
    let start: u32 = bounds[1].parse().unwrap();
    let end: u32 = bounds[2].parse().unwrap();
    let subtract: u32 = bounds[3].parse().unwrap();
    let critter_base: u32 = bounds[4].parse().unwrap();
    assert_eq!(subtract, start, "num5's offset formula changed shape");
    (start..=end)
        .map(|num5| plain_recipe(num5, 1, vec![(num5 - start + critter_base, 1), (31, 1)]))
        .collect()
}

/// D1: seven gemspark-wall blocks, `Recipe.cs` 3178-3320. Not a loop, but repeated straight-line
/// code reassigning the same three locals; the pattern is exact and repeats seven times, one per
/// gem colour:
///
/// ```text
/// num2 = 1970;
/// num3 = 2679;
/// num4 = 2680;
/// currentRecipe.createItem.SetDefaults(num3);
/// currentRecipe.createItem.stack = 4;
/// currentRecipe.requiredItem[0].SetDefaults(num2);
/// currentRecipe.requiredTile = 18;
/// AddRecipe();
/// currentRecipe.createItem.SetDefaults(num4);
/// currentRecipe.createItem.stack = 4;
/// currentRecipe.requiredItem[0].SetDefaults(num2);
/// currentRecipe.requiredTile = 18;
/// AddRecipe();
/// ```
///
/// The ordinary block-to-wall ratio (one block, four walls): `num2` is a Gemspark Block (1970 here
/// is `AmethystGemsparkBlock`), and `num3`/`num4` are its lit and unlit Gemspark Wall
/// (`AmethystGemsparkWall`/`AmethystGemsparkWallOff`), each four walls from one block.
fn gemspark_wall_variants(body: &str) -> Vec<RecipeData> {
    let re = Regex::new(concat!(
        r"num2 = (\d+);\s*num3 = (\d+);\s*num4 = (\d+);\s*",
        r"currentRecipe\.createItem\.SetDefaults\(num3\);\s*currentRecipe\.createItem\.stack = 4;\s*",
        r"currentRecipe\.requiredItem\[0\]\.SetDefaults\(num2\);\s*currentRecipe\.requiredTile = 18;\s*AddRecipe\(\);\s*",
        r"currentRecipe\.createItem\.SetDefaults\(num4\);\s*currentRecipe\.createItem\.stack = 4;\s*",
        r"currentRecipe\.requiredItem\[0\]\.SetDefaults\(num2\);\s*currentRecipe\.requiredTile = 18;\s*AddRecipe\(\);",
    ))
    .unwrap();
    let matches: Vec<_> = re.captures_iter(body).collect();
    assert_eq!(
        matches.len(),
        7,
        "expected 7 gemspark-wall blocks; Recipe.cs's shape changed"
    );
    let mut out = Vec::new();
    for c in matches {
        let block: u32 = c[1].parse().unwrap();
        let wall_lit: u32 = c[2].parse().unwrap();
        let wall_off: u32 = c[3].parse().unwrap();
        out.push(plain_recipe(wall_lit, 4, vec![(block, 1)]));
        out.push(plain_recipe(wall_off, 4, vec![(block, 1)]));
    }
    out
}

/// D1: `AddStandardFurnitureSetRecipes` (`Recipe.cs` 16581-16700), called 21 times from the various
/// `AddXxxFurniture` wrappers (16480-16578), which are themselves called from `SetupRecipes`
/// (5795-5826). Each call names a primary material and nineteen furniture pieces (`bathtub` through
/// `workbench`; the helper's twentieth parameter, `fake_chest`, is declared but never used by its
/// body) and the helper applies the *same* fixed ingredient formula to all nineteen, in this order:
///
/// ```text
/// bathtub:    primaryMaterial×14
/// bed:        primaryMaterial×15, Vine(225)×5
/// bookcase:   primaryMaterial×20, Sunplate Block(149)×10
/// dresser:    primaryMaterial×16
/// candelabra: primaryMaterial×5,  Torch(8)×3
/// candle:     primaryMaterial×4,  Torch(8)×1
/// chair:      primaryMaterial×4
/// chandelier: primaryMaterial×4,  Torch(8)×4, Chain(85)×1
/// chest:      primaryMaterial×8,  Iron Bar(22)×2
/// clock:      primaryMaterial×10, Iron Bar(22)×3, Lead Bar-group Bar(170)×6
/// door:       primaryMaterial×6
/// lamp:       Torch(8)×1, primaryMaterial×3
/// lantern:    primaryMaterial×6,  Torch(8)×1
/// piano:      primaryMaterial×15, Silk(154)×4, Sunplate Block(149)×1
/// sink:       primaryMaterial×6,  Waterbolt(206)×1
/// sofa:       primaryMaterial×5,  Vine(225)×2
/// table:      primaryMaterial×8
/// workbench:  primaryMaterial×10
/// toilet:     primaryMaterial×6
/// ```
///
/// `AddPineFurniture` (16520-16524) calls the helper twice with the same nineteen result items but
/// two different primary materials (1872, then 5930): both sets are emitted here, in call order,
/// so the existing last-recipe-wins fold in [`generate`] lands on the second exactly as
/// `UpdateWhichItemsAreCrafted` would.
fn standard_furniture_sets(body: &str) -> Vec<RecipeData> {
    let call_re = Regex::new(r"AddStandardFurnitureSetRecipes\(([^)]*)\);").unwrap();
    let mut out = Vec::new();
    let mut calls = 0u32;
    for cap in call_re.captures_iter(body) {
        let nums: Vec<u32> = cap[1]
            .split(',')
            .map(|s| s.trim().parse().unwrap())
            .collect();
        assert!(
            nums.len() >= 21,
            "AddStandardFurnitureSetRecipes call has {} args, expected at least 21",
            nums.len()
        );
        calls += 1;
        // primaryMaterial, bathtub, bed, bookcase, candelabra, candle, chair, chandelier, chest,
        // clock, door, dresser, lamp, lantern, piano, sink, sofa, table, toilet, workbench,
        // fake_chest[, overrideStation]: `Recipe.cs` 16581.
        let material = nums[0];
        let (bathtub, bed, bookcase, candelabra, candle) =
            (nums[1], nums[2], nums[3], nums[4], nums[5]);
        let (chair, chandelier, chest, clock, door) =
            (nums[6], nums[7], nums[8], nums[9], nums[10]);
        let (dresser, lamp, lantern, piano, sink) =
            (nums[11], nums[12], nums[13], nums[14], nums[15]);
        let (sofa, table, toilet, workbench) = (nums[16], nums[17], nums[18], nums[19]);

        // Order and ingredients mirror the helper body exactly, `Recipe.cs` 16583-16699.
        out.push(plain_recipe(bathtub, 1, vec![(material, 14)]));
        out.push(plain_recipe(bed, 1, vec![(material, 15), (225, 5)]));
        out.push(plain_recipe(bookcase, 1, vec![(material, 20), (149, 10)]));
        out.push(plain_recipe(dresser, 1, vec![(material, 16)]));
        out.push(plain_recipe(candelabra, 1, vec![(material, 5), (8, 3)]));
        out.push(plain_recipe(candle, 1, vec![(material, 4), (8, 1)]));
        out.push(plain_recipe(chair, 1, vec![(material, 4)]));
        out.push(plain_recipe(
            chandelier,
            1,
            vec![(material, 4), (8, 4), (85, 1)],
        ));
        out.push(plain_recipe(chest, 1, vec![(material, 8), (22, 2)]));
        out.push(plain_recipe(
            clock,
            1,
            vec![(material, 10), (22, 3), (170, 6)],
        ));
        out.push(plain_recipe(door, 1, vec![(material, 6)]));
        out.push(plain_recipe(lamp, 1, vec![(8, 1), (material, 3)]));
        out.push(plain_recipe(lantern, 1, vec![(material, 6), (8, 1)]));
        out.push(plain_recipe(
            piano,
            1,
            vec![(material, 15), (154, 4), (149, 1)],
        ));
        out.push(plain_recipe(sink, 1, vec![(material, 6), (206, 1)]));
        out.push(plain_recipe(sofa, 1, vec![(material, 5), (225, 2)]));
        out.push(plain_recipe(table, 1, vec![(material, 8)]));
        out.push(plain_recipe(workbench, 1, vec![(material, 10)]));
        out.push(plain_recipe(toilet, 1, vec![(material, 6)]));
    }
    assert_eq!(
        calls, 21,
        "expected 21 AddStandardFurnitureSetRecipes calls; Recipe.cs's shape changed"
    );
    out
}

/// D1: every loop- and helper-built recipe family `SetupRecipes` constructs, unrolled and
/// concatenated. `CreateReverseWallRecipes` and `CreateReversePlatformRecipes` (`Recipe.cs` 16744
/// and 16720, called from `SetupRecipes` at 15148-15149) build recipes the same programmatic way
/// but are deliberately excluded: both mark every recipe they add `notDecraftable = true`
/// immediately after `AddRecipe()`, so however many they add, none is ever decraftable; unrolling
/// them would add source and tests for zero table rows.
///
/// None of the ten families here shares a result item with any other family, nor with any of the
/// literal recipes `chunk_re` already parses in [`generate`] (checked by hand against every id each
/// produces), except `StrungCounterweight`, whose one collision is with `chunk_re`'s own spurious
/// partial match, which [`generate`] excludes before calling this function. So simple
/// concatenation, in the order the families appear below, is enough for `UpdateWhichItemsAreCrafted`'s
/// last-wins fold to land on the same recipe the game would.
fn loop_built_recipes(root: &Path, src: &str, body: &str) -> Vec<RecipeData> {
    let mut out = Vec::new();
    out.extend(fake_chest_texture_copies(root, body));
    out.extend(fake_chest_array(body));
    out.extend(blacksmith_racks(body));
    out.extend(strung_counterweight_loop(body).1);
    out.extend(alphabet_statues(body));
    out.extend(critter_statues(src, body));
    out.extend(butterfly_jars(body));
    out.extend(dragonfly_jars(body));
    out.extend(gemspark_wall_variants(body));
    out.extend(standard_furniture_sets(body));
    out
}

/// Emit an ascending `static NAME: [(u16, u16); N]` index table. `cargo fmt` reflows the rows.
fn index_table(name: &str, rows: &[(u32, u32)], doc: &str) -> String {
    let body: Vec<String> = rows.iter().map(|&(a, b)| format!("({a},{b}),")).collect();
    format!(
        "{doc}\nstatic {name}: [(u16, u16); {}] = [\n    {}\n];",
        rows.len(),
        body.join(" ")
    )
}

pub fn generate(root: &Path) -> String {
    let src = read_lossy(&root.join("Terraria/Recipe.cs"));
    let start = src
        .find("public static void SetupRecipes()")
        .expect("SetupRecipes not found");
    let body = &src[start..];
    // The literal-text scan below reads the resolved copy; `loop_built_recipes` keeps the raw one,
    // because its per-family regexes match `SetupRecipes`' own loop and helper text verbatim.
    let resolved = resolve_recipe_locals(body);

    let chunk_re =
        Regex::new(r"(?s)currentRecipe\.createItem\.SetDefaults\((\d+)\);(.*?)AddRecipe\(\);")
            .unwrap();
    let stack_re = Regex::new(r"createItem\.stack = (\d+)").unwrap();

    // D1: the StrungCounterweight loop's one copy of source text is a spurious match for
    // `chunk_re` above (see `strung_counterweight_loop`'s doc comment): it has a literal
    // `createItem`, but a loop-variable `requiredItem[1]` that the generic ingredient parse can't
    // see, so left in it would produce a real but wrong single-ingredient recipe. Exclude it here;
    // `loop_built_recipes` supplies the correct six recipes instead.
    let (strung_exclude, _) = strung_counterweight_loop(&resolved);

    let mut recipes: Vec<RecipeData> = Vec::new();
    for cap in chunk_re.captures_iter(&resolved) {
        if strung_exclude.contains(&cap.get(0).unwrap().start()) {
            continue;
        }
        let result: u32 = cap[1].parse().unwrap();
        let text = &cap[2];
        let stack = stack_re.captures(text).map_or(1, |m| m[1].parse().unwrap());
        recipes.push(RecipeData {
            result,
            stack,
            ingredients: ingredients_of(text),
            not_decraftable: text.contains("notDecraftable = true")
                || text.contains("DisableDecraft()"),
            crimson: text.contains("crimson = true")
                || text.contains(".AddCondition(Condition.InCrimson"),
            corruption: text.contains("corruption = true")
                || text.contains(".AddCondition(Condition.InCorruption"),
            // `Recipe.AddRecipe` (`Recipe.cs:16795-16800`) sets `alchemy` itself, from the
            // crafting station: `if (currentRecipe.requiredTile == 13) currentRecipe.alchemy =
            // true;` (tile 13 is the Bottle/Alchemy Table). The literal `alchemy = true` never
            // appears anywhere in `SetupRecipes`, so looking for it left the flag false on all
            // 3,098 rows and shimmer-decrafting a potion returned every ingredient instead of
            // losing one in three: a free material duplicator, which is exactly what the flag
            // exists to prevent. Both spellings of the assignment count.
            alchemy: text.contains("requiredTile = 13;") || text.contains("SetCraftingStation(13)"),
        });
    }
    assert!(
        recipes.len() >= 1000,
        "only {} recipes parsed; SetupRecipes' shape changed",
        recipes.len()
    );

    // D1: the ~570 recipes `SetupRecipes` builds inside `for` loops and small per-set helper
    // functions, invisible to `chunk_re` above. See `loop_built_recipes`'s doc comment for the full
    // family inventory and why appending them here (rather than interleaving by source position) is
    // safe.
    recipes.extend(loop_built_recipes(root, &src, body));
    assert!(
        recipes.len() >= 3200,
        "only {} recipes total after adding the loop-built families; a family's regex stopped \
         matching (Recipe.cs's shape changed) rather than the extraction actually shrinking",
        recipes.len()
    );

    // `UpdateWhichItemsAreCrafted`: the last decraftable recipe for a result wins.
    let mut is_crafted: BTreeMap<u32, usize> = BTreeMap::new();
    let mut crimson_of: BTreeMap<u32, usize> = BTreeMap::new();
    let mut corruption_of: BTreeMap<u32, usize> = BTreeMap::new();
    for (index, r) in recipes.iter().enumerate() {
        if r.ingredients.is_empty() {
            continue;
        }
        if !r.not_decraftable {
            is_crafted.insert(r.result, index);
        }
        if r.crimson {
            crimson_of.insert(r.result, index);
        }
        if r.corruption {
            corruption_of.insert(r.result, index);
        }
    }

    let mut used: Vec<usize> = is_crafted
        .values()
        .chain(crimson_of.values())
        .chain(corruption_of.values())
        .copied()
        .collect();
    used.sort_unstable();
    used.dedup();
    let renumber: BTreeMap<usize, usize> = used
        .iter()
        .enumerate()
        .map(|(new, &old)| (old, new))
        .collect();

    // Pack ingredients end to end and lay out the recipes in kept order.
    let mut flat: Vec<(u32, u32)> = Vec::new();
    let mut recipe_rows: Vec<String> = Vec::new();
    for &old in &used {
        let r = &recipes[old];
        let first = flat.len();
        flat.extend(r.ingredients.iter().copied());
        recipe_rows.push(format!(
            "    Recipe {{ result: {}, makes: {}, first: {first}, count: {}, alchemy: {} }},",
            r.result,
            r.stack,
            r.ingredients.len(),
            r.alchemy
        ));
    }

    let ingredients_rows: Vec<String> = flat.iter().map(|&(i, s)| format!("({i},{s}),")).collect();
    let ingredients_block = format!(
        "/// Every decraftable recipe's ingredients, packed end to end.\n\
         ///\n\
         /// `static` rather than `const`: a `const` of this size is copied at every use site.\n\
         static INGREDIENTS: [Ingredient; {}] = [\n    {}\n];",
        flat.len(),
        ingredients_rows.join(" ")
    );
    let recipes_block = format!(
        "/// The recipes themselves, in the game's own order.\nstatic RECIPES: [Recipe; {}] = [\n{}\n];",
        used.len(),
        recipe_rows.join("\n")
    );

    let renumbered = |mapping: &BTreeMap<u32, usize>| -> Vec<(u32, u32)> {
        let mut rows: Vec<(u32, u32)> = mapping
            .iter()
            .filter_map(|(&item, old)| renumber.get(old).map(|&new| (item, new as u32)))
            .collect();
        rows.sort_unstable();
        rows
    };
    let crafted_by = index_table(
        "CRAFTED_BY",
        &renumbered(&is_crafted),
        "/// Which recipe makes each craftable item. `ItemID.Sets.IsCrafted`.",
    );
    let crafted_by_crimson = index_table(
        "CRAFTED_BY_CRIMSON",
        &renumbered(&crimson_of),
        "/// ...and the crimson-world variant, where one exists.",
    );
    let crafted_by_corruption = index_table(
        "CRAFTED_BY_CORRUPTION",
        &renumbered(&corruption_of),
        "/// ...and the corruption one.",
    );

    format!(
        "{HEADER}\n\n{ingredients_block}\n\n{recipes_block}\n\n{crafted_by}\n\n{crafted_by_crimson}\n\n{crafted_by_corruption}\n\n{TAIL}\n"
    )
}
