//! `crates/terrustia-proto/src/tile_death.rs`: which tiles a liquid destroys on contact.
//!
//! `Main.tileLavaDeath` and `Main.tileWaterDeath` (`Terraria/Main.cs`) are two `bool[TileID.Count]`
//! arrays, all false by default, that `Main.SetupTileMerge` and its neighbours toggle with several
//! hundred individual `tileLavaDeath[N] = true;` (and the occasional `= false;` override) statements,
//! plus one `for` loop that sets a short run of ids at once. There is no `TileID.Sets.CreateBoolSet`
//! call to lean on here, unlike `hurt_tiles.rs`'s tables, so this reads the setup method itself.
//!
//! There is no `tileShimmerDeath` or equivalent in 1.4.5.8: searched the whole decompiled tree for
//! anything shimmer-and-death shaped and found nothing, so only the lava and water tables exist.
//!
//! Ported fresh; there is no `gen_tile_death.py` predecessor.

use std::collections::BTreeMap;
use std::path::Path;

use regex::Regex;

use crate::csharp::{read_lossy, ushort_const};

const MODULE_DOC: &str = "\
//! Which tiles a liquid destroys on contact, generated from the game's own setup code.
//!
//! `Main.tileLavaDeath` and `Main.tileWaterDeath`: a lava or water tile that spreads into one of
//! these kills it, the way a torch goes out in a flood or a table burns in lava. There is no
//! shimmer equivalent in 1.4.5.8: shimmer transforms what touches it rather than destroying
//! furniture, and no `tileShimmerDeath`-shaped array exists in the decompiled source.
//!
//! The consumer is `kill_drowned_furniture` (`game/server/systems.rs`), which reads whichever of
//! the two tables matches the liquid that arrived and kills the tile outright, exactly as
//! `Liquid.AddWater`'s own inline check does (`Liquid.cs:1196-1215`). This header used to say
//! nothing consulted the table yet, which stopped being true without the header noticing.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.";

const LAVA_DOC: &str = "\
/// Whether a lava tile spreading into this one destroys it. `Main.tileLavaDeath`.";

const WATER_DOC: &str = "\
/// Whether a water tile spreading into this one destroys it. `Main.tileWaterDeath`.";

const TAIL: &str = r#"/// Whether lava destroys this tile on contact.
pub fn lava_death(tile: u16) -> bool {
    LAVA_DEATH.get(tile as usize).copied().unwrap_or(false)
}

/// Whether water destroys this tile on contact.
pub fn water_death(tile: u16) -> bool {
    WATER_DEATH.get(tile as usize).copied().unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Spot checks against tiles whose behaviour is unmistakable: a torch (4) goes dark in a
    /// flood but is untouched by lava; cobweb (51) burns and washes away either way; stone (1)
    /// shrugs off both.
    #[test]
    fn the_obvious_cases_match_the_game() {
        assert!(water_death(4), "a torch goes out in water");
        assert!(!lava_death(4), "but is untouched by lava");
        assert!(lava_death(51), "cobweb burns in lava");
        assert!(water_death(51), "and washes away in water");
        assert!(!lava_death(1), "stone is unaffected by lava");
        assert!(!water_death(1), "and by water");
    }

    /// Every tile lava destroys was reachable from at least one statement in the setup method;
    /// this is really a check that the table did not regenerate empty.
    #[test]
    fn the_tables_are_populated() {
        assert!(LAVA_DEATH.iter().filter(|&&b| b).count() > 100);
        assert!(WATER_DEATH.iter().filter(|&&b| b).count() > 5);
    }

    /// Most of `tileLavaDeath` is set tile by tile, but 435..=439 (the five team-block platforms)
    /// are set by a `for` loop instead: `for (int num2 = 435; num2 <= 439; num2++) { ...
    /// tileLavaDeath[num2] = true; ... }`. None of the five appears as a literal
    /// `tileLavaDeath[N] = true;` anywhere else in `Main.cs`, so this is entirely a check that the
    /// generator's loop expansion ran rather than skipped a range it could not read.
    #[test]
    fn the_loop_set_range_is_not_missed() {
        for tile in 435..=439u16 {
            assert!(lava_death(tile), "tile {tile} is set by the num2 loop");
        }
    }
}"#;

/// Every `<name>[N] = true/false;` assignment in `main_cs`, and every `<name>[VAR] = true;` inside
/// a `for (int VAR = A; VAR <= B; VAR++) { ... }` loop, applied in the order they appear in the
/// file (a later statement overrides an earlier one for the same id, exactly as the real
/// initialisation order would). `main_cs` is `Terraria/Main.cs`'s own decompiled text; `name` is
/// `tileLavaDeath` or `tileWaterDeath`.
fn extract(main_cs: &str, name: &str) -> BTreeMap<u32, bool> {
    let escaped = regex::escape(name);

    // Individual assignments: `tileLavaDeath[427] = true;`.
    let literal_re = Regex::new(&format!(r"{escaped}\[(\d+)\] = (true|false);")).unwrap();
    let mut events: Vec<(usize, u32, bool)> = literal_re
        .captures_iter(main_cs)
        .map(|c| {
            let whole = c.get(0).unwrap();
            let id: u32 = c[1].parse().unwrap();
            let value = &c[2] == "true";
            (whole.start(), id, value)
        })
        .collect();

    // A short run set inside a loop rather than written out: `for (int num2 = 435; num2 <= 439;
    // num2++) { ...; tileLavaDeath[num2] = true; ... }`. Only a `= true;` form has been seen in
    // the wild, so that is all this expands. The `regex` crate has no backreferences, so the loop
    // variable is captured three times (once per use) and checked for equality by hand instead of
    // matched with `\1`.
    let loop_re =
        Regex::new(r"for \(int (\w+) = (\d+); (\w+) <= (\d+); (\w+)\+\+\)\s*\{([^}]*)\}").unwrap();
    for c in loop_re.captures_iter(main_cs) {
        let (var, var2, var3) = (&c[1], &c[3], &c[5]);
        if var != var2 || var != var3 {
            continue;
        }
        let start: u32 = c[2].parse().unwrap();
        let end: u32 = c[4].parse().unwrap();
        let body = &c[6];
        let assigns_in_loop =
            Regex::new(&format!(r"{escaped}\[{}\] = true;", regex::escape(var))).unwrap();
        if assigns_in_loop.is_match(body) {
            let at = c.get(0).unwrap().start();
            for id in start..=end {
                events.push((at, id, true));
            }
        }
    }

    events.sort_by_key(|&(at, ..)| at);
    let mut table = BTreeMap::new();
    for (_, id, value) in events {
        table.insert(id, value);
    }
    table
}

fn bool_table(name: &str, applied: &BTreeMap<u32, bool>, count: usize, doc: &str) -> String {
    let vals: Vec<&str> = (0..count as u32)
        .map(|i| {
            if applied.get(&i).copied().unwrap_or(false) {
                "true,"
            } else {
                "false,"
            }
        })
        .collect();
    format!(
        "{doc}\npub const {name}: [bool; {count}] = [\n    {}\n];",
        vals.join(" ")
    )
}

pub fn generate(root: &Path) -> String {
    let tile_cs = read_lossy(&root.join("Terraria.ID/TileID.cs"));
    let count = ushort_const(&tile_cs, "Count");

    let main_cs = read_lossy(&root.join("Terraria/Main.cs"));
    let lava = extract(&main_cs, "tileLavaDeath");
    let water = extract(&main_cs, "tileWaterDeath");

    assert!(
        lava.values().filter(|&&v| v).count() > 100,
        "only found {} lava-death tiles; the parser is wrong",
        lava.values().filter(|&&v| v).count()
    );
    assert!(
        water.values().filter(|&&v| v).count() > 5,
        "only found {} water-death tiles; the parser is wrong",
        water.values().filter(|&&v| v).count()
    );

    let lava_table = bool_table("LAVA_DEATH", &lava, count, LAVA_DOC);
    let water_table = bool_table("WATER_DEATH", &water, count, WATER_DOC);
    format!("{MODULE_DOC}\n\n{lava_table}\n\n{water_table}\n\n{TAIL}\n")
}
