//! `crates/terrustia-proto/src/tile_object.rs`: how big each placeable object is and how its
//! styles are laid out in the sheet.
//!
//! Every other table in this crate is read off a declaration. This one is not: `TileObjectData
//! .Initialize` (`Terraria.ObjectData/TileObjectData.cs:2111-5015`) is a 2,900-line *program* that
//! mutates one shared "current object" field by field and stamps it into a slot with `addTile(N)`,
//! then keeps mutating the next one from a fresh base. There is nothing to read off. The only way
//! to get the end state is to run it, so this module is a small interpreter for the statement
//! vocabulary that method actually uses.
//!
//! Four details decide whether the interpretation is right, and a plausible shortcut gets each one
//! wrong:
//!
//! * **`addTile` resets the current object.** Each of `addTile`/`addBaseTile` ends with
//!   `newTile = new TileObjectData(_baseObject)` (`:2009-2014`), so a tile inherits the *base*
//!   defaults and never its predecessor's. Reading `Initialize` as one running accumulator is the
//!   tempting misreading, and it silently gives an entry whatever the tile before it last set.
//! * **`CopyFrom` shares module references rather than copying them** (`:1698-1715`). Writes go
//!   through a copy-on-write guarded by `_hasOwn*`, and `CopyFrom` leaves those flags alone, so an
//!   object that already owns a module and is then `CopyFrom`'d keeps the flag and writes straight
//!   through into what it copied from. Value semantics get this wrong, so the modules here are
//!   `Rc<RefCell<_>>` and are shared exactly as the game shares them.
//! * **A setter handed the value already in place returns early**, before the copy-on-write and
//!   before `calculated = false`. `CoordinatePadding = 2` on something already at 2 is not the same
//!   no-op as skipping the line: it leaves a stale `calculated` behind.
//! * **`Calculate` is memoised on the coordinate module** (`:1805-1811`) while the `Width` it reads
//!   lives in the *base* module. Setting `Width` clears `calculated` only when the object did not
//!   already own its base module (`:1186-1201`). That asymmetry is observable in the shipped
//!   numbers.
//!
//! Only the per-type entry is emitted. Vanilla also carries sub-tiles (per style) and alternates
//! (per placement direction); they are interpreted here because `FullCopyFrom` reads a style-0
//! sub-tile, but they are not part of the table and the emitted header says so.

use std::cell::RefCell;
use std::collections::BTreeMap;
use std::path::Path;
use std::rc::Rc;

use regex::Regex;

use crate::csharp::read_lossy;

const MODULE_DOC: &str = "\
//! Multi-tile objects: how big each one is and how its frames are laid out.
//!
//! `TileObjectData.Initialize` sets these up imperatively rather than as a table, mutating a
//! shared \"current object\" and stamping it into a slot, so the numbers here are the end state of
//! running that method rather than anything written down in it. A chest is two by two anchored at
//! its bottom-left, a door one by three anchored at its top, and placing either at the wrong
//! origin puts furniture through the floor.
//!
//! `full_width` and `full_height` are `CoordinateFullWidth`/`CoordinateFullHeight`: the size of one
//! style's block in the sprite sheet, which is what a style index is multiplied by to find its
//! frames. Both count the padding after every row and column, not between them, and both carry
//! `CoordinatePaddingFix` on top.
//!
//! Vanilla also gives most of these a set of sub-tiles (per style) and alternates (per placement
//! direction), which change anchors and liquid rules but never the geometry or the style layout.
//! Neither is modelled here; nothing this server does with an object needs them.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.8. Do not edit by hand.";

/// The hand-written half: the struct and the frame arithmetic, which is a transcription of
/// `TileObject.Place` and `TileObjectData.GetTileData` rather than of any table.
const HEAD: &str = r#"/// The shape of one placeable object.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TileObject {
    /// Size in tiles.
    pub width: i32,
    pub height: i32,
    /// Which tile of the object the player's cursor is on when they place it.
    pub origin: (i32, i32),
    /// Sprite-sheet geometry.
    pub coord_width: i32,
    pub coord_heights: &'static [i32],
    pub padding: i32,
    pub full_width: i32,
    pub full_height: i32,
    /// How styles are laid out in the sheet.
    pub style_horizontal: bool,
    pub style_multiplier: i32,
    pub style_wrap: i32,
    pub style_line_skip: i32,
    pub style_base: i32,
}

impl TileObject {
    /// The frame position of a given style, as `(x, y)` in the sheet.
    ///
    /// Styles run along one axis and wrap onto a new line after `style_wrap` of them, skipping
    /// `style_line_skip` rows each time, which is why a door's styles run down the sheet three
    /// rows at a time and a table's run across it. `TileObject.Place` (`TileObject.cs:57-76`),
    /// with `style * style_multiplier + style_base` from `CalculatePlacementStyle`
    /// (`TileObjectData.cs:1990-1997`).
    pub fn frame_of(&self, style: i32, random: i32) -> (i32, i32) {
        let mut index = style * self.style_multiplier + self.style_base;
        if random >= 0 {
            index += random;
        }
        let mut line = 0;
        if self.style_wrap > 0 {
            line = index / self.style_wrap * self.style_line_skip;
            index %= self.style_wrap;
        }
        if self.style_horizontal {
            (self.full_width * index, self.full_height * line)
        } else {
            (self.full_width * line, self.full_height * index)
        }
    }

    /// Which style a frame belongs to: the inverse of [`Self::frame_of`].
    ///
    /// This is what turns a mined object back into the item that placed it: the frame is all the
    /// world stores, and every table that says what a chair is worth is indexed by style.
    ///
    /// The frame given must be the object's *top-left* one. Any other cell of it is offset by
    /// where in the object it sits, which is what [`origin_of`] undoes.
    pub fn style_of(&self, frame_x: i16, frame_y: i16) -> i32 {
        if self.full_width == 0 || self.full_height == 0 {
            return 0;
        }
        let across = i32::from(frame_x) / self.full_width;
        let down = i32::from(frame_y) / self.full_height;
        // One axis carries the style and the other counts lines, and which is which is the
        // object's own business: a door's styles run down the sheet, a table's across it.
        let (index, line) = if self.style_horizontal {
            (across, down)
        } else {
            (down, across)
        };
        let index = if self.style_wrap > 0 && self.style_line_skip > 0 {
            index + line / self.style_line_skip * self.style_wrap
        } else {
            index
        };
        let multiplier = self.style_multiplier.max(1);
        (index - self.style_base).div_euclid(multiplier)
    }
}

/// Walk back from any cell of a multi-tile object to its top-left one.
///
/// A player mining a table hits whichever tile the cursor was over; everything that decides what
/// a table is worth starts from its corner. The frame says how far in the cell sits.
pub fn origin_of(block: u16, frame_x: i16, frame_y: i16) -> Option<(i32, i32)> {
    let object = tile_object(block)?;
    if object.full_width == 0 || object.full_height == 0 {
        return Some((0, 0));
    }
    let coord = object.coord_width + object.padding;
    let across = if coord > 0 {
        (i32::from(frame_x) % object.full_width) / coord
    } else {
        0
    };
    // Rows can differ in height, so walking down them is a subtraction rather than a division.
    let mut left = i32::from(frame_y) % object.full_height;
    let mut down = 0;
    for height in object.coord_heights {
        if left < height + object.padding {
            break;
        }
        left -= height + object.padding;
        down += 1;
    }
    Some((across.min(object.width - 1), down.min(object.height - 1)))
}

/// The object a tile type places, or `None` for a type that is not a multi-tile object."#;

const TAIL: &str = r##"#[cfg(test)]
mod tests {
    use super::tile_object;

    /// A handful of objects everyone knows the shape of. If these are right the extraction
    /// worked; if any is wrong the whole table is suspect.
    #[test]
    fn the_familiar_objects_are_the_right_shape() {
        let cases = [
            // block, width, height, origin
            (10u16, 1, 3, (0, 0)), // a door
            (21, 2, 2, (0, 1)),    // a chest
            (14, 3, 2, (1, 1)),    // a table
            (15, 1, 2, (0, 1)),    // a chair
            (79, 4, 2, (1, 1)),    // a bed
            (17, 3, 2, (1, 1)),    // a furnace
            (18, 2, 1, (0, 0)),    // a workbench
            (101, 3, 4, (1, 3)),   // a bookcase
            (104, 2, 5, (0, 4)),   // a grandfather clock
        ];
        for (block, width, height, origin) in cases {
            let object =
                tile_object(block).unwrap_or_else(|| panic!("{block} should be an object"));
            assert_eq!(
                (object.width, object.height, object.origin),
                (width, height, origin),
                "block {block}"
            );
        }
    }

    /// Ordinary blocks are not objects, and asking is how the placement path tells them apart.
    #[test]
    fn plain_blocks_are_not_objects() {
        for block in [0u16, 1, 2, 30, 38] {
            assert!(
                tile_object(block).is_none(),
                "block {block} is not an object"
            );
        }
    }

    /// A workbench occupies the two tiles to the right of its origin, framed in order.
    #[test]
    fn a_workbench_frames_its_two_columns_in_order() {
        let bench = tile_object(18).expect("a workbench is an object");
        assert_eq!((bench.width, bench.height), (2, 1));
        assert_eq!(bench.origin, (0, 0), "its origin is its top-left");
        let (fx, _) = bench.frame_of(0, -1);
        let second = fx + (bench.coord_width + bench.padding);
        assert!(second > fx, "the second column is framed after the first");
    }

    /// Styles run along one axis and wrap onto new lines.
    #[test]
    fn styles_step_across_the_sheet() {
        let chest = tile_object(21).unwrap();
        let first = chest.frame_of(0, -1);
        let second = chest.frame_of(1, -1);
        assert_eq!(first, (0, 0), "the first style sits at the origin");
        assert_ne!(second, first, "and the second does not");

        // A door's styles run down rather than across.
        let door = tile_object(10).unwrap();
        assert!(!door.style_horizontal);
        let (x, y) = door.frame_of(1, -1);
        assert_eq!(x, 0, "a door's second style is on the same column");
        assert!(y > 0, "and further down");
    }

    /// The frame stride of the objects whose sheets are the easiest to state from memory.
    ///
    /// Every one of these was wrong before the table was generated, because the style layout had
    /// been filled in with a uniform guess (`multiplier` 2, `wrap` 2, `line_skip` 2) instead of
    /// read out of `Initialize`. A torch is the loudest: its styles step 22 down the sheet, and
    /// the guess put style 1 at 40.
    #[test]
    fn the_common_sheets_step_the_way_the_game_draws_them() {
        // A torch: six orientations across, one style per row, 22 apart.
        let torch = tile_object(4).unwrap();
        assert_eq!(torch.frame_of(0, -1), (0, 0));
        assert_eq!(torch.frame_of(1, -1), (0, 22));
        assert_eq!(torch.frame_of(2, -1), (0, 44));

        // A chair: two facings across, one style per row, 40 apart.
        let chair = tile_object(15).unwrap();
        assert_eq!(chair.frame_of(1, -1), (0, 40));

        // A table and a chest: styles straight across the sheet, one full width apart.
        assert_eq!(tile_object(14).unwrap().frame_of(1, -1), (54, 0));
        assert_eq!(tile_object(21).unwrap().frame_of(1, -1), (36, 0));

        // A door: styles down the sheet 54 apart, wrapping to the next column after 36.
        let door = tile_object(10).unwrap();
        assert_eq!(door.frame_of(1, -1), (0, 54));
        assert_eq!(door.frame_of(36, -1), (54, 0));

        // A statue: 55 to a row, then down.
        let statue = tile_object(105).unwrap();
        assert_eq!(statue.frame_of(1, -1), (36, 0));
        assert_eq!(statue.frame_of(55, -1), (0, 54));
    }

    use super::*;

    /// Every object's style survives a trip out to a frame and back.
    ///
    /// This is the property the drop table depends on: a chair mined is only a frame, and it has
    /// to name the same style the item that placed it did.
    #[test]
    fn a_style_round_trips_through_its_frame() {
        let mut checked = 0;
        for block in 0..crate::tile_sets::TILE_COUNT {
            let Some(object) = tile_object(block) else {
                continue;
            };
            for style in 0..40 {
                let (fx, fy) = object.frame_of(style, -1);
                // Frames are i16 in the world; a style past the sheet is not a real style.
                if fx > i32::from(i16::MAX) || fy > i32::from(i16::MAX) {
                    break;
                }
                let back = object.style_of(fx as i16, fy as i16);
                assert_eq!(
                    back, style,
                    "tile {block} style {style} framed to ({fx}, {fy}) and came back as {back}"
                );
                checked += 1;
            }
        }
        assert!(checked > 5_000, "only checked {checked} styles");
    }

    /// Any cell of an object names the corner it belongs to.
    #[test]
    fn every_cell_points_back_at_its_corner() {
        for block in 0..crate::tile_sets::TILE_COUNT {
            let Some(object) = tile_object(block) else {
                continue;
            };
            let (fx, fy) = object.frame_of(0, -1);
            if fx > i32::from(i16::MAX) || fy > i32::from(i16::MAX) {
                continue;
            }
            for dx in 0..object.width {
                for dy in 0..object.height {
                    let cell_x = fx + dx * (object.coord_width + object.padding);
                    let cell_y = fy
                        + object.coord_heights[..dy as usize]
                            .iter()
                            .map(|h| h + object.padding)
                            .sum::<i32>();
                    if cell_x > i32::from(i16::MAX) || cell_y > i32::from(i16::MAX) {
                        continue;
                    }
                    let at = origin_of(block, cell_x as i16, cell_y as i16);
                    assert_eq!(
                        at,
                        Some((dx, dy)),
                        "tile {block} cell ({dx}, {dy}) framed to ({cell_x}, {cell_y})"
                    );
                }
            }
        }
    }

    /// A chest is two by two and its styles run across the sheet; a door is one by three and
    /// its styles run down it. Getting either backwards puts furniture through the floor.
    #[test]
    fn the_shapes_are_what_they_should_be() {
        let chest = tile_object(21).expect("chests are objects");
        assert_eq!((chest.width, chest.height), (2, 2));
        let door = tile_object(10).expect("doors are objects");
        assert_eq!((door.width, door.height), (1, 3));
    }
}"##;

/// `TileObjectBaseModule`: where `Width`, `Height` and `Origin` live.
#[derive(Clone)]
struct Base {
    width: i64,
    height: i64,
    origin: (i64, i64),
}

/// `TileObjectCoordinatesModule`, including the memoised results of `Calculate`.
#[derive(Clone)]
struct Coords {
    width: i64,
    heights: Vec<i64>,
    padding: i64,
    pad_fix: (i64, i64),
    style_width: i64,
    style_height: i64,
    calculated: bool,
}

/// `TileObjectStyleModule`. Note that `styleLineSkip` starts at 1, not 0: `SetupBaseObject` never
/// assigns it, so the module constructor's own default is what every tile inherits.
#[derive(Clone)]
struct StyleMod {
    style: i64,
    horizontal: bool,
    wrap_limit: i64,
    multiplier: i64,
    line_skip: i64,
}

/// One `TileObjectData`. The three modules are shared by reference exactly as the game shares
/// them, and `own_*` is its `_hasOwn*`: false means the next write clones first.
#[derive(Clone)]
struct Obj {
    base: Rc<RefCell<Base>>,
    coords: Rc<RefCell<Coords>>,
    style: Rc<RefCell<StyleMod>>,
    own_base: bool,
    own_coords: bool,
    own_style: bool,
    subtiles: Vec<Option<Obj>>,
    own_subtiles: bool,
}

/// The copy-on-write half of every setter: a private copy of a module that was shared until now.
fn detach<T: Clone>(shared: &Rc<RefCell<T>>) -> Rc<RefCell<T>> {
    let own = shared.borrow().clone();
    Rc::new(RefCell::new(own))
}

impl Obj {
    /// `SetupBaseObject`: the one object built from nothing.
    fn base_object() -> Obj {
        Obj {
            base: Rc::new(RefCell::new(Base {
                width: 1,
                height: 1,
                origin: (0, 0),
            })),
            coords: Rc::new(RefCell::new(Coords {
                width: 0,
                heights: vec![16],
                padding: 0,
                pad_fix: (0, 0),
                style_width: 0,
                style_height: 0,
                calculated: false,
            })),
            style: Rc::new(RefCell::new(StyleMod {
                style: 0,
                horizontal: false,
                wrap_limit: 0,
                multiplier: 1,
                line_skip: 1,
            })),
            own_base: true,
            own_coords: true,
            own_style: true,
            subtiles: Vec::new(),
            own_subtiles: true,
        }
    }

    /// `new TileObjectData(_baseObject)`: a fresh object that shares the base's modules and owns
    /// none of them.
    fn from(parent: &Obj) -> Obj {
        let mut fresh = parent.clone();
        fresh.own_base = false;
        fresh.own_coords = false;
        fresh.own_style = false;
        fresh.subtiles = Vec::new();
        fresh.own_subtiles = false;
        fresh
    }

    /// `CopyFrom`: reference assignment, and deliberately without touching `own_*`.
    fn copy_from(&mut self, other: &Obj) {
        self.base = Rc::clone(&other.base);
        self.coords = Rc::clone(&other.coords);
        self.style = Rc::clone(&other.style);
    }

    fn full_copy_from(&mut self, other: &Obj) {
        self.copy_from(other);
        self.subtiles = other.subtiles.clone();
        self.own_subtiles = true;
    }

    fn set_width(&mut self, value: i64) {
        if !self.own_base {
            if self.base.borrow().width == value {
                return;
            }
            self.clone_base();
        }
        self.base.borrow_mut().width = value;
    }

    fn set_height(&mut self, value: i64) {
        if !self.own_base {
            if self.base.borrow().height == value {
                return;
            }
            self.clone_base();
        }
        self.base.borrow_mut().height = value;
    }

    fn set_origin(&mut self, value: (i64, i64)) {
        if !self.own_base {
            if self.base.borrow().origin == value {
                return;
            }
            // `Origin` does not drag the coordinate module with it; only `Width` and `Height` do.
            self.base = detach(&self.base);
            self.own_base = true;
        }
        self.base.borrow_mut().origin = value;
    }

    /// The `Width`/`Height` copy-on-write, which also forces a private coordinate module and
    /// clears `calculated`, because `Calculate` reads `Width` (`TileObjectData.cs:1194-1200`).
    fn clone_base(&mut self) {
        self.base = detach(&self.base);
        self.own_base = true;
        if !self.own_coords {
            self.coords = detach(&self.coords);
            self.own_coords = true;
            self.coords.borrow_mut().calculated = false;
        }
    }

    fn set_coord(&mut self, field: &str, value: &Value) {
        {
            let coords = self.coords.borrow();
            let same = match field {
                "CoordinateWidth" => coords.width == value.int(),
                "CoordinatePadding" => coords.padding == value.int(),
                "CoordinatePaddingFix" => coords.pad_fix == value.point(),
                "CoordinateHeights" => coords.heights == value.ints(),
                _ => unreachable!("{field}"),
            };
            if !self.own_coords && same {
                return;
            }
        }
        if !self.own_coords {
            self.coords = detach(&self.coords);
            self.own_coords = true;
        }
        let mut coords = self.coords.borrow_mut();
        match field {
            "CoordinateWidth" => coords.width = value.int(),
            "CoordinatePadding" => coords.padding = value.int(),
            "CoordinatePaddingFix" => coords.pad_fix = value.point(),
            "CoordinateHeights" => coords.heights = value.ints(),
            _ => unreachable!("{field}"),
        }
        coords.calculated = false;
    }

    fn set_style(&mut self, field: &str, value: &Value) {
        {
            let style = self.style.borrow();
            let same = match field {
                "Style" => style.style == value.int(),
                "StyleHorizontal" => style.horizontal == value.flag(),
                "StyleWrapLimit" => style.wrap_limit == value.int(),
                "StyleMultiplier" => style.multiplier == value.int(),
                "StyleLineSkip" => style.line_skip == value.int(),
                _ => unreachable!("{field}"),
            };
            if !self.own_style && same {
                return;
            }
        }
        if !self.own_style {
            self.style = detach(&self.style);
            self.own_style = true;
        }
        let mut style = self.style.borrow_mut();
        match field {
            "Style" => style.style = value.int(),
            "StyleHorizontal" => style.horizontal = value.flag(),
            "StyleWrapLimit" => style.wrap_limit = value.int(),
            "StyleMultiplier" => style.multiplier = value.int(),
            "StyleLineSkip" => style.line_skip = value.int(),
            _ => unreachable!("{field}"),
        }
    }

    fn calculate(&self) {
        let width = self.base.borrow().width;
        let mut coords = self.coords.borrow_mut();
        if coords.calculated {
            return;
        }
        coords.calculated = true;
        coords.style_width = (coords.width + coords.padding) * width + coords.pad_fix.0;
        let total: i64 = coords.heights.iter().map(|h| h + coords.padding).sum();
        coords.style_height = total + coords.pad_fix.1;
    }
}

/// A right-hand side this interpreter understands. Anything else (anchors, hooks, draw offsets)
/// parses to [`Value::Other`] and is dropped, because no field of the emitted table reads it.
enum Value {
    Int(i64),
    Flag(bool),
    Point(i64, i64),
    Ints(Vec<i64>),
    Other,
}

impl Value {
    fn int(&self) -> i64 {
        match self {
            Value::Int(n) => *n,
            _ => panic!("not an integer"),
        }
    }

    fn flag(&self) -> bool {
        match self {
            Value::Flag(b) => *b,
            _ => panic!("not a bool"),
        }
    }

    fn point(&self) -> (i64, i64) {
        match self {
            Value::Point(x, y) => (*x, *y),
            _ => panic!("not a Point16"),
        }
    }

    fn ints(&self) -> Vec<i64> {
        match self {
            Value::Ints(v) => v.clone(),
            _ => panic!("not an int array"),
        }
    }
}

/// Fold the method body into one logical statement per entry.
///
/// Multi-line array and `Rectangle[,]` initialisers are the only continuations in `Initialize`,
/// and every one of them ends in `;`, so accumulating until a semicolon lands is enough. The
/// braces inside such an initialiser get swallowed with it, which is the point: they must not
/// reach the block walker as if they opened a scope.
fn statements(body: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut pending = String::new();
    for raw in body.lines() {
        let line = raw.trim();
        if line.is_empty() {
            continue;
        }
        if pending.is_empty() && (line == "{" || line == "}" || line.starts_with("for (")) {
            out.push(line.to_string());
            continue;
        }
        if !pending.is_empty() {
            pending.push(' ');
        }
        pending.push_str(line);
        if pending.ends_with(';') {
            out.push(std::mem::take(&mut pending));
        }
    }
    assert!(pending.is_empty(), "statement never terminated: {pending}");
    out
}

struct Patterns {
    assign: Regex,
    call: Regex,
    add: Regex,
    for_loop: Regex,
    reset: Regex,
    local: Regex,
    point: Regex,
    int_array: Regex,
    empty_array: Regex,
    wrap_sum: Regex,
    number: Regex,
}

impl Patterns {
    fn new() -> Patterns {
        Patterns {
            assign: Regex::new(r"^(newTile|newSubTile|newAlternate)\.(\w+) = (.*);$").unwrap(),
            call: Regex::new(r"^(newTile|newSubTile|newAlternate)\.(\w+)\((.*)\);$").unwrap(),
            add: Regex::new(r"^add(Tile|BaseTile|SubTileRange|SubTile|Alternate)\((.*)\);$")
                .unwrap(),
            for_loop: Regex::new(r"^for \(int (\w+) = (\w+); \w+ (<=|<) ([\w.]+); \w+\+\+\)$")
                .unwrap(),
            reset: Regex::new(
                r"^(newTile|newSubTile|newAlternate) = new TileObjectData\(_baseObject\);$",
            )
            .unwrap(),
            local: Regex::new(r"^int (\w+) = (\d+);$").unwrap(),
            point: Regex::new(r"^new Point16\((-?\w+), (-?\w+)\)$").unwrap(),
            int_array: Regex::new(r"^new int\[\d*\]\s*\{(.*)\}$").unwrap(),
            empty_array: Regex::new(r"^new int\[(\d+)\]$").unwrap(),
            wrap_sum: Regex::new(r"^(\d+) \+ newTile\.StyleWrapLimit$").unwrap(),
            number: Regex::new(r"-?\d+").unwrap(),
        }
    }
}

struct Interpreter {
    re: Patterns,
    base_object: Obj,
    cur: BTreeMap<String, Obj>,
    named: BTreeMap<String, Obj>,
    locals: BTreeMap<String, i64>,
    data: BTreeMap<u32, Obj>,
}

impl Interpreter {
    fn new() -> Interpreter {
        let base_object = Obj::base_object();
        let mut cur = BTreeMap::new();
        for name in ["newTile", "newSubTile", "newAlternate"] {
            cur.insert(name.to_string(), Obj::from(&base_object));
        }
        Interpreter {
            re: Patterns::new(),
            base_object,
            cur,
            named: BTreeMap::new(),
            locals: BTreeMap::new(),
            data: BTreeMap::new(),
        }
    }

    fn value(&self, token: &str) -> Value {
        let token = token.trim();
        if token == "true" {
            return Value::Flag(true);
        }
        if token == "false" {
            return Value::Flag(false);
        }
        if let Ok(n) = token.parse::<i64>() {
            return Value::Int(n);
        }
        if token == "Point16.Zero" {
            return Value::Point(0, 0);
        }
        if let Some(caps) = self.re.point.captures(token) {
            // `new Point16(0, k)` inside a loop: a component can be the loop variable.
            let component = |raw: &str| match raw.parse::<i64>() {
                Ok(n) => n,
                Err(_) => *self
                    .locals
                    .get(raw)
                    .unwrap_or_else(|| panic!("no local {raw}")),
            };
            return Value::Point(component(&caps[1]), component(&caps[2]));
        }
        if let Some(caps) = self.re.int_array.captures(token) {
            return Value::Ints(
                self.re
                    .number
                    .find_iter(&caps[1])
                    .map(|m| m.as_str().parse().unwrap())
                    .collect(),
            );
        }
        if let Some(caps) = self.re.empty_array.captures(token) {
            return Value::Ints(vec![0; caps[1].parse().unwrap()]);
        }
        if let Some(n) = self.locals.get(token) {
            return Value::Int(*n);
        }
        Value::Other
    }

    /// An `addTile`/`addSubTile` argument: a literal, a loop variable, or the one small sum.
    fn arg(&self, token: &str) -> i64 {
        let token = token.trim();
        if let Ok(n) = token.parse::<i64>() {
            return n;
        }
        if let Some(n) = self.locals.get(token) {
            return *n;
        }
        if let Some(caps) = self.re.wrap_sum.captures(token) {
            let offset: i64 = caps[1].parse().unwrap();
            return offset + self.cur["newTile"].style.borrow().wrap_limit;
        }
        panic!("unhandled argument {token:?}");
    }

    fn run(&mut self, stmts: &[String]) {
        let mut i = 0;
        while i < stmts.len() {
            i = self.step(stmts, i);
        }
    }

    /// The half-open range of the `{ ... }` block starting at `i`.
    fn block(stmts: &[String], i: usize) -> (usize, usize) {
        assert_eq!(stmts[i], "{", "block does not open at {i}");
        let mut depth = 0;
        for (j, stmt) in stmts.iter().enumerate().skip(i) {
            if stmt == "{" {
                depth += 1;
            } else if stmt == "}" {
                depth -= 1;
                if depth == 0 {
                    return (i + 1, j);
                }
            }
        }
        panic!("unbalanced block");
    }

    fn step(&mut self, stmts: &[String], i: usize) -> usize {
        let line = stmts[i].as_str();

        if let Some(caps) = self.re.for_loop.captures(line) {
            let (var, start, op, end) = (
                caps[1].to_string(),
                caps[2].to_string(),
                caps[3].to_string(),
                caps[4].to_string(),
            );
            let (body_start, body_end) = Interpreter::block(stmts, i + 1);
            let bound = |token: &str| -> Option<i64> {
                token
                    .parse::<i64>()
                    .ok()
                    .or_else(|| self.locals.get(token).copied())
            };
            // `for (int i = 0; i < TileID.Count; i++) { _data.Add(null); }` is the only loop whose
            // bound is not a number or a local, and it writes nothing this table reads.
            if let (Some(lo), Some(hi)) = (bound(&start), bound(&end)) {
                let last = if op == "<=" { hi + 1 } else { hi };
                let body: Vec<String> = stmts[body_start..body_end].to_vec();
                for n in lo..last {
                    self.locals.insert(var.clone(), n);
                    self.run(&body);
                }
                self.locals.remove(&var);
            }
            return body_end + 1;
        }

        if line == "{" || line == "}" {
            return i + 1;
        }

        if let Some(caps) = self.re.local.captures(line) {
            self.locals
                .insert(caps[1].to_string(), caps[2].parse().unwrap());
            return i + 1;
        }

        if let Some(caps) = self.re.reset.captures(line) {
            let fresh = Obj::from(&self.base_object);
            self.cur.insert(caps[1].to_string(), fresh);
            return i + 1;
        }

        if let Some(caps) = self.re.assign.captures(line) {
            let (target, field, rhs) = (
                caps[1].to_string(),
                caps[2].to_string(),
                caps[3].to_string(),
            );
            self.assign(&target, &field, &rhs);
            return i + 1;
        }

        if let Some(caps) = self.re.call.captures(line) {
            let (target, method, args) = (
                caps[1].to_string(),
                caps[2].to_string(),
                caps[3].to_string(),
            );
            self.method(&target, &method, &args);
            return i + 1;
        }

        if let Some(caps) = self.re.add.captures(line) {
            let (kind, args) = (caps[1].to_string(), caps[2].to_string());
            self.add(&kind, &args);
            return i + 1;
        }

        // Everything left assigns a field this table does not carry: anchors, hooks, draw offsets,
        // the `_data` bookkeeping, and the four hand-rolled alternate pushes.
        i + 1
    }

    fn assign(&mut self, target: &str, field: &str, rhs: &str) {
        let value = self.value(rhs);
        let obj = self.cur.get_mut(target).expect("unknown target");
        match field {
            "Width" => obj.set_width(value.int()),
            "Height" => obj.set_height(value.int()),
            "Origin" => obj.set_origin(value.point()),
            "CoordinateWidth"
            | "CoordinatePadding"
            | "CoordinatePaddingFix"
            | "CoordinateHeights" => obj.set_coord(field, &value),
            "Style" | "StyleHorizontal" | "StyleWrapLimit" | "StyleMultiplier"
            | "StyleLineSkip" => obj.set_style(field, &value),
            _ => {}
        }
    }

    fn method(&mut self, target: &str, method: &str, args: &str) {
        match method {
            "CopyFrom" => {
                let source = self.resolve(args);
                self.cur.get_mut(target).expect("target").copy_from(&source);
            }
            "FullCopyFrom" => {
                let source = match args.trim().parse::<u32>() {
                    Ok(tile) => self.tile_data(tile),
                    Err(_) => self.resolve(args),
                };
                self.cur
                    .get_mut(target)
                    .expect("target")
                    .full_copy_from(&source);
            }
            "Calculate" => self.cur[target].calculate(),
            // `ApplyNaturalObjectRules` touches only the placement flags.
            _ => {}
        }
    }

    /// `GetTileData(type, 0)`: the style-0 sub-tile when there is one, else the tile itself.
    fn tile_data(&self, tile: u32) -> Obj {
        let entry = self.data.get(&tile).expect("tile not added yet");
        match entry.subtiles.first() {
            Some(Some(sub)) => sub.clone(),
            _ => entry.clone(),
        }
    }

    fn resolve(&self, name: &str) -> Obj {
        let name = name.trim();
        self.cur
            .get(name)
            .or_else(|| self.named.get(name))
            .unwrap_or_else(|| panic!("unknown object {name}"))
            .clone()
    }

    fn add(&mut self, kind: &str, args: &str) {
        match kind {
            "Tile" | "BaseTile" => {
                let tile = self.cur["newTile"].clone();
                tile.calculate();
                if kind == "Tile" {
                    self.data.insert(self.arg(args) as u32, tile);
                } else {
                    self.named
                        .insert(args.replace("out ", "").trim().to_string(), tile);
                }
                let fresh = Obj::from(&self.base_object);
                self.cur.insert("newTile".to_string(), fresh);
            }
            "SubTile" | "SubTileRange" => {
                let sub = self.cur["newSubTile"].clone();
                sub.calculate();
                let styles: Vec<i64> = if kind == "SubTile" {
                    args.split(',').map(|a| self.arg(a)).collect()
                } else {
                    let parts: Vec<i64> = args.split(',').map(|a| self.arg(a)).collect();
                    (parts[0]..parts[0] + parts[1]).collect()
                };
                let tile = self.cur.get_mut("newTile").expect("newTile");
                if !tile.own_subtiles {
                    tile.subtiles = Vec::new();
                    tile.own_subtiles = true;
                }
                for style in styles {
                    let style = style as usize;
                    while tile.subtiles.len() <= style {
                        tile.subtiles.push(None);
                    }
                    tile.subtiles[style] = Some(sub.clone());
                }
                let fresh = Obj::from(&self.base_object);
                self.cur.insert("newSubTile".to_string(), fresh);
            }
            "Alternate" => {
                let base_style = self.arg(args);
                {
                    let alt = self.cur.get_mut("newAlternate").expect("newAlternate");
                    alt.calculate();
                    alt.set_style("Style", &Value::Int(base_style));
                }
                let fresh = Obj::from(&self.base_object);
                self.cur.insert("newAlternate".to_string(), fresh);
            }
            _ => unreachable!("{kind}"),
        }
    }
}

/// One emitted row.
struct Entry {
    width: i64,
    height: i64,
    origin: (i64, i64),
    coord_width: i64,
    coord_heights: Vec<i64>,
    padding: i64,
    full_width: i64,
    full_height: i64,
    style_horizontal: bool,
    style_multiplier: i64,
    style_wrap: i64,
    style_line_skip: i64,
    style_base: i64,
}

fn parse(root: &Path) -> BTreeMap<u32, Entry> {
    let text = read_lossy(&root.join("Terraria.ObjectData/TileObjectData.cs"));
    let lines: Vec<&str> = text.lines().collect();
    let start = lines
        .iter()
        .position(|l| l.trim() == "public static void Initialize()")
        .expect("no Initialize in TileObjectData.cs");
    // Bounded by the method's own braces: `TileObjectData.cs` carries plenty of later methods that
    // would otherwise be read as more of the same program.
    let mut depth = 0;
    let mut seen = false;
    let mut end = None;
    for (offset, line) in lines[start..].iter().enumerate() {
        depth += line.matches('{').count() as i64 - line.matches('}').count() as i64;
        if line.contains('{') {
            seen = true;
        }
        if seen && depth == 0 {
            end = Some(start + offset);
            break;
        }
    }
    let end = end.expect("Initialize never closes");

    let mut interpreter = Interpreter::new();
    let body = lines[start + 1..end].join("\n");
    interpreter.run(&statements(&body));

    let mut out = BTreeMap::new();
    for (tile, obj) in &interpreter.data {
        obj.calculate();
        let base = obj.base.borrow();
        let coords = obj.coords.borrow();
        let style = obj.style.borrow();
        out.insert(
            *tile,
            Entry {
                width: base.width,
                height: base.height,
                origin: base.origin,
                coord_width: coords.width,
                coord_heights: coords.heights.clone(),
                padding: coords.padding,
                full_width: coords.style_width,
                full_height: coords.style_height,
                style_horizontal: style.horizontal,
                style_multiplier: style.multiplier,
                style_wrap: style.wrap_limit,
                style_line_skip: style.line_skip,
                style_base: style.style,
            },
        );
    }
    assert!(
        out.len() > 300,
        "only {} objects read out of Initialize",
        out.len()
    );
    out
}

pub fn generate(root: &Path) -> String {
    let entries = parse(root);
    let mut table = String::from("pub fn tile_object(block: u16) -> Option<TileObject> {\n");
    table.push_str("    Some(match block {\n");
    for (tile, entry) in &entries {
        let heights: Vec<String> = entry.coord_heights.iter().map(|h| h.to_string()).collect();
        table.push_str(&format!(
            "        {tile} => TileObject {{\n\
             \x20           width: {},\n\
             \x20           height: {},\n\
             \x20           origin: ({}, {}),\n\
             \x20           coord_width: {},\n\
             \x20           coord_heights: &[{}],\n\
             \x20           padding: {},\n\
             \x20           full_width: {},\n\
             \x20           full_height: {},\n\
             \x20           style_horizontal: {},\n\
             \x20           style_multiplier: {},\n\
             \x20           style_wrap: {},\n\
             \x20           style_line_skip: {},\n\
             \x20           style_base: {},\n\
             \x20       }},\n",
            entry.width,
            entry.height,
            entry.origin.0,
            entry.origin.1,
            entry.coord_width,
            heights.join(", "),
            entry.padding,
            entry.full_width,
            entry.full_height,
            entry.style_horizontal,
            entry.style_multiplier,
            entry.style_wrap,
            entry.style_line_skip,
            entry.style_base,
        ));
    }
    table.push_str("        _ => return None,\n    })\n}");
    format!("{MODULE_DOC}\n\n{HEAD}\n{table}\n\n{TAIL}\n")
}
