#!/usr/bin/env bash
#
# The README's comparison table, measured rather than remembered.
#
#   ./tools/compare_vanilla.sh
#
# Startup, idle CPU, idle RAM and idle bandwidth for the real Terraria dedicated server and for
# terrustia, on one and the same world, with nobody connected.
#
# ## Why this script exists
#
# The four numbers in README.md were measured by hand once and the method lived nowhere, so
# "refresh the table" was an afternoon of remembering how rather than a command. An unrepeatable
# measurement is the same problem this project keeps finding in its own checkers: it cannot be
# re-run, so a stale number and a current one look identical.
#
# ## What it does and does not claim
#
# It measures an *idle* server, which is what the README's table says it is measuring, and that is
# the honest thing to compare: it is the cost of simply being up, which is what somebody paying for
# a box cares about. It is not a claim about behaviour under load. Loaded numbers come from
# `tools/soak_scale.sh` and `docs/performance.md`, which measure per-phase tick cost against the
# 16,666 us budget and are the numbers that matter for whether the server plays well.
#
# Both servers load the SAME world file, generated by vanilla, for the reason `differential.sh`
# spells out at length: a fresh-versus-fresh comparison measures two different worlds. Here it also
# removes world size as a variable from the RSS figure, which is most of it.
#
# ## Method
#
#   Startup   wall clock from exec to the server's own "ready"/"Server started" line.
#   CPU idle  ps's accumulated CPU time across a fixed window, as a percentage of one core. Not
#             ps's instantaneous %CPU, which is an average since process start and so is dominated
#             by world loading on a sample taken this soon.
#   RAM idle  peak RSS over the window. Peak, not final: a quiet world pages out (see
#             docs/performance.md), so a single late sample flatters both servers unequally.
#   Bandwidth bytes on the listening socket over the window, with nobody connected. An idle server
#             with no clients should send nothing at all; whatever it does send is the number.
#
# Requires the real server. Override its path with TERRARIA_SERVER=.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VANILLA="${TERRARIA_SERVER:-$HOME/Library/Application Support/Steam/steamapps/common/Terraria/Terraria.app/Contents/MacOS/TerrariaServer}"
BIN="$ROOT/target/release/terrustia"
# Long enough that a per-second housekeeping tick lands several times and a single scheduling
# hiccup cannot dominate; short enough to rerun after three merges without thinking about it.
WINDOW="${COMPARE_WINDOW:-300}"
SEED="${COMPARE_SEED:-1337}"
KEEP="${COMPARE_KEEP:-0}"

WORK="$(mktemp -d)"
VSRV=""
OSRV=""
cleanup() {
  [ -n "$VSRV" ] && { echo exit > "$WORK/vfifo" 2>/dev/null & sleep 2; kill "$VSRV" 2>/dev/null; }
  [ -n "$OSRV" ] && kill "$OSRV" 2>/dev/null
  wait "$VSRV" "$OSRV" 2>/dev/null
  if [ "$KEEP" = 1 ]; then echo "run directory kept: $WORK"; else rm -rf "$WORK"; fi
}
trap cleanup EXIT

[ -x "$BIN" ]     || { echo "build first: cargo build --release -p terrustia --bin terrustia"; exit 1; }
[ -x "$VANILLA" ] || { echo "no real server at: $VANILLA   (set TERRARIA_SERVER)"; exit 1; }

# A contended machine makes every one of these numbers worse, and unequally, because the two
# servers are measured one after the other rather than at once. Say so rather than quietly
# producing a table that will be pasted into a README as fact.
LOAD="$(uptime | sed 's/.*averages*: *//' | awk '{print $1}' | tr -d ',')"
BUSY=$(awk -v l="$LOAD" 'BEGIN { print (l > 2.0) ? 1 : 0 }')
if [ "$BUSY" = 1 ]; then
  echo "WARNING: load average is $LOAD. These numbers will be worse than the truth, and not"
  echo "         evenly between the two servers. Re-run on a quiet machine before publishing."
  echo
fi

VPORT=$((20000 + RANDOM % 20000))
OPORT=$((VPORT + 1))
GPORT=$((VPORT + 2))

wait_for() { # wait_for <file> <text> <seconds> <pid>
  for _ in $(seq 1 "$3"); do
    grep -qF "$2" "$1" 2>/dev/null && return 0
    kill -0 "$4" 2>/dev/null || { echo "FAIL: process exited before '$2'"; tail -20 "$1"; return 1; }
    sleep 0.2
  done
  echo "FAIL: never saw '$2' in $1"; tail -20 "$1"; return 1
}

# Accumulated CPU seconds for a pid, from ps's TIME column (`[dd-]hh:mm:ss`). Accumulated rather
# than instantaneous: ps's %CPU is an average over the whole life of the process, so on a server
# that has just loaded an 80 MB world it reports the load, not the idle.
cpu_seconds() { # cpu_seconds <pid>
  ps -o time= -p "$1" 2>/dev/null | tr -d ' ' | awk -F'[-:]' '{
    if (NF == 4)      { print $1*86400 + $2*3600 + $3*60 + $4 }
    else if (NF == 3) { print $1*3600 + $2*60 + $3 }
    else if (NF == 2) { print $1*60 + $2 }
    else              { print 0 }
  }'
}

rss_kb() { ps -o rss= -p "$1" 2>/dev/null | tr -d ' '; }

# The pid actually doing the work, which is not always the pid a launcher's `&` gave us. Steam's
# macOS build ships the real server behind a MonoKickstart wrapper
# (`Terraria.app/Contents/MacOS/TerrariaServer`, a bash script) that runs
# `./TerrariaServer.bin.osx $@` as a plain child - no `exec` - so the wrapper's own pid sits idle
# for the server's whole life while the child does everything. Measuring the wrapper reads as a
# server using ~0% CPU and a couple of megabytes of RAM regardless of load, which is wrong rather
# than merely approximate. Walk to the deepest live child; a launcher that already execs into the
# real binary (Linux, or terrustia's own single process) has no child and this returns the pid
# unchanged.
descendant_pid() { # descendant_pid <pid>
  local pid="$1" child
  while true; do
    child="$(pgrep -P "$pid" 2>/dev/null | head -1)"
    [ -n "$child" ] || break
    pid="$child"
  done
  echo "$pid"
}

# Bytes sent by this pid, summed over its sockets. `nettop` is per-process and present on every
# mac; it is sampled twice and differenced rather than trusted as a total.
#
# Column 6, not 5: the header is `time,,interface,state,bytes_in,bytes_out,...`, so the empty
# second field shifts everything one right of where a reading of the header names suggests.
# Non-numeric rows (the header, and nettop's own summary lines) are skipped rather than coerced,
# because awk would silently read them as zero and a bandwidth of zero is exactly the answer this
# is trying to distinguish from a real one.
#
# `-L 1` and not more: each sample prints its own row carrying the *cumulative* total, so summing
# across `-L 2` reports exactly twice the real figure and `-L 3` three times. Measured, not assumed:
# 16936, 33872, 50808 for the same idle process.
# A pid nettop said nothing numeric about is not a pid that sent nothing, and printing 0 for both
# is the one thing this function must not do: the README's "100% less" row is computed from it, so
# a nettop that returned no rows at all (a pid already gone, a future macOS wanting different
# privileges) would publish as a perfect score. Verified 2026-09-08 that an idle terrustia does
# yield a row - `terrustia.<pid>,,,0,0` - so the zero in the table is measured and not this case.
bytes_out() { # bytes_out <pid>; prints bytes, or "none" if nettop reported nothing numeric
  nettop -P -x -L 1 -p "$1" 2>/dev/null |
    awk -F, '$6 ~ /^[0-9]+$/ { s += $6; n++ } END { if (n) print s; else print "none" }'
}

# Watch a running server for WINDOW seconds and print "cpu_pct peak_rss_kb bytes_sent".
watch_idle() { # watch_idle <pid>
  local pid="$1" c0 c1 b0 b1 peak=0 now
  c0="$(cpu_seconds "$pid")"
  b0="$(bytes_out "$pid")"
  for _ in $(seq 1 "$WINDOW"); do
    now="$(rss_kb "$pid")"
    [ -n "$now" ] && [ "$now" -gt "$peak" ] && peak="$now"
    kill -0 "$pid" 2>/dev/null || break
    sleep 1
  done
  c1="$(cpu_seconds "$pid")"
  b1="$(bytes_out "$pid")"
  # Carry the unmeasured case through as -1 rather than folding it into 0, so the caller can print
  # it as unmeasured instead of as a win.
  if [ "$b0" = none ] || [ "$b1" = none ]; then
    awk -v c0="$c0" -v c1="$c1" -v w="$WINDOW" -v p="$peak" \
      'BEGIN { printf "%.2f %d -1\n", (c1 - c0) * 100.0 / w, p }'
    return
  fi
  awk -v c0="$c0" -v c1="$c1" -v w="$WINDOW" -v p="$peak" -v b0="$b0" -v b1="$b1" \
    'BEGIN { printf "%.2f %d %d\n", (c1 - c0) * 100.0 / w, p, (b1 - b0 < 0 ? 0 : b1 - b0) }'
}

# ---------------------------------------------------------------- one world, written by vanilla

cat > "$WORK/gen.txt" <<END
world=$WORK/base.wld
autocreate=2
seed=$SEED
worldname=compareworld
difficulty=0
maxplayers=8
port=$GPORT
secure=0
upnp=0
END

echo "=== generating the shared world with the real server (seed $SEED, large) ==="
mkfifo "$WORK/gfifo"
"$VANILLA" -config "$WORK/gen.txt" < "$WORK/gfifo" > "$WORK/gen.log" 2>&1 &
GEN=$!
exec 9> "$WORK/gfifo"
wait_for "$WORK/gen.log" "Server started" 900 "$GEN" || exit 1
echo exit >&9
for _ in $(seq 1 60); do kill -0 "$GEN" 2>/dev/null || break; sleep 1; done
kill "$GEN" 2>/dev/null
exec 9>&-
[ -s "$WORK/base.wld" ] || { echo "FAIL: the real server wrote no world"; tail -20 "$WORK/gen.log"; exit 1; }
cp "$WORK/base.wld" "$WORK/vanilla.wld"
cp "$WORK/base.wld" "$WORK/ours.wld"
echo "world: $(wc -c < "$WORK/base.wld" | tr -d ' ') bytes, one copy each"
echo

# ---------------------------------------------------------------- the real server, idle

cat > "$WORK/vanilla.txt" <<END
world=$WORK/vanilla.wld
maxplayers=8
port=$VPORT
secure=0
upnp=0
END

echo "=== the real server, idle for ${WINDOW}s ==="
mkfifo "$WORK/vfifo"
VSTART="$(date +%s.%N)"
"$VANILLA" -config "$WORK/vanilla.txt" < "$WORK/vfifo" > "$WORK/vanilla.log" 2>&1 &
VSRV=$!
exec 8> "$WORK/vfifo"
wait_for "$WORK/vanilla.log" "Server started" 600 "$VSRV" || exit 1
VREADY="$(awk -v a="$VSTART" -v b="$(date +%s.%N)" 'BEGIN { printf "%.2f", b - a }')"
VMPID="$(descendant_pid "$VSRV")"
read -r VCPU VRSS VNET <<<"$(watch_idle "$VMPID")"
echo exit >&8
sleep 2
exec 8>&-
kill "$VMPID" 2>/dev/null; kill "$VSRV" 2>/dev/null; wait "$VSRV" 2>/dev/null; VSRV=""

# Wait for the real server process to be *gone*, not merely signalled.
#
# `wait "$VSRV"` only reaps the wrapper job; `$VMPID` is the actual TerrariaServer underneath it,
# and on the way out it writes and fsyncs its own copy of the world - several megabytes. Starting
# terrustia into that means timing its startup against a disk that is still busy, and that is not a
# small effect: a quiet-machine run measured terrustia at 3.46 s where the same binary loads the
# same class of world in 0.46 s once the disk is idle. The number was nearly published.
for _ in $(seq 1 300); do
  kill -0 "$VMPID" 2>/dev/null || break
  sleep 0.1
done
# And give the filesystem a moment to finish the writes the process left behind.
sleep 1

# ---------------------------------------------------------------- terrustia, idle, same world

cat > "$WORK/ours.toml" <<END
world_file = "$WORK/ours.wld"
save_file = "$WORK/ours.wld"
listen = "0.0.0.0:$OPORT"
max_players = 8
autosave_secs = 300
update_check_enabled = false
upnp_enabled = false
END

echo "=== terrustia, idle for ${WINDOW}s, same world ==="
OSTART="$(date +%s.%N)"
"$BIN" -c "$WORK/ours.toml" --headless > "$WORK/ours.log" 2>&1 &
OSRV=$!
wait_for "$WORK/ours.log" "accepting connections" 600 "$OSRV" || exit 1
OREADY="$(awk -v a="$OSTART" -v b="$(date +%s.%N)" 'BEGIN { printf "%.2f", b - a }')"
read -r OCPU ORSS ONET <<<"$(watch_idle "$OSRV")"
kill "$OSRV" 2>/dev/null; wait "$OSRV" 2>/dev/null; OSRV=""

# ---------------------------------------------------------------- the table

ratio() { awk -v a="$1" -v b="$2" 'BEGIN { if (b == 0) print "n/a"; else printf "%.0fx", a / b }'; }

echo
echo "| | vanilla 1.4.5.8 | terrustia | |"
echo "|---|:---:|:---:|:---:|"
printf "| Startup | %s s | **%s s** | %s faster |\n" "$VREADY" "$OREADY" "$(ratio "$VREADY" "$OREADY")"
printf "| CPU, idle | %s%% of a core | **%s%%** | %s less |\n" "$VCPU" "$OCPU" "$(ratio "$VCPU" "$OCPU")"
printf "| RAM, idle | %s MB | **%s MB** | %s less |\n" \
  "$(awk -v k="$VRSS" 'BEGIN { printf "%.1f", k / 1024 }')" \
  "$(awk -v k="$ORSS" 'BEGIN { printf "%.1f", k / 1024 }')" \
  "$(ratio "$VRSS" "$ORSS")"
if [ "$VNET" = -1 ] || [ "$ONET" = -1 ]; then
  # nettop reported nothing for at least one of the two. Say so rather than printing a number: an
  # unmeasured row that reads as "0 B, 100% less" is the most flattering possible way to be wrong.
  printf "| Bandwidth over %s minutes | %s | %s | UNMEASURED: nettop returned no rows |\n" \
    "$(awk -v w="$WINDOW" 'BEGIN { printf "%g", w / 60 }')" \
    "$([ "$VNET" = -1 ] && echo "n/a" || echo "$VNET B")" \
    "$([ "$ONET" = -1 ] && echo "n/a" || echo "$ONET B")"
else
  printf "| Bandwidth over %s minutes | %s B | **%s B** | %s |\n" \
    "$(awk -v w="$WINDOW" 'BEGIN { printf "%g", w / 60 }')" "$VNET" "$ONET" \
    "$(awk -v a="$VNET" -v b="$ONET" 'BEGIN { if (a == 0) print "n/a"; else printf "%.0f%% less", (a - b) * 100.0 / a }')"
fi
echo
echo "load average during the run: $(uptime | sed 's/.*averages*: *//')"
[ "$BUSY" = 1 ] && echo "NOT PUBLISHABLE: the machine was contended. Re-run when quiet."
exit 0
